### ISSUE TITLE
Code Editor: [Mac IDE] GM unstable when renaming a Script/Shader when a custom layout is being used

### ISSUE THREAD

**Issue by SamTHodson** [YoYoGames/GameMaker-Bugs#1665]
### Description

Using the Mac IDE, GM goes unstable when creating and renaming a Script/Shader when a custom layout is being used.

```C++
[15:32:01:859(4ae2)] Loading project layout from: /Users/qa/Library/Application Support/GameMakerStudio2/samthodson_2804894/Layouts/11Sep2023/11Sep2023/11Sep2023.xml
[15:32:08:465(4ae2)] DoUndoableAction: 'Rename GMScript from Script2 to store'
[15:32:08:488(4ae2)] Fatal Error! 'UndoManager::DoUndoableAction - Object reference not set to an instance of an object.'
[15:32:08:488(4ae2)]    at YYCodeEditor.CodeFolding.StoredRegionState.DocumentRenamed(String _oldPath, String _newPath)
   at YYCodeEditor.CodeEditor.RenameDocument(String _oldFilename, String _newFilename)
   at YoYoStudio.Utils.DocumentHelper.RenameDocument(String _previousFile, String _newFile)
   at YoYoStudio.Resources.GMScriptAdapter.Renamed(String _oldName)
   at YoYoStudio.Core.Utils.UndoManager.DoUndoableAction(String _description, Object _objectsToTrack, Action _actionDelegate, Object _contextOverride)
[15:32:08:488(4ae2)] ####################################
[15:32:08:488(4ae2)] Break in FatalErrorWarning (IDE:4481)
[15:32:08:488(4ae2)] ####################################

``` 
Tested using IDE v2023.8.0.98 Runtime v2023.8.0.145.

[Contact Us Package](https://drive.google.com/file/d/1nCWDnTs4nBRcgt5iJNAMiOmv_HaMQ6qI/view?usp=drive_link)

### Steps To Reproduce

1. Start GameMaker and create/open a project
2. Load a layout via _Layouts > Load Layout_ (you'll have to create a new one if you do not have a previously saved layout)
3. Close the project and reopen it
4. Create a Script and instantly rename it 
5. Observe the IDE goes unstable

Repro: Most Times - Sometimes having a pre-applied layout did not cause the IDE to go unstable

### How reliably can you recreate this issue using your steps above?

Most Times

### Which version of GameMaker are you reporting this issue for?

2023.8 (Monthly)

### Which operating system(s) are you seeing the problem on?

macOS Ventura, macOS Big Sur

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by yerumaku** [comment]
Beta (2023.800.0.406) has this problem too.

**Comment by paxer** [comment]
related https://github.com/YoYoGames/GameMaker-Bugs/issues/1670

**Comment by SamTHodson** [comment]
Verified internally in Beta IDE v2023.1100.0.415  Runtime v2023.1100.0.436.
