### ISSUE TITLE
Startup: [Windows IDE] GM crash because MQTT server cannot start if using Proton to run on Kubuntu

### ISSUE THREAD

**Issue by YYDan** [YoYoGames/GameMaker-Bugs#1701]
### Description

Trying to use the Windows IDE on Kubuntu using Proton emulation shows GM crashes on startup in 2023.8.0 because the MQTT server cannot start.

The ui.log ends with this each time:

```
[19:37:32:998(4b41)] -----------------------------------------------------------------------
[KubuntuCrash.log](https://github.com/YoYoGames/GameMaker-Bugs/files/12606636/KubuntuCrash.log)
---------
[19:37:33:7(4b41)] IDE Exception: Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: Unknown error (0x80090027)
   at Internal.Cryptography.Helpers.GetProperty(SafeNCryptHandle ncryptHandle, String propertyName, CngPropertyOptions options)
   at System.Security.Cryptography.RSACng.ImportKeyBlob(Byte[] rsaBlob, Boolean includePrivate)
   at System.Security.Cryptography.RSACng.ImportParameters(RSAParameters parameters)
   at Internal.Cryptography.Pal.CertificatePal.CopyWithPrivateKey(RSA rsa)
   at System.Security.Cryptography.X509Certificates.RSACertificateExtensions.CopyWithPrivateKey(X509Certificate2 certificate, RSA privateKey)
   at System.Security.Cryptography.X509Certificates.CertificateRequest.CreateSelfSigned(DateTimeOffset notBefore, DateTimeOffset notAfter)
   at YoYoStudio.IDE.CreateSelfSignedCertificate(Byte[]& _caCert, Byte[]& _serverCertPEM, Byte[]& _rsaServer, Byte[]& _serverCertPFX, String& _thumb256)
   at YoYoStudio.IDE.MqttInitialise()
   at YoYoStudio.SplashScreen.SplashTick()
   at YoYoStudio.Plugins.MethodContainer.Call(Object[] _args)
   at YoYoStudio.Plugins.Command.Perform(Function _command, String _action, Object[] _parameters)
   at YoYoStudio.Plugins.Command.execute_object(String _command, Object _focus, Object[] paramaters)
   at YoYoStudio.Plugins.Command.execute(String _command, Object[] paramaters)
   at YoYoStudio.Plugins.Command.Perform(Function _command, String _action, Object[] _parameters)
   at YoYoStudio.Plugins.Command.execute_object(String _command, Object _focus, Object[] paramaters)
   at YoYoStudio.Plugins.Command.execute(String _command, Object[] paramaters)
   at YoYoStudio.IDE.Run()
   at YoYoStudio.IDE.Execute(String[] _args, Int32 _initialWidth, Int32 _initialHeight)
[19:37:33:7(4b41)] --------------------------------------------------------------------------------
```

_Steps are untested, as this is not a supported setup. Crash has been filed for wider discussion than Kubuntu support._

### Expected Change

GM should always start up - users who cannot run MQTT should simply be told this if they tried to use it in Target Manager/deploy a GX.games build

### Steps To Reproduce

1. Start GameMaker from Steam on a Kubuntu machine
2. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8 (Monthly)

### Are you running GameMaker from inside your Steam library?

Yes

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by rwkay** [comment]
I cannot run on Kubuntu but I have added exception handling around the certificate creation and the whole MQTT server initialisation... this fix will be in 2023.11, reopen this issue if it is still causing problems then
