### ISSUE TITLE
Licencing: 2023.8.2.106 crashes on startup if incomplete SSO keys are in the um.json due to a "bad request" error being returned by Web

### ISSUE THREAD

**Issue by YYDan** [YoYoGames/GameMaker-Bugs#1884]
### Description

2023.8.2 is unable to start for me if launched from Steam - it crashes during the Checking RSS phase. Looking at my log, I can see each time the licensing is blocked with a 401 and then two 400 errors, and then the IDE falls over trying to find the matching runtime version in the RSS feed.

For example:

[15:48:43:469(5942)] LoadingState: BeginUserLogin
[15:48:43:472(5942)] LoadingState: UserLogin
[15:48:43:518(5942)] CheckForUpdate : Skipping because running steam version
[15:48:44:27(5942)] DoRefreshAccessToken WebException httpStatusCode=Unauthorized, System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebRequest.<>c.<GetResponseAsync>b__68_2(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at A.d.c(String )
[15:48:44:30(5942)] SSO_TryRefresh Refresh Token empty - user is logged out
[15:48:44:582(5942)] SSO_CheckSubscription : Web Exception : System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebRequest.<>c.<GetResponseAsync>b__68_2(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at A.d.Q()
[15:48:44:928(5942)] SSO_FetchSubscriptionLicense: System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebRequest.<>c.<GetResponseAsync>b__68_2(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at A.d.R()
[15:48:44:988(5942)] LoadingState: Preferences
[15:48:45:18(5942)] LoadingState: CheckingRSS
[15:48:45:161(5942)] Error reading the RSS feed - System.NullReferenceException: Object reference not set to an instance of an object.
   at YoYoStudio.Runtime.RuntimeEntry.RequiredModules()
   at YoYoStudio.Runtime.RuntimeEntry.<>c__DisplayClass50_0.<MatchRuntimeJSON>b__0(Object a, Object b)
   at YoYoStudio.FileAPI.FileRequest.ResultOperation()
   at YoYoStudio.FileAPI.FileRequest.wait()
   at YoYoStudio.Runtime.RuntimeEntry.MatchRuntimeJSON(List`1 ret)
   at YoYoStudio.Runtime.RuntimeEntry.LoadRuntimeRSS(Stream _strm, String _feedURI)
   at A.d.A(String , List`1 )
[15:48:45:163(5942)] --------------------------------------------------------------------------------
[15:48:45:165(5942)] IDE Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at YoYoStudio.Runtime.RuntimeEntry.RequiredModules()
   at YoYoStudio.Runtime.RuntimeEntry.<>c__DisplayClass50_0.<MatchRuntimeJSON>b__0(Object a, Object b)
   at YoYoStudio.FileAPI.FileRequest.ResultOperation()
   at YoYoStudio.Core.Utils.FileAPI.ThreadedAsyncQueue.DispatchCompletedRequests(Int32 _amount)
   at YoYoStudio.FileAPI.FileSystem_Local.Tick(Boolean _applicationIsBackground)
   at YoYoStudio.FileAPI.FileSystem.Tick(Boolean _applicationIsBackground)
   at YoYoStudio.IDE.Tick()
   at YoYoStudio.IDE.Run()
   at YoYoStudio.IDE.Execute(String[] _args, Int32 _initialWidth, Int32 _initialHeight)
[15:48:45:166(5942)] --------------------------------------------------------------------------------
[15:48:45:167(5942)] ####################################

[ui.log](https://github.com/YoYoGames/Incoming-Bugs/files/12832475/ui.log)

### Expected Change

GM should not crash and should complete licensing and be able to download the guest runtimes

### Steps To Reproduce

1. Do not install the latest internal green via standalone.
2. Try to launch a Steam test-qa branch version (which IS the latest internal green)
3. Observe whether the IDE silently closes while Checking RSS... on the splash screen.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.8.2.106 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

Yes

### ui.log File

- [X] I have attached my ui.log file

### Sample .yyz File

- [ ] I have attached a small sample project

**Comment by rwkay** [comment]
Fixed in 2023.8.2

**Comment by YYDan** [comment]
Works fine now in IDE v2023.8.2.108. Closing.
