### ISSUE TITLE
IDE crashes on startup from v9.9.1.443

### ISSUE THREAD

**Issue by toby-yoyo** [YoYoGames/GameMaker-Bugs#1892]
### Description

The red build crashes to desktop while starting up on v9.9.1.443 and v9.9.1.444, the two most recent builds as of writing this. v9.9.1.442 does not seem to have this issue for me.

My ui.log ends with the following stack trace:
> IDE Exception: System.ArgumentException: Delegate to an instance method cannot have null 'this'.
   at System.MulticastDelegate.ThrowNullThisInDelegateToInstance()
   at System.MulticastDelegate.CtorClosed(Object target, IntPtr methodPtr)
   at YoYoStudio.TextEditor2.CodeEditorSettings.LoadFromPreferences()
   at YoYoStudio.GUI.Gadgets.TextEditor2.TextEditorPanel.Initialize()
   at YoYoStudio.IDE.<>c.<Initialise>b__234_18()
   at YoYoStudio.Plugins.MethodContainer.Call(Object[] _args)
   at YoYoStudio.Plugins.Command.execute_object(String _command, Object _focus, Object[] paramaters)
   at YoYoStudio.SplashScreen.SplashTick()
   at YoYoStudio.Plugins.MethodContainer.Call(Object[] _args)
   at YoYoStudio.Plugins.Command.execute_object(String _command, Object _focus, Object[] paramaters)
   at YoYoStudio.Plugins.Command.execute_object(String _command, Object _focus, Object[] paramaters)
   at YoYoStudio.IDE.Run()
   at YoYoStudio.IDE.Execute(String[] _args, Int32 _initialWidth, Int32 _initialHeight)

The full log: [ui.log](https://github.com/YoYoGames/GameMaker-Bugs/files/12872343/ui.log)

Do let me know if any other info is required.

### Expected Change

The IDE successfully loads

### Steps To Reproduce

1. Start IDE v9.9.1.443.
2. It will crash just as the splash screen disappears.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Other Release (Please put the exact version number in your Description)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by toby-yoyo** [comment]
In case it is related to this in some way - I have never used the new code editor.
