### ISSUE TITLE
Install: tvOS runtime installation can cause silent crashes, possibly due to length of file path

### ISSUE THREAD

**Issue by YYDan** [YoYoGames/GameMaker-Bugs#2077]
### Description

tvOS runtime installation during the automatic installation when updating the IDE can cause silent crashes. You see the splash screen working away as normal, but then suddenly the IDE closes:

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/15669932/c7742050-fb03-47e0-967e-d9e2b751bcfc)

Possibly due to the length of the file path, as in the crash below the file which cannot be read is:

C:\ProgramData\GameMakerStudio2-Beta\Cache\runtimes\runtime-2023.1100.0.441\ke33jx0e.4id\yyc\tvos\TemplateProject\${YYXCodeProjName}\Supporting Files\yoyo_tvos_runner_yyc.xcframework\tvos-arm64_x86_64-simulator\libyoyo_yyc_sim.a

"System.UnauthorizedAccessException: Access to the path '...'  is denied" is constant, but the exact file blamed can vary. For example, the Beta log attached below shows:
```
[09:40:36:57(b10e)] Exception installing runtime tvos - System.UnauthorizedAccessException: Access to the path 'C:\ProgramData\GameMakerStudio2-Beta\Cache\runtimes\runtime-2023.1100.0.441\ke33jx0e.4id\yyc\tvos\TemplateProject\${YYXCodeProjName}\Supporting Files\yoyo_tvos_runner_yyc.xcframework\tvos-arm64_x86_64-simulator\libyoyo_yyc_sim.a' is denied.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at YoYoStudio.Runtime.RuntimeModule.DownloadInstallAndVerify(String _location, Object _user, updateProgressBar _update)
[09:40:36:58(b10e)] Deleting Temporary Directory C:\ProgramData/GameMakerStudio2-Beta/Cache/runtimes\runtime-2023.1100.0.441\ke33jx0e.4id
[09:40:36:95(b10e)] Installing runtimes threw exception - System.AggregateException: One or more errors occurred. (One or more errors occurred. (Access to the path 'libyoyo_yyc_sim.a' is denied.))
 ---> System.AggregateException: One or more errors occurred. (Access to the path 'libyoyo_yyc_sim.a' is denied.)
 ---> System.UnauthorizedAccessException: Access to the path 'libyoyo_yyc_sim.a' is denied.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at YoYoStudio.Runtime.RuntimeModule.DownloadInstallAndVerify(String _location, Object _user, updateProgressBar _update)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at YoYoStudio.Runtime.RuntimeEntry.<>c__DisplayClass42_0.<Install>b__0()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at YoYoStudio.Runtime.RuntimeEntry.Install(String _installLocation, List`1 modulesToGet, Boolean onStartScreen, Boolean forceSelectionWindow)
   --- End of inner exception stack trace ---
```

[tvOSRuntimeInstallFail-Beta.log](https://github.com/YoYoGames/GameMaker-Bugs/files/13225715/tvOSRuntimeInstallFail-Beta.log)
[tvOSRuntimeInstallFail-Monthly.log](https://github.com/YoYoGames/GameMaker-Bugs/files/13225706/tvOSRuntimeInstallFail-Monthly.log)
[tvOSRuntimeCrash-LTS.log](https://github.com/YoYoGames/GameMaker-Bugs/files/13225707/tvOSRuntimeCrash-LTS.log)

### Expected Change

GameMaker should not crash - presumably the file should be extracted to a shorter path and then moved later?

### Steps To Reproduce

1. Start GameMaker when you know there is a new version available
2. Accept and download the new installer
3. Perform the installation
4. See the issue during the splash screen / installing runtimes phase of the new IDE starting up

### How reliably can you recreate this issue using your steps above?

Only Sometimes

### Which version of GameMaker are you reporting this issue for?

2022.0.2 (LTS), 2022.8.2, Beta (Please put the exact version number in your Description)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by caitlinrmcintyre** [comment]
It's working for Dan now, but is still crashing for me every time.
[gm crash ui log.txt](https://github.com/YoYoGames/GameMaker-Bugs/files/13270055/gm.crash.ui.log.txt)

**Comment by stuckie** [comment]
Initial fix in https://github.com/YoYoGames/YoYoStudio/commit/50d5271425ebe2ac355485e536450c032b49a523
But as above, will need to revise it

**Comment by stuckie** [comment]
Another attempt in https://github.com/YoYoGames/YoYoStudio/commit/1de37c8418cfa83f877135d562aa54ca0f7b749f

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2023.1100.0.439  Runtime v2023.1100.0.452, thanks.

**Comment by YYDan** [comment]
Fix needs to be brought to LTS, so have tagged this now.

**Comment by YYDan** [comment]
Haven't seen any issues in the multiple LTS runtimes I have installed since, and no complaints on the GMC "Early Look" thread, so Verifying in LTS.
