### ISSUE TITLE
Rollback game getting javascript exception-not starting

### ISSUE THREAD

**Issue by allende** [YoYoGames/GameMaker-Bugs#2194]
### Description
After dowloading beta 2023.1100.0.448 version the rollback game won't start.

Can't tell if it's some permission-firewall issue, but with previous version still working.

### Steps To Reproduce
Create a minimum rollback game with previous version run and test , then try same project with beta version

[8d85eb9f-300e-450b-8ba0-d23dc823c919](https://api.gamemaker.io/api/github/downloads/8d85eb9f-300e-450b-8ba0-d23dc823c919)

**Comment by rwkay** [comment]
I am unable to replicate  the issue... could you please add the Javascript console output that you are seeing?

**Comment by allende** [comment]
I keep getting the roomo is full message, then  this appears on the JS console

MessageEvent
9runner.js:306 Requesting 2-player game with game-id debug
81runner.html?game=rollbackPOC:707 0
api.gxc.gg/gg/games/debug/rooms:1     Failed to load resource: the server responded with a status of 400 ()
runner.html?game=rollbackPOC:707 Request failed with status 400, too_many_rooms_created
content_getdify.js:1 MessageEvent
api.gxc.gg/gg/games/debug/rooms:1     Failed to load resource: the server responded with a status of 400 ()
api.gxc.gg/gg/games/debug/rooms:1     Failed to load resource: the server responded with a status of 400 ()
api.gxc.gg/gg/games/debug/rooms:1     Failed to load resource: the server responded with a status of 400 ()
runner.html?game=rollbackPOC:707 0
3runner.html?game=rollbackPOC:707 Request failed with status 400, too_many_rooms_created
content_getdify.js:1 MessageEvent
content_getdify.js:1 MessageEvent
content_getdify.js:1 MessageEvent
23runner.html?game=rollbackPOC:707 0
runner.js:300 Connected successfully to relay.
3runner.html?game=rollbackPOC:707 0
2runner.js:300 Connected successfully to relay.
21runner.html?game=rollbackPOC:707 0
runner.wasm:0x31cdb Uncaught RuntimeError: memory access out of bounds
    at runner.wasm:0x31cdb
    at runner.wasm:0x170f5c
    at runner.wasm:0xa355
    at runner.wasm:0x285894
    at runner.wasm:0x28ab26
    at runner.wasm:0x31700c
    at runner.wasm:0x16c3df
    at c (runner.js:272:432)
runner.html?game=rollbackPOC:721 [post-exception status] Exception thrown, see JavaScript console
printErr @ runner.html?game=rollbackPOC:721
runner.wasm:0x1632f Uncaught RuntimeError: memory access out of bounds
    at runner.wasm:0x1632f
    at runner.wasm:0x9b668
    at runner.wasm:0x21fd6e
    at Object.Oi (runner.js:195:36)
    at HTMLCanvasElement.b (runner.js:152:47)
runner.html?game=rollbackPOC:721 [post-exception status] Exception thrown, see JavaScript console
printErr @ runner.html?game=rollbackPOC:721
runner.wasm:0x85567 Uncaught RuntimeError: memory access out of bounds
    at runner.wasm:0x85567
    at runner.wasm:0x15f002
    at runner.wasm:0x27bf08
    at Object.Oi (runner.js:194:20)
    at b (runner.js:152:47)
runner.html?game=rollbackPOC:721 [post-exception status] Exception thrown, see JavaScript console
printErr @ runner.html?game=rollbackPOC:721
runner.wasm:0x85567 Uncaught RuntimeError: memory access out of bounds
    at runner.wasm:0x85567
    at runner.wasm:0x15f002
    at runner.wasm:0x27bf08
    at Object.Oi (runner.js:194:20)
    at b (runner.js:152:47)

**Comment by rwkay** [comment]
which version of the IDE / Runtime are you building with?

**Comment by allende** [comment]
> which version of the IDE / Runtime are you building with?

I have the issue with the current BETA 2023.1100.0.435 runtime 2023.1000.0.448

**Comment by rwkay** [comment]
@YYDan can you please get someone else to try this before we release the monthly build?

**Comment by ezekiel-hls** [comment]
@allende Have you found any work-around to fix this issue?

**Comment by allende** [comment]
> @allende Have you found any work-around to fix this issue?

Hi, no I think they even disable rollback system on the monthly release, probably are working on a fix for this, the only work around would I can think about would it be to use the latest version where the issue was not present.

**Comment by ezekiel-hls** [comment]
Thanks for the reply. I will try using older monthly release version and see if I can make it work. Tried working on beta release 2023.800.x, that fixes the javascript exception but "rollback_game_running" never gets set to true

**Comment by BroDudeGuyMan** [comment]
I was going through the official multi-player tutorial, and had only done the first coding step for obj_game.  When I ran the game (target system GX.Games | GMS2 VM) I get this error as soon as the code loaded in the browser:


############################################################################################
ERROR in
action number 1
of Create Event
for object obj_game:

Variable <unknown_object>.rollabck_join_game(100005, -2147483648) not set before reading it.
 at gml_Object_obj_game_Create_0 (line 5) - if (!rollabck_join_game()) {
############################################################################################
gml_Object_obj_game_Create_0 (line 5)



I have no idea what's happening, I can't find documentation for this error anywhere.

**Comment by YYDan** [comment]
Rollback is always disabled in Monthly releases - this has always been the way and is documented in the manual as such.
