### ISSUE TITLE
Building projects: Cannot run/debug/create executables on new or just imported projects on  IDE v2023.1100.0.439  Runtime v2023.1100.0.452

### ISSUE THREAD

**Issue by alicemoretti** [YoYoGames/GameMaker-Bugs#2212]
### Description

Possibly connected to #2120  .

On  IDE v2023.1100.0.439  Runtime v2023.1100.0.452 when creating a new project or  importing a project and then trying to run the project, the run fails with the following error: 

```
Igor complete.
[Run] Run game
C:\Users\amoretti\AppData\Local\GameMakerStudio2-Beta\GMS2TEMP\Feather_ignore_bug2_3FFE9ED9_\Feather_ignore_bug2.exe 
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\Users\amoretti\AppData\Local\GameMakerStudio2-Beta\GMS2TEMP\Feather_ignore_bug2_3FFE9ED9_\Feather_ignore_bug2.exe' with working directory 'C:\Users\amoretti\AppData\Local\GameMakerStudio2-Beta\GMS2TEMP\Feather_ignore_bug2_3FFE9ED9_'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Igor.Command.ExecuteCommandSync(String _command, String _args, Boolean _fail_on_error, String _cwd, YYDictionary`2 _env, Boolean as_admin, String timingKey, Boolean _fQuiet)
   at Igor.WindowsBuilder.Run()
Igor complete.
elapsed time 00:00:04.9603221s for command "C:\ProgramData/GameMakerStudio2-Beta/Cache/runtimes\runtime-2023.1100.0.452/bin/igor/windows/x64/Igor.exe" -j=8  -options="C:\Users\amoretti\AppData\Local\GameMakerStudio2-Beta\GMS2TEMP\build.bff" -v -- Windows Run started at 11/15/2023 13:20:36
FAILED: Run Program Complete
For the details of why this build failed, please review the whole log above and also see your Compile Errors window.
```

This does not happen to projects that are opened. It also only happen to imported projects when they are imported from the File menu while another project is open.
The issue is fixed if the users relaunches the IDE or changes the target and then returns to the original target.
[run_error.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13365393/run_error.zip)

### Steps To Reproduce

1. Create a new project
2. Press Run
3. See the issue

or 

1. Open a project
2. From the File menu, import the project attached
3. Press Run
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Beta (Please put the exact version number in your Description)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Which platform(s) are you having trouble building this project for?

Windows

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by alicemoretti** [comment]
Verified fixed on Beta IDE v2023.1100.0.441 Beta Runtime v2023.1100.0.453.

Thank you
