### ISSUE TITLE
Feather doesn't work at all for some projects in 2023.1100.0.411, throws on initialization and then it's missing from IDE

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#2224]
### Description
Feather crashes on some projects init with
```
[01:50:29:521(4217)] Reason: Exception - Feather Init Exception
[01:50:29:521(4217)] ####################################
[01:50:29:521(4217)] Feather Init Exception: System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at OddlySpecific.Feather.Rule.Compiler.GmlCompiler.Visit(CallExpression expression)
   at OddlySpecific.Feather.Rule.Compiler.GmlCompiler.AcceptVarType(Expression expr, Boolean allowNarrowing)
   at OddlySpecific.Feather.Rule.Compiler.GmlCompiler.Visit(BlockExpression expression)
   at OddlySpecific.Feather.Rule.Compiler.GmlCompiler.AcceptVarType(Expression expr, Boolean allowNarrowing)
   at OddlySpecific.Feather.Rule.Compiler.GmlCompiler.Visit(IfExpression expression)
   at OddlySpecific.Feather.Rule.Compiler.GmlCompiler.AcceptVarType(Expression expr, Boolean allowNarrowing)
   at OddlySpecific.Feather.Rule.Compiler.GmlCompiler.Visit(BlockExpression expression)
   at OddlySpecific.Feather.Rule.Compiler.GmlCompiler.AcceptVarType(Expression expr, Boolean allowNarrowing)
   at OddlySpecific.Feather.Rule.Compiler.GmlCompiler.Visit(FunctionExpression expression)
   at OddlySpecific.Feather.Rule.Compiler.GmlCompiler.AcceptVar(Expression expr, Boolean allowNarrowing)
   at OddlySpecific.Feather.Rule.Compiler.GmlCompiler.Visit(CallExpression expression)
   at OddlySpecific.Feather.Rule.Compiler.GmlCompiler.AcceptVarType(Expression expr, Boolean allowNarrowing)
   at OddlySpecific.Feather.Rule.Compiler.GmlCompiler.Visit(BlockExpression expression)
   at OddlySpecific.Feather.Rule.Compiler.GmlCompiler.AcceptVarType(Expression expr, Boolean allowNarrowing)
   at OddlySpecific.Feather.Rule.Compiler.GmlCompiler.Visit(FunctionExpression expression)
   at OddlySpecific.Feather.Rule.Compiler.GmlCompiler.AcceptVarType(Expression expr, Boolean allowNarrowing)
   at OddlySpecific.Feather.Rule.Compiler.GmlCompiler.Visit(VarExpression expression)
   at OddlySpecific.Feather.Rule.Compiler.GmlCompiler.AcceptVarType(Expression expr, Boolean allowNarrowing)
   at OddlySpecific.Feather.Rule.Compiler.GmlCompiler.Visit(BlockExpression expression)
   at OddlySpecific.Feather.Rule.Compiler.GmlCompiler.AcceptVarType(Expression expr, Boolean allowNarrowing)
   at OddlySpecific.Feather.Rule.Compiler.GmlCompiler.Visit(FunctionExpression expression)
   at OddlySpecific.Feather.Rule.Compiler.GmlCompiler.AcceptVarType(Expression expr, Boolean allowNarrowing)
   at OddlySpecific.Feather.Rule.Compiler.GmlCompiler.Visit(FunctionExpression expression)
   at OddlySpecific.Feather.ResourceContext.Parse(Boolean mandatory)
   at OddlySpecific.Feather.FeatherProject.Parse(Boolean mandatory)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at OddlySpecific.Feather.FeatherProject.<>c.<FromCurrentProject>b__62_1(Task t)
   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at OddlySpecific.Feather.FeatherProject.FromCurrentProject()
   at OddlySpecific.Feather.FeatherModule.OpenFeatherProject()
   at OddlySpecific.Feather.FeatherModule.IDE_OnProjectLoaded() [IDE_OnProjectLoaded, D:\a\YoYoStudio\YoYoStudio\YoYoStudio\IDE\Plugins\Feather.Ui\FeatherPlugin.cs, 263]
```

There's also ton of `[01:51:56:994(4217)] Error performing Key lookup - 1073742086 was not found in the lookup` errors in ui.log

Beta IDE v2023.1100.0.441 Beta Runtime v2023.1100.0.453

[133fb88f-7906-4e82-9241-75a0ffb3c29a](https://api.gamemaker.io/api/github/downloads/133fb88f-7906-4e82-9241-75a0ffb3c29a)

**Comment by gnysek** [comment]
Smalles project on which it crashes for me:
[graphs.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13385783/graphs.zip)

**Comment by KormexGit** [comment]
I'm also having this same bug, here's my ui.log. It's only happening on my main large project, not on smaller test projects. I'm not getting the key lookup errors. 

[ui.log](https://github.com/YoYoGames/GameMaker-Bugs/files/13385912/ui.log)

**Comment by gnysek** [comment]
Smallest example I've found to break - but it crashes only AFTER load, not if you write/paste it into current project:
```gml
function test(_a) constructor {
	a = _a;
	
	static fff = function(_a = 1){
		return _a;
	}
}

function child_test(_a, _x, _y) : test(_a) constructor {
	xx = _x;
	yy = _y;
	
	static _fff = self.fff;
	
	static fff = function(_b){ return _fff(_b); }
}```

Seems it's connected with `static _fff = self.fff;` part, as commenting this one makes Feather to work again (after reload).

**Comment by alicemoretti** [comment]
Linking to #2091 and #2227

**Comment by zreedy** [comment]
Fixed. Faulty "can dive" conditional for base ctors in the Compiler pass (different from the Discovery pass related to the crash in #2091). "Can dive" is now flagged as a one-shot flag when diving directly into a base function.
Additionally, I had to fix an issue with how the override pattern here is handled by Feather and now you should see proper intellisense tooltips/etc. for `_connection`.
