### ISSUE TITLE
java.lang.UnsatisfiedLinkError: No implementation found for void com.yoyogames.runner.RunnerJNILib.onGamepadChange()

### ISSUE THREAD

**Issue by efeberku** [YoYoGames/GameMaker-Bugs#2359]
### Description
[RunnerActivity.onResume]
Fatal Exception: java.lang.UnsatisfiedLinkError

[RunnerActivity.onResume]

RunnerActivity.java:1134 (
This is about the gamepad issue.

	RunnerJNILib.onGamepadChange();

)
Regressed issue? RunnerActivity.java:1095 (
I solved the 1095 one by deleting this in RunnerActivity.java

	int dsMapIndex = RunnerJNILib.jCreateDsMap(null, null, null);
	RunnerJNILib.DsMapAddString(dsMapIndex, "event_type", "onResume");
	RunnerJNILib.CreateAsynEventWithDSMap(dsMapIndex, 75);//EVENT_OTHER_SYSTEM
)

Crash Log:
No implementation found for void com.yoyogames.runner.RunnerJNILib.onGamepadChange() (tried Java_com_yoyogames_runner_RunnerJNILib_onGamepadChange and Java_com_yoyogames_runner_RunnerJNILib_onGamepadChange__)

Fatal Exception: java.lang.UnsatisfiedLinkError: No implementation found for void com.yoyogames.runner.RunnerJNILib.onGamepadChange() (tried Java_com_yoyogames_runner_RunnerJNILib_onGamepadChange and Java_com_yoyogames_runner_RunnerJNILib_onGamepadChange__)
       at com.yoyogames.runner.RunnerJNILib.onGamepadChange(RunnerJNILib.java)
       at com.xxx.xxx.xxx.RunnerActivity.onResume(RunnerActivity.java:1134)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1269)
       at android.app.Activity.performResume(Activity.java:6816)
       at android.app.ActivityThread.performNewIntents(ActivityThread.java:2801)
       at android.app.ActivityThread.handleNewIntent(ActivityThread.java:2808)
       at android.app.ActivityThread.-wrap15(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1543)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6084)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

Device:
Brand:Unknown
Model:Aosp On IA Emulator
Orientation:Portrait
RAM free: 1.17 GB
Disk free: 5.54 GB
Operating System
Version:Android 7.0
Orientation:Portrait
Rooted:No

### Expected Change

RunnerActivity.java:1134 RunnerActivity.java:1095

### Steps To Reproduce

1. Sorry this happened to players not me.

### How reliably can you recreate this issue using your steps above?

Rarely

### Which version of GameMaker are you reporting this issue for?

2023.8.2 (Monthly)

### Which platform(s) are you seeing the problem on?

Android

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by efeberku** [comment]
> Hi, @efeberku this looks like somebody is running on an emulator from Android Studio (Aosp On IA Emulator) just a thought but do you ship an x86_64 Architecture for your game?

No, I don't.

**Comment by YYDan** [comment]
Nothing for us to verify.
