### ISSUE TITLE
java.lang.IllegalArgumentException No EGL configs match our minimum required spec

### ISSUE THREAD

**Issue by efeberku** [YoYoGames/GameMaker-Bugs#2366]
### Description

Fatal Exception: java.lang.IllegalArgumentException
No EGL configs match our minimum required spec

Fatal Exception: java.lang.IllegalArgumentException: No EGL configs match our minimum required spec
       at com.efeberkucar.metroidvania.adventurerlife.DemoGLSurfaceView.chooseConfig(DemoGLSurfaceView.java:85)
       at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1054)
       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1431)
       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)

Device
Brand:Xiaomi
Model:MI CC9 Pro Premium Edition
Orientation:Landscape
RAM free: 2.32 GB
Disk free: 33.45 GB
Operating System
Version:Android 11
Orientation:Landscape
Rooted:No

### Expected Change

DemoGLSurfaceView.chooseConfig(DemoGLSurfaceView.java:85)

### Steps To Reproduce

1. Sorry this happened to a player

### How reliably can you recreate this issue using your steps above?

Only Ever Happened Once

### Which version of GameMaker are you reporting this issue for?

2023.8.2 (Monthly)

### Which platform(s) are you seeing the problem on?

Android

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by JonnoRobson** [comment]
Has this issue only been reported on the Xiaomi MI CC9 Pro Premium Edition device or are there other Android devices which you are aware of the issue occurring on? Also are you aware if the issue is consistently reproducible on the device? The Xiaomi device specified should be able to support the minimum OpenGL spec we are requesting so I'm not sure why it is failing to find a valid configuration.

**Comment by efeberku** [comment]
Yes, it's only been reported on the MI CC9 Pro but the player base of the game is really low. I included everything I can see in the crash log.
