### ISSUE TITLE
Faulting module name: coreclr.dll, version: 6.0.2223.42425 .NET Version: 6.0.22

### ISSUE THREAD

**Issue by LV-6502** [YoYoGames/GameMaker-Bugs#2394]
### Description
[ui.log.txt](https://github.com/YoYoGames/GameMaker-Bugs/files/13600541/ui.log.txt)
System Info:
OSPLATFORM_TYPE:  x64
OSNAME:  Windows 10
IDE v2022.0.2.51
Runtime v2022.0.2.49

This is an intermittent fatal crash, sometimes it happens coming out of sleep other times I'd be browsing the net with GMS2 open in the background and all of a sudden it crashes - I cannot recreate it although it occurs almost hourly.

Notable Event Viewer items:
```
Application: GameMaker-LTS.exe CoreCLR Version: 6.0.2223.42425 .NET Version: 6.0.22
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: A callback was made on a garbage collected delegate of type 'SDL2-CS!SDL2.SDL+SDL_AudioCallback::Invoke'. Stack:
```

```
Application: GameMaker-LTS.exe CoreCLR Version: 6.0.2223.42425 .NET Version: 6.0.22
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
```

```
Faulting application name: Runner.exe, version: 2022.0.2.49, time stamp: 0x652678d6
Faulting module name: Runner.exe, version: 2022.0.2.49, time stamp: 0x652678d6
Exception code: 0xc0000005
Fault offset: 0x00000000001d8199
Faulting process id: 0x1610
```

```
Faulting application name: GameMaker-LTS.exe, version: 2022.0.2.51, time stamp: 0x64e81669
Faulting module name: coreclr.dll, version: 6.0.2223.42425, time stamp: 0x64e8109c
Exception code: 0x80131623
Fault offset: 0x000000000025c9a6
Faulting process id: 0x16e0
Faulting application start time: 0x01da2842757791b0
Faulting application path: C:\Program Files\GameMaker-LTS\GameMaker-LTS.exe
Faulting module path: C:\Program Files\GameMaker-LTS\coreclr.dll
Report Id: 290cd171-efb4-43b6-ab89-4a42f9037751
Faulting package full name:
Faulting package-relative application ID:
```
```
*******************************************************************************
*                                                                             *
*                        Exception Analysis                                   *
*                                                                             *
*******************************************************************************


KEY_VALUES_STRING: 1

    Key  : Analysis.CPU.mSec
    Value: 5639

    Key  : Analysis.Elapsed.mSec
    Value: 8583

    Key  : Analysis.IO.Other.Mb
    Value: 31

    Key  : Analysis.IO.Read.Mb
    Value: 1

    Key  : Analysis.IO.Write.Mb
    Value: 137

    Key  : Analysis.Init.CPU.mSec
    Value: 15796

    Key  : Analysis.Init.Elapsed.mSec
    Value: 1018810

    Key  : Analysis.Memory.CommitPeak.Mb
    Value: 445

    Key  : CLR.Engine
    Value: CORECLR

    Key  : CLR.Version
    Value: 6.0.2223.42425

    Key  : Failure.Bucket
    Value: BREAKPOINT_80000003_coreclr.dll!Thread::UserSleep

    Key  : Failure.Hash
    Value: {34490a04-0f98-befe-ed18-d6ff8d577a28}

    Key  : Timeline.Process.Start.DeltaSec
    Value: 64801

    Key  : WER.OS.Branch
    Value: vb_release

    Key  : WER.OS.Version
    Value: 10.0.19041.1

    Key  : WER.Process.Version
    Value: 2022.0.2.51


FILE_IN_CAB:  gmdump.6512.dmp

APPLICATION_VERIFIER_FLAGS:  0

EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 0000000000000000
   ExceptionCode: 80000003 (Break instruction exception)
  ExceptionFlags: 00000000
NumberParameters: 0

FAULTING_THREAD:  000067c4

PROCESS_NAME:  GameMaker-LTS.exe

ERROR_CODE: (NTSTATUS) 0x80000003 - {EXCEPTION}  Breakpoint  A breakpoint has been reached.

EXCEPTION_CODE_STR:  80000003

STACK_TEXT:  
00000019`f337e0a8 00007ffa`5483b62e     : 00000019`f337e168 00000000`00000000 00000000`0000ffff 00000000`00000001 : ntdll!NtDelayExecution+0x14
00000019`f337e0b0 00007ff9`f8f555f2     : ffffffff`ffffffff 00007ff9`00000001 00007ff9`c00000bb 00000000`00000000 : KERNELBASE!SleepEx+0x9e
00000019`f337e150 00007ff9`f8f554eb     : 06000000`00000001 00007ff9`f8f55450 04000000`00000001 00000000`00000013 : coreclr!Thread::UserSleep+0xb2
00000019`f337e1a0 00007ff9`9a31d395     : 40220000`00000000 88dbf4bc`58cd8c0f 00000000`00000064 00000000`0000006f : coreclr!ThreadNative::Sleep+0x9b
00000019`f337e2f0 40220000`00000000     : 88dbf4bc`58cd8c0f 00000000`00000064 00000000`0000006f 88dbf4bc`58cd8c0f : 0x00007ff9`9a31d395
00000019`f337e2f8 88dbf4bc`58cd8c0f     : 00000000`00000064 00000000`0000006f 88dbf4bc`58cd8c0f 00000000`00000000 : 0x40220000`00000000
00000019`f337e300 00000000`00000064     : 00000000`0000006f 88dbf4bc`58cd8c0f 00000000`00000000 00000000`0000006f : 0x88dbf4bc`58cd8c0f
00000019`f337e308 00000000`0000006f     : 88dbf4bc`58cd8c0f 00000000`00000000 00000000`0000006f 00007ff9`9a3cf290 : 0x64
00000019`f337e310 88dbf4bc`58cd8c0f     : 00000000`00000000 00000000`0000006f 00007ff9`9a3cf290 00000000`00000000 : 0x6f
00000019`f337e318 00000000`00000000     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : 0x88dbf4bc`58cd8c0f


STACK_COMMAND:  ~0s; .ecxr ; kb

FAULTING_SOURCE_LINE:  D:\a\_work\1\s\src\coreclr\vm\threads.cpp

FAULTING_SOURCE_FILE:  D:\a\_work\1\s\src\coreclr\vm\threads.cpp

FAULTING_SOURCE_LINE_NUMBER:  4264

FAULTING_SOURCE_CODE:  
No source found for 'D:\a\_work\1\s\src\coreclr\vm\threads.cpp'


SYMBOL_NAME:  coreclr!Thread::UserSleep+b2

MODULE_NAME: coreclr

IMAGE_NAME:  coreclr.dll

FAILURE_BUCKET_ID:  BREAKPOINT_80000003_coreclr.dll!Thread::UserSleep

OS_VERSION:  10.0.19041.1

BUILDLAB_STR:  vb_release

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

IMAGE_VERSION:  6.0.2223.42425

FAILURE_ID_HASH:  {34490a04-0f98-befe-ed18-d6ff8d577a28}

Followup:     MachineOwner
```

Other errors from the UI Log:
```
[17:13:44:382(1a77)] InternalCheckForInternetConnection :: Unable to reach site https://www.yoyogames.com
[17:13:44:383(1a77)] System.AggregateException: One or more errors occurred. (A task was canceled.)
---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.Task.GetExceptions(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at YoYoStudio.Core.Utils.HttpUtil.<>c__DisplayClass47_0.<InternalCheckForInternetConnection>b__1(String s, ParallelLoopState _state)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
--- End of stack trace from previous location ---

   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at YoYoStudio.Core.Utils.HttpUtil.<>c__DisplayClass47_0.<InternalCheckForInternetConnection>b__1(String s, ParallelLoopState _state)
[17:13:44:383(1a77)] Inner exception:
```

### Expected Change

Hopefully to resolve the issue as I cannot use GMS2 anymore due to frequent crashing

### Steps To Reproduce

I have not yet found a way to reproduce this error.

### How reliably can you recreate this issue using your steps above?

Rarely

### Which version of GameMaker are you reporting this issue for?

Other Release (Please put the exact version number in your Description)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by LV-6502** [comment]
UI Logs attached
[ui.log.txt](https://github.com/YoYoGames/GameMaker-Bugs/files/13600423/ui.log.txt)

**Comment by LV-6502** [comment]
Sadly happened again, crashed with the CMD window saying it was creating a minidump (however none exist under the specified path).

Checking the UI logs I see the following:
```
[19:56:58:633(cc4b)] Audio Device Disconnected: C49RG9x (NVIDIA High Definition Audio)
[19:56:58:657(beaa)] Audio Device Disconnected: C49RG9x (NVIDIA High Definition Audio)
[19:56:58:769(beaa)] Audio Device Disconnected: C49RG9x (NVIDIA High Definition Audio)
[19:56:58:795(cc4b)] Audio Device Disconnected: C49RG9x (NVIDIA High Definition Audio)
[19:58:17:30(beaa)] --------------------------------------------------------------------------------
[19:58:17:31(beaa)] Unhandled Exception: System.NullReferenceException
[19:58:17:31(beaa)] Exception message: Object reference not set to an instance of an object.
[19:58:17:31(beaa)] Exception stack: 
[19:58:17:31(beaa)] --------------------------------------------------------------------------------
[19:58:17:46(beaa)] ####################################
[19:58:17:46(beaa)] Assert in AddWindow (WindowManager:2232)
[19:58:17:46(beaa)] Reason: You can't manipulate UI on a background thread
[19:58:17:46(beaa)] ####################################
```
Which again lines up with this event in the Event Viewr:

```
Application: GameMaker-LTS.exe
CoreCLR Version: 6.0.2223.42425
.NET Version: 6.0.22
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
```

Potentially a sound driver issue?

**Comment by stuckie** [comment]
I've put in a potential fix... the audio system in newer IDEs has been completely rewritten, and I assume this doesn't happen in newer IDEs?

It does look like we're getting hiccuped with a sound device change, so I've put an additional two guards in place that may have been falling over, but I'm honestly not sure as I can't reproduce it myself.

**Comment by stuckie** [comment]
I've put in a potential fix... the audio system in newer IDEs has been completely rewritten, and I assume this doesn't happen in newer IDEs?

It does look like we're getting hiccuped with a sound device change, so I've put an additional two guards in place that may have been falling over, but I'm honestly not sure as I can't reproduce it myself.

**Comment by YYDan** [comment]
@LV-6502 Any chance you have tried the 2022.0.3 Early Look release yet? Any problems with this still happening on your machine, or does everything seem fixed now?

https://forum.gamemaker.io/index.php?threads/2022-0-3-lts-early-look-thread.115055/

**Comment by LV-6502** [comment]
Hi Daniel, sincere apologies on the delay. I'm currently on IDE: v2022.0.3.83 | Runtime: v2022.0.3.98.
I've had no issues until I started working with audio files again and the IDE has started to crash in the same fashion.

Looking at the Windows Event Viewer I can see:
```
Application: GameMaker-LTS.exe
CoreCLR Version: 6.0.3524.45918
.NET Version: 6.0.35
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: A callback was made on a garbage collected delegate of type 'SDL2-CS!SDL2.SDL+SDL_AudioCallback::Invoke'.
Stack:
```
```
Faulting application name: GameMaker-LTS.exe, version: 2022.0.3.83, time stamp: 0x66df0000
Faulting module name: coreclr.dll, version: 6.0.3524.45918, time stamp: 0x66dfe3a5
Exception code: 0x80131623
Fault offset: 0x000000000025cb46
Faulting process id: 0x11dc
Faulting application start time: 0x01db44bdaed99c78
Faulting application path: C:\Program Files\GameMaker-LTS\GameMaker-LTS.exe
Faulting module path: C:\Program Files\GameMaker-LTS\coreclr.dll
Report Id: f5d85920-0a5b-4e23-a340-511b741367f3
Faulting package full name: 
Faulting package-relative application ID: 
```

Which are the same failures as before.

The minidump had no exceptions nor heap information.

**Comment by LV-6502** [comment]
> [@LV-6502](https://github.com/LV-6502) Any chance you have tried the 2022.0.3 Early Look release yet? Any problems with this still happening on your machine, or does everything seem fixed now?
> 
> https://forum.gamemaker.io/index.php?threads/2022-0-3-lts-early-look-thread.115055/

Hi Daniel, sincere apologies on the delay. I'm currently on IDE: v2022.0.3.83 | Runtime: v2022.0.3.98.
I've had no issues until I started working with audio files again and the IDE has started to crash in the same fashion.

Looking at the Windows Event Viewer I can see:
```
Application: GameMaker-LTS.exe
CoreCLR Version: 6.0.3524.45918
.NET Version: 6.0.35
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: A callback was made on a garbage collected delegate of type 'SDL2-CS!SDL2.SDL+SDL_AudioCallback::Invoke'.
Stack:
```
```
Faulting application name: GameMaker-LTS.exe, version: 2022.0.3.83, time stamp: 0x66df0000
Faulting module name: coreclr.dll, version: 6.0.3524.45918, time stamp: 0x66dfe3a5
Exception code: 0x80131623
Fault offset: 0x000000000025cb46
Faulting process id: 0x11dc
Faulting application start time: 0x01db44bdaed99c78
Faulting application path: C:\Program Files\GameMaker-LTS\GameMaker-LTS.exe
Faulting module path: C:\Program Files\GameMaker-LTS\coreclr.dll
Report Id: f5d85920-0a5b-4e23-a340-511b741367f3
Faulting package full name: 
Faulting package-relative application ID: 
```

Which are the same failures as before.

The minidump had no exceptions nor heap information.
