### ISSUE TITLE
Device Manager: [Win IDE] Cannot detect iOS devices after updating the target Mac to macOS Sonoma, "No such host is known"

### ISSUE THREAD

**Issue by j4m1ef0rd** [YoYoGames/GameMaker-Bugs#2404]
### Description

Gamemaker: 2023.11.0.121
Runtime: 2023.11.0.157

On windows I was able to connect to the Mac but not find any iOS device, even with xcode open and the device on the list. It was working before but recently updated to Sonoma.

If I use `Jamies-MacBook-Pro.local` as my host name on the mac, I can test the connection fine, but when trying to find iOS devices i get the ` No such host is known.` error. To solve this i just changed my host name to `JamiesM1.local` and it was able to find the iOS device.
I can reliably get the error again by just changing my host name back to `Jamies-MacBook-Pro.local`. But strangely it still finds the iOS device now.

```sh
"C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2023.11.0.157/bin/igor/windows/x64/Igor.exe"  -password="redacted" -username="redacted" -hostname="Jamies-MacBook-Pro.local" -- Test Test

elapsed time 00:00:01.8065547s for command "C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2023.11.0.157/bin/igor/windows/x64/Igor.exe" -password="redacted" -username="redacted" -hostname="Jamies-MacBook-Pro.local" -- Test Test started at 12/08/2023 12:30:58
Connection successful!
"C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2023.11.0.157/bin/igor/windows/x64/Igor.exe"  -of="C:\Users\JAmie\AppData\Local\GameMakerStudio2\GMS2TEMP\devices.json" -d="Jamies-MacBook-Pro.local" -uf="C:\Users\JAmie\AppData\Roaming/GameMakerStudio2\j4m1ef0rd_1301" -rp="C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2023.11.0.157" -- ios DetectDevices

Options: C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2023.11.0.157\bin\platform_setting_defaults.json
Options: C:\Users\JAmie\AppData\Roaming/GameMakerStudio2\j4m1ef0rd_1301\local_settings.json
Release build
WARNING: Unable to connect to remote client: No such host is known.
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Mismatched call to Igor.RealSSH.ClientReleaseConnection()
   at Igor.RealSSH.ClientReleaseConnection()
   at Igor.RealSSH.plink(String command, Boolean fail_on_error)
   at Igor.RealSSH.CacheKey(String _host, String _user, String _pass)
   at Igor.SSH.SetupPPK(String _hostname, String _username, String _password)
   at Igor.RealSSH.Connect(String _username, String _hostname, String _password)
   at Igor.iOSBuilder..ctor()
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   --- End of inner exception stack trace ---
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type)
   at Igor.Program.GetBuilder()
   at Igor.Program.Main(String[] args)
[createdump] Writing minidump to file C:\ProgramData\GameMakerStudio2\Dumps\gmdump.22040.dmp
[createdump] Dump successfully written
Igor complete.
elapsed time 00:00:02.1281844s for command "C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2023.11.0.157/bin/igor/windows/x64/Igor.exe" -of="C:\Users\JAmie\AppData\Local\GameMakerStudio2\GMS2TEMP\devices.json" -d="Jamies-MacBook-Pro.local" -uf="C:\Users\JAmie\AppData\Roaming/GameMakerStudio2\j4m1ef0rd_1301" -rp="C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2023.11.0.157" -- ios DetectDevices started at 12/08/2023 12:31:00
"C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2023.11.0.157/bin/igor/windows/x64/Igor.exe"  -of="C:\Users\JAmie\AppData\Local\GameMakerStudio2\GMS2TEMP\simulators.json" -d="Jamies-MacBook-Pro.local" -uf="C:\Users\JAmie\AppData\Roaming/GameMakerStudio2\j4m1ef0rd_1301" -rp="C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2023.11.0.157" -- ios DetectSimulators

Options: C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2023.11.0.157\bin\platform_setting_defaults.json
Options: C:\Users\JAmie\AppData\Roaming/GameMakerStudio2\j4m1ef0rd_1301\local_settings.json
Release build
mkdir -p ~/.ssh
WARNING: Unable to connect to remote client: No such host is known.
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Mismatched call to Igor.RealSSH.ClientReleaseConnection()
   at Igor.RealSSH.ClientReleaseConnection()
   at Igor.RealSSH.plink_get_output(String command, StringBuilder result, Boolean fail_on_error)
   at Igor.SSH.SetupPPK(String _hostname, String _username, String _password)
   at Igor.RealSSH.Connect(String _username, String _hostname, String _password)
   at Igor.iOSBuilder..ctor()
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   --- End of inner exception stack trace ---
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type)
   at Igor.Program.GetBuilder()
   at Igor.Program.Main(String[] args)
[createdump] Writing minidump to file C:\ProgramData\GameMakerStudio2\Dumps\gmdump.28408.dmp
[createdump] Dump successfully written
Igor complete.
elapsed time 00:00:03.6716675s for command "C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2023.11.0.157/bin/igor/windows/x64/Igor.exe" -of="C:\Users\JAmie\AppData\Local\GameMakerStudio2\GMS2TEMP\simulators.json" -d="Jamies-MacBook-Pro.local" -uf="C:\Users\JAmie\AppData\Roaming/GameMakerStudio2\j4m1ef0rd_1301" -rp="C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2023.11.0.157" -- ios DetectSimulators started at 12/08/2023 12:31:02

```

[contact us package](https://github.com/YoYoGames/GameMaker-Bugs/files/13608032/yoyobugios.zip)

### Steps To Reproduce

1. Change Mac hostname to `Jamies-MacBook-Pro.local`
2. In windows gamemaker, connect to the mac
3. on windows gamemaker, Try and find iOS devices with `Jamies-MacBook-Pro.local`
4. Get the error in the output

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Other Release (Please put the exact version number in your Description)

### Which operating system(s) are you seeing the problem on?

Windows 10, macOS Sonoma

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by stuckie** [comment]
The issues seems to be that the hostname has a space or apostrophe. If the hostname is renamed to remove this, it should be fine.
Alternatively, use the IP address instead.
It seems to be an issue on Sonoma.

**Comment by j4m1ef0rd** [comment]
> The issues seems to be that the hostname has a space or apostrophe.

But the hostname did not have any bad characters. Also this hostname was working before the Sonoma update. 

> It seems to be an issue on Sonoma

So nothing you can do? Should we close this issue?

**Comment by jackerley** [comment]
@gurpreetsinghmatharoo  I've tried a number of workarounds for this but can't find a way to avoid it. Could you add a note to the setup guide?

**Comment by gurpreetsinghmatharoo** [comment]
Added note on https://help.gamemaker.io/hc/en-us/articles/235186128

**Comment by Emc1923** [comment]
Verified note added to the set up articles - adding IP as hostname works fine too, closing.
