### ISSUE TITLE
2023.11+ IDEs corrupt most of my extensions on import

### ISSUE THREAD

**Issue by YellowAfterlife** [YoYoGames/GameMaker-Bugs#2649]
### Description

Starting with the 2023.11 release (tested on IDE v2023.11.1.129  Runtime v2023.11.1.160), the IDE for some reason strips the filenames from most of my extensions when imported, producing this kind of sight

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/731492/ae9060d9-8652-44a2-9065-192e307ac2c5)

And a cryptic error upon trying to compile the project
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at GMAssetCompiler.WADSaver`1.WriteExtensions(IList`1 _data, Stream _s, IFF _iff)
   at GMAssetCompiler.IFFChunkHandler`1.Save(Stream _stream, IFF _iff)
   at GMAssetCompiler.IFF.WriteChunks(Stream _stream, TextWriter _out)
   at GMAssetCompiler.WADSaver`1.Save(GMAssets _assets, Stream _stream, List`1 _extraFilenames, Dictionary`2 _extraAttributes)
   at GMAssetCompiler.IFFSaver.Save(GMAssets _assets, String _name)
   at GMAssetCompiler.Program.CompileProject(GMAssets _file)
   at GMAssetCompiler.Program.Reentry(String[] _args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Igor.Program.ExecuteAssetCompiler(String _args)
   at Igor.WindowsBuilder.Compile(Boolean _exe)
   at Igor.WindowsBuilder.Deploy(Boolean _exe)
   at Igor.WindowsBuilder.Run()
```

["Contact us" package](https://github.com/YoYoGames/GameMaker-Bugs/files/13842427/ext-contact-us.zip)

As far as I can tell, the only workarounds for the end user are:
1. Re-enter the filenames by hand
2. Downgrade the IDE+runtime to 2023.8 and re-import the extension(s)

### Steps To Reproduce

1. Start GameMaker
2. Open a project
3. Import the extension from [file_dropper-for-GMS2.3+.yymps.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13842379/file_dropper-for-GMS2.3%2B.yymps.zip)
4. Double-click on the extension in the resource tree
5. Note the file list

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by caitlinrmcintyre** [comment]
Verified fix in IDE v2024.200.0.461  Runtime v2024.200.0.477, thanks.
