### ISSUE TITLE
Room Editor: Allow customising/overiding the sprite asset assigned to an instance

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#3733]
### Description

When double-clicking an instance within the room editor, you currently have the ability to change which object is assigned to this instance. However, it would be great to have an option on this window to customise the sprite assigned to the instance (which could override the one already assigned to the object). This means you could see the various instances of the same object placed in a room, with the sprites you've set them, which would then set their sprite_indexes upon game start.

### Justification

This would be particularly helpful as there may be times where a person needs to be able to use lots of the same object in order to achieve something like a drawing, or depth-sorting system. Something streamlined where a job is performed by lots of instances of the same object. This can however become problematic when hand-placing objects into the room editor and needing to be able to precisely place them to construct the room. Currently the only way to 'see' a sprite in the room editor is to assign it to a unique object (or place it on as asset layer). As a result, to be able to place lots of sprites down (that are all handled by the aforementioned system), they all need to have their own object, then parented to a controller object of sorts. In some cases I have had to make thousands of extra objects for this. It ends up being a lot of bloat on the project and is very time-consuming to set up.

### Benefit

If I was able to make a single object responsible for handling scenery, then simply change which sprite is assigned to each instance (with this being visible in the room editor), this would save a huge amount of time, and would open up the opportunity for better instance customisation whilst in the room editor.

**Comment by ThomazDiniz** [comment]
To anyone here interested in a workaround, I made one that I found to be quite nice today:

Create an asset layer and add your sprites as if they were objects. At the start of the room, use a function like this:
`
var _all_elements = layer_get_all_elements("sprites");
for (var _i = 0; _i < array_length(_all_elements); _i++;){
    if (layer_get_element_type(_all_elements[_i]) == layerelementtype_sprite) {
        var _spr_layer	= _all_elements[_i];
		var _spr		= layer_sprite_get_sprite(_spr_layer);
		var _img		= layer_sprite_get_alpha(_spr_layer);
		var _x			= layer_sprite_get_x(_spr_layer);
		var _y			= layer_sprite_get_y(_spr_layer);
		var _ang		= layer_sprite_get_angle(_spr_layer);
		var _blend		= layer_sprite_get_blend(_spr_layer);
		var _xs			= layer_sprite_get_xscale(_spr_layer);
		var _ys			= layer_sprite_get_yscale(_spr_layer);
		var _alpha		= layer_sprite_get_alpha(_spr_layer);
		
		
		instance_create_layer(_x,_y,layer,obj_map_interactable, 
		{	
			sprite_index: _spr,
			image_index: _img,
			image_xscale: _xs,
			image_yscale: _ys,
			image_angle: _ang,
			image_blend: _blend,
			image_alpha: _alpha
		});
		
		layer_sprite_destroy(_spr_layer);
    }
}`

This code deletes all sprites from the asset layer, and recreates them as a specific instance. It's not perfect, but it works when you want to do fast level design.

**Comment by ThomazDiniz** [comment]
Btw, FYI this is the same issue as #2654

**Comment by mmMarzban** [comment]
Please!

**Comment by gnysek** [comment]
There are at least two duplicates of this feature: #3442 & #3765 .

**Comment by stuckie** [comment]
Second part is now in.
This updates and manages the Object Properties ( also changed the name to Sprite Override to avoid confusion ) and now it can be closed.

![Image](https://github.com/user-attachments/assets/52809170-49fa-4c9f-91b4-ab9899052ebc)

**Comment by mgeddesGM** [comment]
the following issues were found in  IDE v2024.1400.0.830  Runtime v2024.1400.0.826

1. if an object is added to a room, the sprite override frame is "-2147483648"
2. if an override sprite is set then when ran the following error is seen
```
Found Project Format 2
Cannot load project because linking failed with the following errors:
C:/Users/mgeddes/Documents/GameMakerStudio2/BLANK GAME_1/rooms/Room1/Room1.yy(15,209): Cannot resolve link 'rooms/Room1/Room1.yy : image_index' in user's project.
C:/Users/mgeddes/Documents/GameMakerStudio2/BLANK GAME_1/rooms/Room1/Room1.yy(16,210): Cannot resolve link 'rooms/Room1/Room1.yy : sprite_index' in user's project.

Failed: Cannot load project because linking failed with the following errors:
C:/Users/mgeddes/Documents/GameMakerStudio2/BLANK GAME_1/rooms/Room1/Room1.yy(15,209): Cannot resolve link 'rooms/Room1/Room1.yy : image_index' in user's project.
C:/Users/mgeddes/Documents/GameMakerStudio2/BLANK GAME_1/rooms/Room1/Room1.yy(16,210): Cannot resolve link 'rooms/Room1/Room1.yy : sprite_index' in user's project.

Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at GMAssetCompiler.Loader.LoadGMS2CreateAssets(String _filename)
   at GMAssetCompiler.Loader.Load(String _name)
   at GMAssetCompiler.Program.GetAssetsFile(List`1 _args)
   at GMAssetCompiler.Program.Main(String[] _args)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Igor.Program.ExecuteAssetCompiler(String _args)
   at Igor.Program.SetupBuildEnv(String _options, String _project, String _runtimeLocation, String _cache, String _temp, String _user, String _outputFilename, String _targetFilename, String _debuggerPort, Boolean _launchPackage)
   at Igor.Program.Main(String[] args)
Igor complete.
elapsed time 00:00:03.5870716s for command "C:\ProgramData/GameMakerStudio2-Beta/Cache/runtimes\runtime-2024.1400.0.826/bin/igor/windows/x64/Igor.exe" -j=8  -options="C:\Users\mgeddes\AppData\Local\GameMakerStudio2-Beta\GMS2TEMP\build.bff" -v -- Windows Run started at 06/18/2025 11:13:13, exited with -532462766
FAILED: Run Program Complete
For the details of why this build failed, please review the whole log above and also see your Compile Errors window.

```
3. if this project is closed then reopened then the user will be stopped by this error message

![Image](https://github.com/user-attachments/assets/5342d365-329c-4b87-975c-2c92cda05f1c)

![Image](https://github.com/user-attachments/assets/a6b76e2b-d4d7-4730-82f6-a166b10203ec)
https://api.gamemaker.io/api/github/downloads/3669f78c-3b14-4d3e-90bb-b3142b42011e

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.1400.0.831  Runtime v2024.1400.0.827
