### ISSUE TITLE
Sequence Editor: Fatal Error message when adding parameter tracks to an audio track

### ISSUE THREAD

**Issue by caitlinrmcintyre** [YoYoGames/GameMaker-Bugs#4313]
### Description

When in the Sequence Editor and clicking "Add Parameter Track" on an audio track, as soon as you add any you get a fatal error message.

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/131007845/e3a2e55a-fa02-41b0-8d83-e81219ff908e)

ui log shows:
```
[12:08:19:855(de4d)] DoUndoableAction: 'Add parameter'
[12:08:19:922(de4d)] Fatal Error! 'UndoManager::DoUndoableAction - Override getDopeSheetHierarchyGadget, cannot edit GMBaseTrack'
[12:08:19:924(de4d)]    at YoYoStudio.Resources.GMTrackAdapter.getSequenceDopeSheetHierarchyItem(SequenceDopeSheet _dopesheet, SequenceTrackModel _track)
   at YoYoStudio.GUI.Gadgets.Sequences.SequenceTrackModel.CreateHierarchyGadget()
   at YoYoStudio.GUI.Gadgets.Sequences.Dope_Sheet.DopeSheetHierarchyPanel.CreateHierarchyItem(IDopeSheetModel _node)
   at YoYoStudio.GUI.Gadgets.Sequences.SequenceDopeSheetHierarchy.CreateTreeViewNode(IDopeSheetModel _node, TreeViewNode _parent, Int32 _index)
   at YoYoStudio.GUI.Gadgets.Sequences.Dope_Sheet.DopeSheetHierarchyPanel.AddChildNodes(IDopeSheetModel _node, TreeViewNode _parent, Int32 _index)
   at YoYoStudio.GUI.Gadgets.Sequences.Dope_Sheet.DopeSheetHierarchyPanel.AddChildNodes(IDopeSheetModel _node, TreeViewNode _parent, Int32 _index)
   at YoYoStudio.GUI.Gadgets.Sequences.Dope_Sheet.DopeSheetHierarchyPanel.Rebuild(IDopeSheetModel _root)
   at YoYoStudio.GUI.Gadgets.Sequences.Dope_Sheet.DopeSheetHierarchyPanel.set_Items(IList`1 value)
   at YoYoStudio.GUI.Gadgets.Sequences.Dope_Sheet.DopeSheet.set_Items(IList`1 value)
   at YoYoStudio.GUI.Gadgets.Sequences.SequenceDopeSheet.UpdateTracks(GMSequence sequence)
   at YoYoStudio.GUI.Gadgets.Sequences.SequenceDopeSheet.OnBoundObjectChanged(Object _sender, String _propertyName)
   at YoYoStudio.Resources.Changeable.ThrowChangeIn(Dictionary`2 _events, String _property, Object _object) in D:\a\YoYoStudio\YoYoStudio\YoYoStudio\IDE\Core\CoreResources\CoreResources\Interfaces\IChangeable.cs:line 207
   at YoYoStudio.Resources.ResourceBase.Throw_Change(String _property, Object _object, Boolean _setDirty) in D:\a\YoYoStudio\YoYoStudio\YoYoStudio\IDE\Core\CoreResources\CoreResources\ResourceBase.cs:line 1440
   at YoYoStudio.GUI.Gadgets.Sequences.SequenceDopeSheetHierarchy.<>c__DisplayClass23_2.<AddParametersToContextMenu>b__1()
   at YoYoStudio.Core.Utils.UndoManager.DoUndoableAction(String _description, Object _objectsToTrack, Action _actionDelegate, Object _contextOverride)
[12:08:19:926(de4d)] ####################################
[12:08:19:927(de4d)] Break in FatalErrorWarning (IDE:4513)
[12:08:19:929(de4d)] ####################################
[12:08:36:587(de4d)] MQTT - Received msg: GameMaker/event/open_browser/url = C:\ProgramData\GameMakerStudio2-Beta
```

IDE v2024.200.0.461  Runtime v2024.200.0.477 /  IDE v2023.11.1.129  Runtime v2023.11.1.160

[parameter_fatalerror.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/13904164/parameter_fatalerror.zip)

### Expected Change

There should be no fatal error message when adding parameter tracks

### Steps To Reproduce

1. Start GameMaker and import project.
2. Click on Sequences and on the "snd_1" track in the editor, press the + button to add parameter track and choose any.
3. See fatal error message.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.1100 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by yyalansavage** [comment]
This is the result of loading a project made in sequence audio effect parameters feature build, into a beta version which does not have the new audio parameter sequence tracks (yet)

**Comment by YYDan** [comment]
Will keep this one on Caitlin and confirm all is well whenever we do get that feature added. Ta!

**Comment by stuckie** [comment]
Fixed as part of https://github.com/YoYoGames/CoreResources/pull/185

**Comment by Emc1923** [comment]
Closing this issue as parameter tracks are correctly added and applied now after the merge, even in the project attached - Verified as of  IDE v2024.200.0.476  Runtime v2024.200.0.491
