### ISSUE TITLE
Igor not setting variables when running extension/steamworks scripts

### ISSUE THREAD

**Issue by OmegaMetor** [YoYoGames/GameMaker-Bugs#4339]
### Description

(I know it specifically says "building your projects inside the GameMaker IDE", but I don't know which type would be better)

Currently, on Ubuntu 22.04, when running igor with the command:
`./Igor /rp ../../../../ /lf ~/Gamemaker/licence.plist /cache ~/Gamemaker/cache /temp ~/Gamemaker/temp /project ~/Game/Game.yyp /of ~/Gamemaker/out /tf Game.appimage linux Package`

It gets through most of the build, but eventually fails with the following errors:
```
#################################### INFORMATION ####################################
Steam Extension is not available in this target: Linux (no setup required)
#####################################################################################








Copying Linux (64 bit) dependencies
Archive is current

#################################### INFORMATION ####################################
Steam Extension is not available in this target: Linux (no setup required)
#####################################################################################



System.IO.FileNotFoundException: Could not find file '/home/ubuntu/Gamemaker/out.zip'.
File name: '/home/ubuntu/Gamemaker/out.zip'
   at System.IO.File.Move(String sourceFileName, String destFileName, Boolean overwrite)
   at System.IO.File.Move(String sourceFileName, String destFileName)
   at Igor.LinuxBuilder.Package()
Igor complete.
```
After looking through the post_build_step.sh from the steamworks extension, where the error occurs, i found that the YYprojectName variable is unset, causing the script to fail. In ide on windows this works fine, though I haven't tested calling igor on windows.

I did not include a contact us package due to there not being any way to generate it that I am aware of. If there is a way to do that, I can do that soon.

### Expected Change

I'd like either this to be fixed so it can build properly, also only slightly related but a better "more official" place to download only igor from would be nice for ci, along with documentation for running igor on non-windows platforms.

### Steps To Reproduce

1. Acquire igor on Ubuntu 22.04 (Maybe other versions, not tested) 
2. Attempt to build project that uses steamworks and the post_build_step.sh
3. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which operating system(s) are you seeing the problem on?

Ubuntu 22 LTS

### Which platform(s) are you having trouble building this project for?

Ubuntu

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by DiasFranciscoA** [comment]
Morning @OmegaMetor, what version of the extension are you using I can see by the logs that this is from an older version of the extension. The message that you are seeing:

> #################################### INFORMATION ####################################
> Steam Extension is not available in this target: Linux (no setup required)
> #####################################################################################

...is not from a current version of the Steamworks extension. Regarding the error:

> System.IO.FileNotFoundException: Could not find file '/home/ubuntu/Gamemaker/out.zip'.

...please refer to the following [entry in the manual](https://manual.gamemaker.io/monthly/en/Settings/Building_via_Command_Line.htm) where it reads the `/of` should not be a path to a folder but a path to a file you will need to give it a file path instead if you want to use it `/of ~/Gamemaker/out/game.unx` for example

**Comment by OmegaMetor** [comment]
The Steamworks extension is version 1.1.3a, though slightly modified to add functions for GetUserItemVote and SetUserItemVote, only modifying the c++.

**Comment by patchuby** [comment]
@DiasFranciscoA I'm on the latest Steamworks extension version and this is still an issue, specifying an /of filename argument like suggested does not solve the issue. I've tried this on two different ubuntu machines. Removing the /of argument doesn't solve it either. 
I've submitted an issue over the Steamworks repo but should I open one here instead ?
