### ISSUE TITLE
qemu_pipe_read ANR triggered by slow operations in blamed thread

### ISSUE THREAD

**Issue by efeberku** [YoYoGames/GameMaker-Bugs#4395]
### Description

RenderThread (native)
tid=21 systid=3154 Root blocking qemu_pipe_read

Insight: Native lock contention
The main thread is blocked, waiting on a native synchronization routine, such as a mutex.

Native synchronization routines don't provide details on the exact lock, or where it is being held. Find the locked mutex in your source, and then locate other code locations where it is being acquired.You can use Android Studio's profiler to detect potential lock contentions if multiple threads frequently compete for the same lock.

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/60998058/2ca1446c-998d-4f2b-bbe9-d510ccf4296f)

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/60998058/2d48d622-647d-4568-a41c-3b1325082fad)

RenderThread (native):tid=21 systid=3154 
#00 pc 0x9da18 libc.so (read + 8)
#01 pc 0x15088 libOpenglSystemCommon.so (qemu_pipe_read + 16)
#02 pc 0xfdf8 libOpenglSystemCommon.so (QemuPipeStream::commitBufferAndReadFully(unsigned long, void*, unsigned long) + 268)
#03 pc 0x635d8 libGLESv2_enc.so ((anonymous namespace)::glFinishRoundTrip_enc(void*) + 244)
#04 pc 0xae48 libEGL_emulation.so (egl_window_surface_t::swapBuffers() + 824)
#05 pc 0xf6c0 libEGL_emulation.so (eglSwapBuffers + 448)
#06 pc 0x1fadc libEGL.so (android::eglSwapBuffersWithDamageKHRImpl(void*, void*, int*, int) + 524)
#07 pc 0x1c4b0 libEGL.so (eglSwapBuffersWithDamageKHR + 72)
#08 pc 0x35e9a8 libhwui.so (android::uirenderer::renderthread::EglManager::swapBuffers(android::uirenderer::renderthread::Frame const&, SkRect const&) + 124)
#09 pc 0x35e7f0 libhwui.so (android::uirenderer::skiapipeline::SkiaOpenGLPipeline::swapBuffers(android::uirenderer::renderthread::Frame const&, bool, SkRect const&, android::uirenderer::FrameInfo*, bool*) + 92)
#10 pc 0x48f230 libhwui.so (android::uirenderer::renderthread::CanvasContext::draw() + 732)
#11 pc 0x387e00 libhwui.so (android::uirenderer::renderthread::DrawFrameTask::run() + 588)
#12 pc 0x3b3ff4 libhwui.so (android::uirenderer::WorkQueue::process() + 156)
#13 pc 0x3b3d5c libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop() + 84)
#14 pc 0x12094 libutils.so (android::Thread::_threadLoop(void*) + 260)
#15 pc 0x11964 libutils.so (thread_data_t::trampoline(thread_data_t const*) + 404)
#16 pc 0xb1ff0 libc.so (__pthread_start(void*) + 264)
#17 pc 0x51ad8 libc.so (__start_thread + 64)

main (native)
tid=1 systid=3131 Triggered ANR syscall

main (native):tid=1 systid=3131 
#00 pc 0x4c25c libc.so (syscall + 28)
#01 pc 0x51068 libc.so (__futex_wait_ex(void volatile*, bool, int, bool, timespec const*) + 144)
#02 pc 0xb126c libc.so (pthread_cond_wait + 80)
#03 pc 0x564e0 libc++.so (std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 20)
#04 pc 0x58fec libc++.so (std::__1::__assoc_sub_state::__sub_wait(std::__1::unique_lock<std::__1::mutex>&) + 48)
#05 pc 0x3ee9b8 libhwui.so (std::__1::__assoc_state<android::uirenderer::DeferredLayerUpdater*>::move() + 64)
#06 pc 0x3f7cf8 libhwui.so (android::uirenderer::renderthread::RenderProxy::RenderProxy(bool, android::uirenderer::RenderNode*, android::uirenderer::IContextFactory*) + 464)
#07 pc 0x207fb8 libhwui.so (android::android_view_ThreadedRenderer_createProxy(_JNIEnv*, _jobject*, unsigned char, long) + 84)
       at android.graphics.HardwareRenderer.nCreateProxy(Native method)
       at android.graphics.HardwareRenderer.<init>(HardwareRenderer.java:171)
       at android.view.ThreadedRenderer.<init>(ThreadedRenderer.java:264)
       at android.view.ThreadedRenderer.create(ThreadedRenderer.java:232)
       at android.view.ViewRootImpl.enableHardwareAcceleration(ViewRootImpl.java:1495)
       at android.view.ViewRootImpl.setView(ViewRootImpl.java:1085)
       at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:400)
       at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:138)
       at com.android.internal.policy.PhoneWindow.openPanel(PhoneWindow.java:928)
       at com.android.internal.policy.PhoneWindow.onKeyUpPanel(PhoneWindow.java:1145)
       at com.android.internal.policy.PhoneWindow.onKeyUp(PhoneWindow.java:2071)
       at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:408)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:6377)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6243)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5725)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5782)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5748)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5913)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5756)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5970)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5729)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5782)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5748)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5756)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5729)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5782)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5748)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5946)
       at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:6104)
       at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:3159)
       at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:2723)
       at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:2714)
       at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:3136)
       at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:154)
       at android.os.MessageQueue.nativePollOnce(Native method)
       at android.os.MessageQueue.next(MessageQueue.java:335)
       at android.os.Looper.loopOnce(Looper.java:161)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7870)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)

Device
Brand:Google
Model:Pixel 6 Pro
Orientation:Unknown
RAM free: Unknown
Disk free: Unknown
Operating System
Version:Android 12
Orientation:Unknown
Rooted:No
ANR
Date:Jan 13, 2024, 6:03:38 AM
App version:0.0.17 (17)

### Expected Change

ANR's solved

### Steps To Reproduce

1. It happens to the users not me

### How reliably can you recreate this issue using your steps above?

Rarely

### Which version of GameMaker are you reporting this issue for?

2023.11.1 (Monthly)

### Which platform(s) are you seeing the problem on?

Android

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by stuckie** [comment]
From the callstack, it does not look like it is our code that is crashing - qemu is nothing to do with us.
