### ISSUE TITLE
UI/UX: Frequent failure to paste text into Beta IDE v2024.200.0.472  Runtime v2024.200.0.488

### ISSUE THREAD

**Issue by YYDan** [YoYoGames/GameMaker-Bugs#4472]
### Description
As my ui.log shows, I am currently getting frequent failure to paste text into Beta IDE v2024.200.0.472  Runtime v2024.200.0.488.

The error is:

[17:26:04:372(474f)] Exception in YoYoStudio.TextEditor.TextEditorInputHelper,Void InputHelper_SendInput() :    System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'startIndex')
   at System.String.Insert(Int32 startIndex, String value)
   at YYCodeEditor.Text.TextBuffer.TextSnapshot.Insert(TextPos _pos, String _text) in D:\a\YoYoStudio\YoYoStudio\YoYoStudio\IDE\YYCodeEditor\Text\TextBuffer\TextSnapshot.cs:line 209
   at YYCodeEditor.Text.TextBuffer.TextBuffer.Insert(TextPos position, String text) in D:\a\YoYoStudio\YoYoStudio\YoYoStudio\IDE\YYCodeEditor\Text\TextBuffer\TextBuffer.cs:line 92
   at YYCodeEditor.DocumentView.DoPaste(ClipBuffer _clipBuffer, Boolean _bIndent, Int32& _indentPosition) in D:\a\YoYoStudio\YoYoStudio\YoYoStudio\IDE\YYCodeEditor\DocumentView.cs:line 2702
   at YYCodeEditor.DocumentView.DoPaste() in D:\a\YoYoStudio\YoYoStudio\YoYoStudio\IDE\YYCodeEditor\DocumentView.cs:line 2593
   at YYCodeEditor.Commands.CommandExecutor.DoPaste(Command _cmd) in D:\a\YoYoStudio\YoYoStudio\YoYoStudio\IDE\YYCodeEditor\Commands\CommandExecutor.cs:line 299
   at YYCodeEditor.Commands.CommandExecutor.Execute(Command _cmd) in D:\a\YoYoStudio\YoYoStudio\YoYoStudio\IDE\YYCodeEditor\Commands\CommandExecutor.cs:line 88
   at YYCodeEditor.Input.InputManager.HandleInput(InputState _input, CodeEditor _editor) in D:\a\YoYoStudio\YoYoStudio\YoYoStudio\IDE\YYCodeEditor\Input\InputManager.cs:line 93
   at YYCodeEditor.CodeEditor.ProcessInput(InputState m_InputState) in D:\a\YoYoStudio\YoYoStudio\YoYoStudio\IDE\YYCodeEditor\CodeEditor.cs:line 352
   at YoYoStudio.TextEditor.TextEditorInputHelper.InputHelper_SendInput()
   at WeakDelegate(Object , Object[] )
   at YoYoStudio.Core.Utils.WeakDelegate`1.Invoke(Object[] _args) in D:\a\YoYoStudio\YoYoStudio\YoYoStudio\IDE\Core\Utils\WeakDelegate.cs:line 184

Text I have pasted includes:
That version number string above (from right-clicking the number in the IDE)
Text I pasted in from my ui.log when filing #4469
Text I cut and then pasted back into the IDE bug reporter Description and also Steps To Reproduce fields when filing #4469
The string " when filing #4469"  on the line immediately above

That last one failed to paste repeatedly until I shifted focus from the Descrition field and pasted it first time in the Steps field, then I could suddenly paste it in the Description field again (without cutting/coying again).

### Steps To Reproduce
1. Start GM and open any project  (the one I was using is attached to the bug I mentioned earlier)
2. Potentially use the code editor for a short while (unconfirmed)
3. Now try copying text either inside GameMaker or externally and then pasting it into GameMaker
4. Do this repeatedly and see if any fail with the ui.log error above.

[33553774-a852-445d-92cd-69e497506a2b](https://api.gamemaker.io/api/github/downloads/33553774-a852-445d-92cd-69e497506a2b)

**Comment by YYDan** [comment]
Have made the bullet points into a code block only because GitHub is automatically changing my text into links to the other issue.

**Comment by stuckie** [comment]
I cannot reproduce this against April betas.. I'm going to tentatively say it's been fixed in the interim...

**Comment by Emc1923** [comment]
Unable to reproduce as of  IDE v2024.400.0.539  Runtime v2024.400.0.558. Closing.
