### ISSUE TITLE
Building Projects: Having a Sound track inside a Sequence causes builds to fail in Feb24 Beta

### ISSUE THREAD

**Issue by SamTHodson** [YoYoGames/GameMaker-Bugs#4501]
### Description

Having any Sound track inside a Sequence will causes builds to fail with the following error.
```
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at YoYoStudio.Resources.GMProjectGraphVisitors.<>c__DisplayClass3_0.<ProjectPrefabDependencyCalculator>g__visitNode|0(Object o) in /home/runner/work/GameMaker/GameMaker/GameMaker/Runner/GMAssetCompiler/CoreResources/CoreResources/Resources/GMProjectGraphVisitors.cs:line 80
   at YoYoStudio.Resources.DataMemberGraphVisitor.<ForEachDataMember>g__visitObject|2_1(Object o, Int32 depth, <>c__DisplayClass2_0& ) in /home/runner/work/GameMaker/GameMaker/GameMaker/Runner/GMAssetCompiler/CoreResources/CoreResources/Resources/DataMemberGraphVisitor.cs:line 82
   at YoYoStudio.Resources.DataMemberGraphVisitor.<ForEachDataMember>g__visitObject|2_1(Object o, Int32 depth, <>c__DisplayClass2_0& ) in /home/runner/work/GameMaker/GameMaker/GameMaker/Runner/GMAssetCompiler/CoreResources/CoreResources/Resources/DataMemberGraphVisitor.cs:line 65
   at YoYoStudio.Resources.DataMemberGraphVisitor.<ForEachDataMember>g__visitObject|2_1(Object o, Int32 depth, <>c__DisplayClass2_0& ) in /home/runner/work/GameMaker/GameMaker/GameMaker/Runner/GMAssetCompiler/CoreResources/CoreResources/Resources/DataMemberGraphVisitor.cs:line 98
   at YoYoStudio.Resources.DataMemberGraphVisitor.<ForEachDataMember>g__visitObject|2_1(Object o, Int32 depth, <>c__DisplayClass2_0& ) in /home/runner/work/GameMaker/GameMaker/GameMaker/Runner/GMAssetCompiler/CoreResources/CoreResources/Resources/DataMemberGraphVisitor.cs:line 65
   at YoYoStudio.Resources.DataMemberGraphVisitor.<ForEachDataMember>g__visitObject|2_1(Object o, Int32 depth, <>c__DisplayClass2_0& ) in /home/runner/work/GameMaker/GameMaker/GameMaker/Runner/GMAssetCompiler/CoreResources/CoreResources/Resources/DataMemberGraphVisitor.cs:line 65
   at YoYoStudio.Resources.DataMemberGraphVisitor.<ForEachDataMember>g__visitObject|2_1(Object o, Int32 depth, <>c__DisplayClass2_0& ) in /home/runner/work/GameMaker/GameMaker/GameMaker/Runner/GMAssetCompiler/CoreResources/CoreResources/Resources/DataMemberGraphVisitor.cs:line 98
   at YoYoStudio.Resources.DataMemberGraphVisitor.<ForEachDataMember>g__visitObject|2_1(Object o, Int32 depth, <>c__DisplayClass2_0& ) in /home/runner/work/GameMaker/GameMaker/GameMaker/Runner/GMAssetCompiler/CoreResources/CoreResources/Resources/DataMemberGraphVisitor.cs:line 65
   at YoYoStudio.Resources.DataMemberGraphVisitor.<ForEachDataMember>g__visitObject|2_1(Object o, Int32 depth, <>c__DisplayClass2_0& ) in /home/runner/work/GameMaker/GameMaker/GameMaker/Runner/GMAssetCompiler/CoreResources/CoreResources/Resources/DataMemberGraphVisitor.cs:line 98
   at YoYoStudio.Resources.DataMemberGraphVisitor.<ForEachDataMember>g__visitObject|2_1(Object o, Int32 depth, <>c__DisplayClass2_0& ) in /home/runner/work/GameMaker/GameMaker/GameMaker/Runner/GMAssetCompiler/CoreResources/CoreResources/Resources/DataMemberGraphVisitor.cs:line 65
   at YoYoStudio.Resources.DataMemberGraphVisitor.<ForEachDataMember>g__visitObject|2_1(Object o, Int32 depth, <>c__DisplayClass2_0& ) in /home/runner/work/GameMaker/GameMaker/GameMaker/Runner/GMAssetCompiler/CoreResources/CoreResources/Resources/DataMemberGraphVisitor.cs:line 65
   at YoYoStudio.Resources.DataMemberGraphVisitor.<ForEachDataMember>g__visitObject|2_1(Object o, Int32 depth, <>c__DisplayClass2_0& ) in /home/runner/work/GameMaker/GameMaker/GameMaker/Runner/GMAssetCompiler/CoreResources/CoreResources/Resources/DataMemberGraphVisitor.cs:line 98
   at YoYoStudio.Resources.DataMemberGraphVisitor.<ForEachDataMember>g__visitObject|2_1(Object o, Int32 depth, <>c__DisplayClass2_0& ) in /home/runner/work/GameMaker/GameMaker/GameMaker/Runner/GMAssetCompiler/CoreResources/CoreResources/Resources/DataMemberGraphVisitor.cs:line 65
   at YoYoStudio.Resources.DataMemberGraphVisitor.ForEachDataMember(Object root, Func`2 visitNode, Func`2 canBeMultiReferenced, Action`2 trace) in /home/runner/work/GameMaker/GameMaker/GameMaker/Runner/GMAssetCompiler/CoreResources/CoreResources/Resources/DataMemberGraphVisitor.cs:line 142
   at YoYoStudio.Resources.GMProjectGraphVisitors.ProjectPrefabDependencyCalculator(GMProject rootProject, Boolean transitive) in /home/runner/work/GameMaker/GameMaker/GameMaker/Runner/GMAssetCompiler/CoreResources/CoreResources/Resources/GMProjectGraphVisitors.cs:line 101
   at GMAssetCompiler.Loader.LoadGMS2CreateAssets(String _filename)
   at GMAssetCompiler.Loader.Load(String _name)
   at GMAssetCompiler.Program.GetAssetsFile(List`1 _args)
   at GMAssetCompiler.Program.Main(String[] _args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Igor.Program.ExecuteAssetCompiler(String _args)
   at Igor.Program.SetupBuildEnv(String _options, String _project, String _runtimeLocation, String _cache, String _temp, String _user, String _outputFilename, String _targetFilename, String _debuggerPort, Boolean _launchPackage)
   at Igor.Program.Main(String[] args)
[createdump] Writing minidump to file C:\ProgramData\GameMakerStudio2-Beta\Dumps\gmdump.36740.dmp
[createdump] Dump successfully written
Igor complete.
elapsed time 00:00:02.3492883s for command "C:\ProgramData/GameMakerStudio2-Beta/Cache/runtimes\runtime-2024.200.0.489/bin/igor/windows/x64/Igor.exe" -j=8  -options="C:\Users\samth\AppData\Local\GameMakerStudio2-Beta\GMS2TEMP\build.bff" -v -- Windows Run started at 01/25/2024 13:49:39
FAILED: Run Program Complete
``` 
Tested using Beta IDE v2024.200.0.474  Runtime v2024.200.0.489

[Contact Us Package](https://drive.google.com/file/d/1EYgFN_Bh2pZK3ijZbRJa0O6migLbGsUA/view?usp=drive_link)

### Steps To Reproduce

1. Start GameMaker Beta and open/create a project
2. Create a Sound 
3. Create a Sequence
4. Add the Sound as a track in the Sequence
5. Build the project
6. Observe the issue

Repro: 100%

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.200 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by cameron-home** [comment]
Verified fixed in IDE v2024.200.0.478  Runtime v2024.200.0.493
