### ISSUE TITLE
Can't run, missing audio files

### ISSUE THREAD

**Issue by patchuby** [YoYoGames/GameMaker-Bugs#4602]
### Description
Can't manage to make a build, I'm seeing error messages about missing audio files in the build output :

System.IO.FileNotFoundException: Could not find file '/tmp/GameMakerStudio2/Cache/GMS2CACHE/Chronique__FA7BA81_F4363B1B/Chronique des Silencieux/Default/Audio/snd_BerlinFlatRock.ogg'.
File name: '/tmp/GameMakerStudio2/Cache/GMS2CACHE/Chronique__FA7BA81_F4363B1B/Chronique des Silencieux/Default/Audio/snd_BerlinFlatRock.ogg'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Interop.CheckIo(Error error, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at YoYoStudio.Resources.FileIO.<>c.<SetDefaultFileFunctions>b__54_7(String _from, String _to) in /home/runner/work/GameMaker/GameMaker/GameMaker/Runner/GMAssetCompiler/CoreResources/FileIO/FileIO.cs:line 245

I doesn't happen on all files, can't seem to find a commonality (ogg, streamed)
The build goes through, but crashes immediately with the following message :
Failed to find streamed sound with path '/tmp/GameMakerStudio2/GMS2TEMP/Chronique_des_Silencieux_3CBBBFBE_VM/snd_meubledrogue_trigger.ogg'

### Steps To Reproduce
Launch a build via run

[d7e46262-d159-44bd-9206-ef76a617e1e1](https://api.gamemaker.io/api/github/downloads/d7e46262-d159-44bd-9206-ef76a617e1e1)

**Comment by ScottGrogin** [comment]
What os are you on?
