### ISSUE TITLE
Changing Configuration freezes IDE

### ISSUE THREAD

**Issue by clee2005** [YoYoGames/GameMaker-Bugs#4603]
### Description
I have a configuration "Amazon" when I switch to it, the IDE now freezes and I cannot do anything other than kill the process and reload.   It means that I cannot access that configuration at all like this.   I WAS able to go through some of the sprites and most recent changes and remove the configuration directly from the .yy files and that seemed to fix the issue.   It's back now and I don't see anything else that I can change but in the ui.log I was able to see that it logged this just as it froze : 

[14:14:58:870(a31e)] Exception in YoYoStudio.Resources.ProjectManager+<>c__DisplayClass16_1,Void <SaveProject>b__3() :    System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at OddlySpecific.Feather.FeatherProject.ActiveConfig_OnChange(String _config)
   at YoYoStudio.Resources.GMProject.SetConfig(String _config)
   at YoYoStudio.GUI.Gadgets.TargetSelectButton.<>c__DisplayClass14_0.<InitialiseTargetInfo>b__5(Boolean _success)
   at YoYoStudio.IDE.<>c__DisplayClass305_0.<SaveProjectIncremental>b__0(GMProject _project, Boolean _isSuccess)
   at YoYoStudio.Resources.ProjectManager.<>c__DisplayClass16_1.<SaveProject>b__3()
   at WeakDelegate(Object , Object[] )
   at YoYoStudio.Core.Utils.WeakDelegate`1.Invoke(Object[] _args)

### Steps To Reproduce
Choose another configuration and the project processes for a short time, then freezes not accepting any more input.

[7c3327f5-e505-4876-820d-6af0be4c56df](https://api.gamemaker.io/api/github/downloads/7c3327f5-e505-4876-820d-6af0be4c56df)

**Comment by clee2005** [comment]
I know I haven't given you much to work with.  I was hoping that exception might mean something obvious, or you would have some troubleshooting suggestions that I could do to get the configurations to switch over successfully.

**Comment by clee2005** [comment]
Ok, so deleting the GMS2IDE folder allowed me to change configurations.   It would freeze again after closing it and reopening.  I was able to narrow it down to a single .png file in the ICONS folder of the cached project and I removed that and readded it and it seems ok now.  I did compare the .yy file to another sprite and there was nothing different about it (dimensions but no elements that were not in the other, presumably working .yy file).    So there's some corruption happening.   Oh and the icon size was 32 x 5, where the original image was 179 x 30.  

C:\Users\User\AppData\Roaming\GameMakerStudio2\Cache\GMS2IDE\WordWowSea_8BD83E23_A42EF528\Icons

**Comment by stuckie** [comment]
We will need either the project or the image to investigate why it fell over
