### ISSUE TITLE
__yy_sdf_shader.yyp(5,54): GMSC Error: name expected.

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GameMaker-Bugs#4646]
### Description
When attempting to clean or run the project, we get the message:

runtime-2024.200.0.501/bin/ProjectImports/__yy_sdf_shader/__yy_sdf_shader.yyp(5,54): GMSC Error: name expected.

### Steps To Reproduce
Run or clean the project.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.200.0.485 Runtime v2024.200.0.501

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22000.0

[6100b15d-f648-4518-b17f-c6049c1e6f20](https://api.gamemaker.io/api/github/downloads/6100b15d-f648-4518-b17f-c6049c1e6f20)

**Comment by shichen85** [comment]
```
elapsed time 00:00:00.3170560s for command "C:\ProgramData\GameMakerStudio2-Beta\Cache\runtimes\runtime-2024.200.0.501/bin/igor/windows/x64/Igor.exe" -j=8  -options="C:\temp\GMS2TEMP\build.bff" -v -- windows Clean started at 02/06/2024 11:51:01
---------- STOPPING ----------
FAILED : Clean Program Complete
"C:\ProgramData\GameMakerStudio2-Beta\Cache\runtimes\runtime-2024.200.0.501/bin/igor/windows/x64/Igor.exe"  -j=8  -options="C:\temp\GMS2TEMP\build.bff" -v -- windows Clean

Loaded Macros from C:\temp\GMS2CACHE\i32_71D39093\macros.json
Options: C:\ProgramData\GameMakerStudio2-Beta\Cache\runtimes\runtime-2024.200.0.501\bin\platform_setting_defaults.json
Options: C:\Users\shi\AppData\Roaming/GameMakerStudio2-Beta\build_2151704\local_settings.json
Options: C:\temp\GMS2CACHE\i32_71D39093\targetoptions.json
Setting up the Asset compiler
C:\ProgramData\GameMakerStudio2-Beta\Cache\runtimes\runtime-2024.200.0.501/bin/assetcompiler/windows/x64/GMAssetCompiler.dll  /c /mv=1 /zpex /iv=0 /rv=0 /bv=0 /j=8  /gn="i32" /td="C:\temp\GMS2TEMP" /cd="C:\temp\GMS2CACHE\i32_71D39093" /rtp="C:\ProgramData\GameMakerStudio2-Beta\Cache\runtimes\runtime-2024.200.0.501" /zpuf="C:\Users\shi\AppData\Roaming/GameMakerStudio2-Beta\build_2151704"  /ffe="d3t+fjZrf25zeTdwgjZ5em98a3GCN4ODbTZzeH5vdnZzfW94fW82eH92dnN9cjZ2eXFzeGl9fXk2fm99fjZtf31+eXdpb3iANnBzdn41cII2cYJpd3luaYFrdnZ6a3pvfDZxgml3eW5pcWt3b31+fHN6NnZzgG9pgWt2dnprem98aX1/bH1tfHN6fnN5eDZ8eXZ2bGttdQ==" /m=llvm-win /tgt=64 /llvmSource="C:\ProgramData\GameMakerStudio2-Beta\Cache\runtimes\runtime-2024.200.0.501/yyc/"  /nodnd /cfg="Default" /o="C:\temp\GMS2TEMP\i32_4C07461B_YYC" /sh=True /optionsini="C:\temp\GMS2TEMP\i32_4C07461B_YYC\options.ini" /baseproject="C:\ProgramData\GameMakerStudio2-Beta\Cache\runtimes\runtime-2024.200.0.501\BaseProject\BaseProject.yyp" "C:\Users\shi\Documents\GameMakerStudio2\i32\i32.yyp" /pre
process="C:\temp\GMS2CACHE\i32_71D39093"
Found Project Format 2
+++ GMSC serialisation:  SUCCESSFUL LOAD AND LINK TIME: 318.3167ms
Loaded Project: i32
finished.
Found Project Format 2
C:/ProgramData/GameMakerStudio2-Beta/Cache/runtimes/runtime-2024.200.0.501/bin/ProjectImports/__yy_sdf_shader/__yy_sdf_shader.yyp(5,54): GMSC Error: name expected.
Core Resources : IDE Message - ProjectLoad_ErrorTitle : ProjectLoad_ErrorMessage ( C:/ProgramData/GameMakerStudio2-Beta/Cache/runtimes/runtime-2024.200.0.501/bin/ProjectImports/__yy_sdf_shader/__yy_sdf_shader.yyp(5,54): GMSC Error: name expected. )
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at GMAssetCompiler.Loader.<>c__DisplayClass6_0.<AddGMS2ProjToAssets>b__2(ResourceBase _project)
   at YoYoStudio.Resources.ProjectInfo.<>c__DisplayClass23_0.<LoadProject>g__handleFailure|4(String message) in /home/runner/work/GameMaker/GameMaker/GameMaker/Runner/GMAssetCompiler/CoreResources/CoreResources/Management/ProjectInfo.cs:line 294
   at YoYoStudio.Resources.ProjectInfo.LoadProject(String _path, Boolean _setActive, OnLoadSaveSuccess _onSuccess, OnLoadSaveUpdate _onUpdate, OnLoadSaveFailed _onFailed, Boolean _triedProjectTool) in /home/runner/work/GameMaker/GameMaker/GameMaker/Runner/GMAssetCompiler/CoreResources/CoreResources/Management/ProjectInfo.cs:line 322
   at GMAssetCompiler.Loader.AddGMS2ProjToAssets(String _filename, GMAssets _assets, Boolean _isFilter)
   at GMAssetCompiler.Loader.MergeInSDFShader(GMAssets _assets)
   at GMAssetCompiler.Loader.Load(String _name)
   at GMAssetCompiler.Program.GetAssetsFile(List`1 _args)
   at GMAssetCompiler.Program.Main(String[] _args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Igor.Program.ExecuteAssetCompiler(String _args)
   at Igor.Program.SetupBuildEnv(String _options, String _project, String _runtimeLocation, String _cache, String _temp, String _user, String _outputFilename, String _targetFilename, String _debuggerPort, Boolean _launchPackage)
   at Igor.Program.Main(String[] args)
[createdump] Writing minidump to file C:\ProgramData\GameMakerStudio2-Beta\Dumps\gmdump.4420.dmp
[createdump] Dump successfully written
Igor complete.
elapsed time 00:00:02.9264612s for command "C:\ProgramData\GameMakerStudio2-Beta\Cache\runtimes\runtime-2024.200.0.501/bin/igor/windows/x64/Igor.exe" -j=8  -options="C:\temp\GMS2TEMP\build.bff" -v -- windows Clean started at 02/06/2024 11:51:01
FAILED : Clean Program Complete
Creating bug report...
 Zipping project...
 Zipping report...
 Sending bug report...
 Uploading bug report files...
Bug Report (#4646) files uploaded successfully
```

**Comment by shichen85** [comment]
Can confirm! Thanks for the fix.

**Comment by caitlinrmcintyre** [comment]
Verified fix in Beta IDE v2024.200.0.494  Runtime v2024.200.0.511, thanks.
