### ISSUE TITLE
Cannot run MacOS on a separate machine even when test connection is successful

### ISSUE THREAD

**Issue by patchuby** [YoYoGames/GameMaker-Bugs#4669]
### Description
I've managed before to make it run, even today, and I haven't changed anything obvious since.
Might be an issue with my firewall/network, but at least the test connection should fail too.
This is the output :

System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Dns.GetHostEntryOrAddressesCore(String hostName, Boolean justAddresses, AddressFamily addressFamily, ValueStopwatch stopwatch)
   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress, AddressFamily family)
   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)
   at Renci.SshNet.Abstractions.DnsAbstraction.GetHostAddresses(String hostNameOrAddress)
   at Renci.SshNet.Connection.ConnectorBase.SocketConnect(String host, Int32 port, TimeSpan timeout)
   at Renci.SshNet.Connection.DirectConnector.Connect(IConnectionInfo connectionInfo)
   at Renci.SshNet.Session.Connect()
   at Renci.SshNet.BaseClient.CreateAndConnectSession()
   at Renci.SshNet.BaseClient.Connect()
   at Igor.RealSSH.pscp(String local, String remote, Boolean recursive)
   at Igor.MacUtils.RunOnMac(String workingFolder, String _zip, String remote_install_path)
   at Igor.MacBuilder.Run()

I've included the generated dump in case it's not included by default

[f09f5e0e-4221-46b5-ae64-7c95c76d841f](https://api.gamemaker.io/api/github/downloads/f09f5e0e-4221-46b5-ae64-7c95c76d841f)

**Comment by YYDan** [comment]
Is your remote Mac device added into GM via IP address or via name-resolution?

**Comment by patchuby** [comment]
@YYDan I use name-resolution

**Comment by patchuby** [comment]
I confirm that using the IP address solves the issue

**Comment by DragoniteSpam** [comment]
This also happens on Linux, btw.
