### ISSUE TITLE
GMAssetCompiler.HTML5Saver Compiler Crash

### ISSUE THREAD

**Issue by acedward** [YoYoGames/GameMaker-Bugs#4828]
### Description

runtime-2024.200.0.519 (beta) fails to build with HTML5.
Opera compiles successfully.

## HTML5 Build Fails.
```
/Users/Shared/GameMakerStudio2-Beta/Cache/runtimes/runtime-2024.200.0.519/bin/igor/osx/arm64/Igor --project=/Users/user_name/company_name/game_name_hh/frontend/monster-game.yyp --rp=/Users/Shared/GameMakerStudio2-Beta/Cache/runtimes/runtime-2024.200.0.519 --lf=/Users/user_name/.config/GameMakerStudio2-Beta/ac.user_name_4041095/licence.plist --tf=/Users/user_name/company_name/game_name_hh/gm_cli_build --temp=/Users/user_name/company_name/game_name_hh/gm_cli_temp --cache=/Users/user_name/company_name/game_name_hh/gm_cli_cache html5 folder
Options: /Users/Shared/GameMakerStudio2-Beta/Cache/runtimes/runtime-2024.200.0.519/bin/platform_setting_defaults.json
Options: /Users/user_name/company_name/game_name_hh/local_settings.json
Failed to load Options from /Users/user_name/company_name/game_name_hh/local_settings.json
Setting up the Asset compiler
Found Project Format 2
+++ GMSC serialisation:  SUCCESSFUL LOAD AND LINK TIME: 525.352ms
Loaded Project: monster-game
finished.
Found Project Format 2
+++ GMSC serialisation:  SUCCESSFUL LOAD AND LINK TIME: 30.746ms
Loaded Project: __yy_sdf_shader
finished.
Found Project Format 2
+++ GMSC serialisation:  SUCCESSFUL LOAD AND LINK TIME: 11.391ms
Loaded Project: __yy_sdf_effect_shader
finished.
Found Project Format 2
+++ GMSC serialisation:  SUCCESSFUL LOAD AND LINK TIME: 9.131ms
Loaded Project: __yy_sdf_blur_shader
finished.
Found Project Format 2
+++ GMSC serialisation:  SUCCESSFUL LOAD AND LINK TIME: 15.589ms
Loaded Project: GMPresetParticles
finished.
Release build
Options: /Users/user_name/company_name/game_name_hh/gm_cli_cache/ExtensionOptions.json
OptionsIni
Options: /Users/user_name/company_name/game_name_hh/gm_cli_cache/PlatformOptions.json
Looking for built-in fallback image in /Users/Shared/GameMakerStudio2-Beta/Cache/runtimes/runtime-2024.200.0.519/bin/BuiltinImages
Saving HTML5 file... /Users/user_name/company_name/game_name_hh/output/monster-game/html5game/monster-game.js
Looking for built-in particle images in /Users/Shared/GameMakerStudio2-Beta/Cache/runtimes/runtime-2024.200.0.519/bin/assetcompiler/ParticleImages
Looking for built-in font images in /Users/Shared/GameMakerStudio2-Beta/Cache/runtimes/runtime-2024.200.0.519/bin/assetcompiler/BuiltinFonts
Fonts - Texture group not found in FONT_builtin.yy
Texture Group - __YY__0fallbacktexture.png_YYG_AUTO_GEN_TEX_GROUP_NAME_
Texture Group - Default
Rebuild cache file /Users/user_name/company_name/game_name_hh/gm_cli_cache/monster-game/Default/TextureGroups/_4096_0/__YY__0fallbacktexture.png_YYG_AUTO_GEN_TEX_GROUP_NAME_.texturePreview.xml due to changed texture format
Rebuild cache file /Users/user_name/company_name/game_name_hh/gm_cli_cache/monster-game/Default/TextureGroups/_4096_131/Default.texturePreview.xml due to changed texture format
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at GMAssetCompiler.HTML5Saver.<>c__DisplayClass267_0.<WriteRooms>b__0(KeyValuePair`2 _kvp, TextWriter __s, Int32 __n)
   at GMAssetCompiler.HTML5Saver.WriteDataKVP[T](IList`1 _data, TextWriter _s, WriteDelegateKVP`1 _del)
   at GMAssetCompiler.HTML5Saver.WriteRooms(IList`1 _rooms, TextWriter _s)
   at GMAssetCompiler.HTML5Saver.SaveAssetsAsJS(GMAssets _assets, TextWriter sw)
   at GMAssetCompiler.HTML5Saver.Save(GMAssets _assets, TextWriter _s)
   at GMAssetCompiler.HTML5Saver.Save(GMAssets _assets, String _name)
   at GMAssetCompiler.Program.CompileProject(GMAssets _file)
   at GMAssetCompiler.Program.Reentry(String[] _args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Igor.Program.ExecuteAssetCompiler(String _args)
   at Igor.HTML5Builder.Compile(Boolean _exe)
   at Igor.HTML5Builder.Deploy(Boolean _exe)
   at Igor.HTML5Builder.Package()
   at Igor.HTML5Builder.folder()
```

## OperaGX build works:
```
rm -rf gm_cli_cache output gm_cli_build  && /Users/Shared/GameMakerStudio2-Beta/Cache/runtimes/runtime-2024.200.0.519/bin/igor/osx/arm64/Igor --project=/Users/user_name/company_name/game_name_hh/frontend/monster-game.yyp --rp=/Users/Shared/GameMakerStudio2-Beta/Cache/runtimes/runtime-2024.200.0.519 --lf=/Users/user_name/.config/GameMakerStudio2-Beta/ac.user_name_4041095/licence.plist --tf=/Users/user_name/company_name/game_name_hh/gm_cli_build --temp=/Users/user_name/company_name/game_name_hh/gm_cli_temp --cache=/Users/user_name/company_name/game_name_hh/gm_cli_cache OperaGX Package 
Options: /Users/Shared/GameMakerStudio2-Beta/Cache/runtimes/runtime-2024.200.0.519/bin/platform_setting_defaults.json
Options: /Users/user_name/company_name/game_name_hh/local_settings.json
Failed to load Options from /Users/user_name/company_name/game_name_hh/local_settings.json
Setting up the Asset compiler
Found Project Format 2
+++ GMSC serialisation:  SUCCESSFUL LOAD AND LINK TIME: 533.104ms
Loaded Project: monster-game
finished.
Found Project Format 2
+++ GMSC serialisation:  SUCCESSFUL LOAD AND LINK TIME: 31.738ms
Loaded Project: __yy_sdf_shader
finished.
Found Project Format 2
+++ GMSC serialisation:  SUCCESSFUL LOAD AND LINK TIME: 10.453ms
Loaded Project: __yy_sdf_effect_shader
finished.
Found Project Format 2
+++ GMSC serialisation:  SUCCESSFUL LOAD AND LINK TIME: 9.273ms
Loaded Project: __yy_sdf_blur_shader
finished.
Found Project Format 2
+++ GMSC serialisation:  SUCCESSFUL LOAD AND LINK TIME: 15.847ms
Loaded Project: GMPresetParticles
finished.
Release build
Options: /Users/user_name/company_name/game_name_hh/gm_cli_cache/ExtensionOptions.json
Options: /Users/user_name/company_name/game_name_hh/gm_cli_cache/PlatformOptions.json
Options: /Users/user_name/company_name/game_name_hh/gm_cli_cache/MainOptions.json
[Compile] Run asset compiler
Looking for built-in fallback image in /Users/Shared/GameMakerStudio2-Beta/Cache/runtimes/runtime-2024.200.0.519/bin/BuiltinImages
Compile Constants...finished.
Remove DnD...finished.
Compile Scripts...finished.
Compile Rooms...finished..... 0 CC empty
Compile Objects...finished.... 23 empty events
Compile Timelines...finished.
Compile Triggers...finished.
Compile Extensions...finished.
Global scripts...finished.
finished.
collapsing enums.
Final Compile...finished.
Saving IFF file... /Users/user_name/company_name/game_name_hh/output/monster-game/monster-game.unx
Writing Chunk... GEN8 size ... -0.00 MB
option_game_speed=60
Writing Chunk... OPTN size ... 0.00 MB
Writing Chunk... LANG size ... 0.00 MB
Writing Chunk... EXTN size ... 0.00 MB
Writing Chunk... SOND size ... 0.00 MB
Converting bossbattle2_piano to Wav 16bit mono @ 44100Hz
Converting battle1_legendary_piano to Wav 16bit mono @ 44100Hz
Converting bossbattle1_piano to Wav 16bit mono @ 44100Hz
Converting dragonfly to Wav 16bit mono @ 44100Hz
Converting music_intro to Wav 16bit mono @ 44100Hz
Converting sketchy_situation_8bit to Ogg with bit rate 128, quality 2, mono @ 44100Hz
Converting snd_excavating to Ogg with bit rate 128, quality 2, mono @ 44100Hz
Converting snd_ok to Wav 16bit mono @ 44100Hz
Converting snd_menu_open_2 to Wav 16bit mono @ 44100Hz
Converting prancing_evil_8bit to Ogg with bit rate 128, quality 2, mono @ 44100Hz
Converting snd_battle_restore to Wav 16bit mono @ 44100Hz
Converting snd_menu_open to Wav 16bit mono @ 44100Hz
Converting snd_success_jingle to Wav 16bit mono @ 44100Hz
Converting snd_menu_select to Wav 16bit mono @ 44100Hz
Converting snd_battle_damage to Wav 16bit mono @ 44100Hz
Writing audio file battle1_8bit.ogg...
Writing audio file battle2_8bit.ogg...
Writing audio file bossbattle1_8bit.ogg...
Writing audio file bossbattle2_8bit.ogg...
Writing audio file cave_8bit.ogg...
Writing audio file city1_8bit.ogg...
Writing audio file city2_8bit.ogg...
Writing audio file event1_8bit.ogg...
Writing audio file event2_8bit.ogg...
Writing audio file flying_8bit.ogg...
Writing audio file luckymarket_8bit.ogg...
Writing audio file menutheme_8bit.ogg...
Writing audio file peaceful1_8bit.ogg...
Writing audio file peaceful2_8bit.ogg...
Writing audio file route1_8bit.ogg...
Writing audio file route2_8bit.ogg...
Writing audio file route3_8bit.ogg...
Writing audio file route4_8bit.ogg...
Writing audio file rural1_8bit.ogg...
Writing audio file rural2_8bit.ogg...
Writing audio file rural3_8bit.ogg...
Writing audio file sea_8bit.ogg...
Writing Chunk... AGRP size ... 0.00 MB
Writing Chunk... SPRT size ... 0.00 MB
Writing Chunk... BGND size ... 0.03 MB
Writing Chunk... PATH size ... 0.31 MB
Writing Chunk... SCPT size ... 0.00 MB
Writing Chunk... GLOB size ... 0.01 MB
Writing Chunk... SHDR size ... 0.00 MB
Writing Chunk... FONT size ... 0.00 MB
Writing Chunk... TMLN size ... 0.42 MB
Writing Chunk... OBJT size ... 0.00 MB
Writing Chunk... FEDS size ... 0.02 MB
Writing Chunk... ACRV size ... 0.00 MB
Writing Chunk... SEQN size ... 0.00 MB
Writing Chunk... TAGS size ... 0.00 MB
Writing Chunk... ROOM size ... 0.00 MB
Writing Chunk... DAFL size ... 0.79 MB
Writing Chunk... EMBI size ... 0.00 MB
Writing Chunk... PSEM size ... 0.00 MB
Writing Chunk... PSYS size ... 0.00 MB
Writing Chunk... TPAGE size ... 0.00 MB
Texture Group - __YY__0fallbacktexture.png_YYG_AUTO_GEN_TEX_GROUP_NAME_
Texture Group - Default
Writing Chunk... TGIN size ... 0.05 MB
Writing Chunk... CODE size ... 0.00 MB
Writing Chunk... VARI size ... 0.27 MB
Writing Chunk... FUNC size ... 0.04 MB
Writing Chunk... FEAT size ... 0.02 MB
Writing Chunk... STRG size ... 0.00 MB
Writing Chunk... TXTR size ... 0.13 MB
0 Compressing texture... writing texture __yy__0fallbacktexture.png_yyg_auto_gen_tex_group_name__0.yytex... 
1 Compressing texture... writing texture default_0.yytex... 
2 Compressing texture... writing texture default_1.yytex... 
3 Compressing texture... writing texture default_2.yytex... 
4 Compressing texture... writing texture default_3.yytex... 
5 Compressing texture... writing texture default_4.yytex... 
Writing Chunk... AUDO size ... 16.30 MB
Stats : GMA : Elapsed=9747.586
Stats : GMA : sp=299,au=41,bk=18,pt=0,sc=715,sh=3,fo=3,tl=0,ob=50,ro=34,da=379,ex=1,ma=45,fm=0xB29D6DFE02A4
runnerGameVersion=0.0.0.0
10
Copying /Users/Shared/GameMakerStudio2-Beta/Cache/runtimes/runtime-2024.200.0.519/operagx/index.html to /Users/user_name/company_name/game_name_hh/output/monster-game/runner/index.html...
Copying /Users/Shared/GameMakerStudio2-Beta/Cache/runtimes/runtime-2024.200.0.519/operagx/runner-debugger.wasm to /Users/user_name/company_name/game_name_hh/output/monster-game/runner/runner-debugger.wasm...
Copying /Users/Shared/GameMakerStudio2-Beta/Cache/runtimes/runtime-2024.200.0.519/operagx/runner.js to /Users/user_name/company_name/game_name_hh/output/monster-game/runner/runner.js...
Copying /Users/Shared/GameMakerStudio2-Beta/Cache/runtimes/runtime-2024.200.0.519/operagx/audio-worklet.js to /Users/user_name/company_name/game_name_hh/output/monster-game/runner/audio-worklet.js...
Copying /Users/Shared/GameMakerStudio2-Beta/Cache/runtimes/runtime-2024.200.0.519/operagx/runner.wasm to /Users/user_name/company_name/game_name_hh/output/monster-game/runner/runner.wasm...
Copying /Users/Shared/GameMakerStudio2-Beta/Cache/runtimes/runtime-2024.200.0.519/operagx/runner.html to /Users/user_name/company_name/game_name_hh/output/monster-game/runner/runner.html...
Copying /Users/Shared/GameMakerStudio2-Beta/Cache/runtimes/runtime-2024.200.0.519/operagx/fnames to /Users/user_name/company_name/game_name_hh/output/monster-game/runner/fnames...
Copying /Users/Shared/GameMakerStudio2-Beta/Cache/runtimes/runtime-2024.200.0.519/operagx/runner-sw.js to /Users/user_name/company_name/game_name_hh/output/monster-game/runner/runner-sw.js...
Copying /Users/Shared/GameMakerStudio2-Beta/Cache/runtimes/runtime-2024.200.0.519/operagx/sw.js to /Users/user_name/company_name/game_name_hh/output/monster-game/runner/sw.js...
Copying /Users/Shared/GameMakerStudio2-Beta/Cache/runtimes/runtime-2024.200.0.519/operagx/runner-debugger.js to /Users/user_name/company_name/game_name_hh/output/monster-game/runner/runner-debugger.js...
Igor complete.
``` 

https://drive.google.com/file/d/1Qd3HWwLVE3ppeci57uxsuj8iN-Jdoh_z/view?usp=sharing
pass: gamemaker

BTW there is no tick as the issue requires
<img width="894" alt="image" src="https://github.com/YoYoGames/GameMaker-Bugs/assets/3951895/9d570b5b-1969-455e-8d37-61e0e520466a">

<img width="600" alt="image" src="https://github.com/YoYoGames/GameMaker-Bugs/assets/3951895/bd9c39b5-da1c-4f5c-ae7b-2e4d9a596503">

I can provide a complete project to non-public location. 

### Steps To Reproduce

1. Start GameMaker
2. Compile via CLI or Gamemaker GUI

NOTE: I can provide a sample project 

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.200 (Betas)

### Which operating system(s) are you seeing the problem on?

macOS Sonoma

### Which platform(s) are you having trouble building this project for?

macOS

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by rwkay** [comment]
Fixed in 2024.2

**Comment by Emc1923** [comment]
Verified in  IDE v2024.200.0.505  Runtime v2024.200.0.523

**Comment by YYDan** [comment]
"I can provide a complete project to non-public location." - all attachments sent via the in-IDE bug reporter are always private.
