### ISSUE TITLE
IDE Unable to load my project

### ISSUE THREAD

**Issue by nullbunny** [YoYoGames/GameMaker-Bugs#4891]
### Description
When I first started the new version it, it showed the error attached.

I restarted the IDE and the error did not reappear, but I am unable to load my projects - see second screenshot

### Steps To Reproduce
1. Install new version
2. Start the IDE - see first error
3. Restart IDE - project loading fails

### Which version of GameMaker are you reporting this issue for?
IDE v2024.2.0.132 Runtime v2024.2.0.163

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[a4683d70-416a-42d1-9778-c7eda0c28c71](https://api.gamemaker.io/api/github/downloads/a4683d70-416a-42d1-9778-c7eda0c28c71)

**Comment by nullbunny** [comment]
I also can't load any other of the tiny test projects again I made during the beta. It might be a regression of a previous bug I had reported: #4582

**Comment by YYDan** [comment]
Hi,

This appears to be that your machine no longer has the runtime installed correctly - looks like maybe an AV client is modifying your install, as I can see you had loads of errors when downloading the runtime files in the _previous_ run of the IDE and then at the end of your log we can see:

```
[10:21:43:333(ada7)] Unable to launch "C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2024.2.0.163/bin/projecttool/windows/x64/ProjectTool.exe": System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2024.2.0.163/bin/projecttool/windows/x64/ProjectTool.exe' with working directory 'C:\Program Files\GameMaker Studio 2'. Das System kann die angegebene Datei nicht finden.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at YoYoStudio.Core.Utils.CmdProcess.StartProcess(String _working_directory, OutputDelegate _output, OutputDelegate _error) in D:\a\YoYoStudio\YoYoStudio\YoYoStudio\IDE\Core\Utils\CmdProcess.cs:line 245 [StartProcess, D:\a\YoYoStudio\YoYoStudio\YoYoStudio\IDE\Core\Utils\CmdProcess.cs, 267]
```

Obviously, that file being missing will explain why you cannot open any projects ;)

If you check your file permissions and antivirus client settings against [our permissions guide](https://help.gamemaker.io/hc/en-us/articles/360022953052-User-Permissions-and-Internet-Access-Required-by-GameMaker#h_01GSTA3RHQC16XMB3EG8CD1ED9) and also see if you can restore the missing executable from your AV client (or download the runtimes again), then all should be fine for you also.
