### ISSUE TITLE
`val[$""]` (empty key) causes a GMAC exception

### ISSUE THREAD

**Issue by YellowAfterlife** [YoYoGames/GameMaker-Bugs#5167]
### Description

Attempting to read or write an empty key using the `[$]` accessor causes compiler to fail with the following

```
Final Compile...System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at GMAssetCompiler.GMLCompile.IsValidVariableName(String _name)
   at GMAssetCompiler.GMLCompile.OptimizeVariableStructGet(GMLToken& _tok)
   at GMAssetCompiler.GMLCompile.OptimizeTree(GMLToken _tok, Boolean fLHS, Boolean fPartOfDot)
   at GMAssetCompiler.GMLCompile.OptimizeTree(GMLToken _tok, Boolean fLHS, Boolean fPartOfDot)
   at GMAssetCompiler.GMLCompile.OptimizeTree(GMLToken _tok, Boolean fLHS, Boolean fPartOfDot)
   at GMAssetCompiler.GMLCompile.OptimizeTree(GMLToken _tok, Boolean fLHS, Boolean fPartOfDot)
   at GMAssetCompiler.GMLCompile.OptimizeTree(GMLToken _tok, Boolean fLHS, Boolean fPartOfDot)
   at GMAssetCompiler.GMLCompile.OptimizeTree(GMLToken _tok, Boolean fLHS, Boolean fPartOfDot)
   at GMAssetCompiler.GMLCompile.OptimizeTree(GMLToken _tok, Boolean fLHS, Boolean fPartOfDot)
   at GMAssetCompiler.WADSaver`1.CompileAllCode(GMAssets _assets)
   at GMAssetCompiler.IFFSaver.Save(GMAssets _assets, String _name)
   at GMAssetCompiler.Program.CompileProject(GMAssets _file)
   at GMAssetCompiler.Program.Reentry(String[] _args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Igor.Program.ExecuteAssetCompiler(String _args)
   at Igor.WindowsBuilder.Compile(Boolean _exe)
   at Igor.WindowsBuilder.Deploy(Boolean _exe)
   at Igor.WindowsBuilder.Run()
```

```gml
function scr_test(){
	var q = {};
	var v = q[$""];
	q[$""] = v;
}
```

[zip.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14822001/zip.zip)

### Steps To Reproduce

1. Start GameMaker
2. Open the example project
3. Attempt to run the game
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.2.0 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Which platform(s) are you having trouble building this project for?

Windows

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by Emc1923** [comment]
Verified as of  IDE v2024.400.0.533  Runtime v2024.400.0.552
