### ISSUE TITLE
Code Editor 2: GM unstable when dragging a split-screen note back in to one

### ISSUE THREAD

**Issue by sihammill** [YoYoGames/GameMaker-Bugs#5214]
### Description

When a note asset is split in to two editors, dragging the right editor in to the left editor causes the IDE to become unstable.
See below video.

Error Log:
```
[16:17:47:773(2a4c)] Exception in YoYoStudio.GUI.Gadgets.TextEditor2.DocumentWorkspace+<>c__DisplayClass8_1,Void <AddPanel>b__1() : System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
 at System.Collections.Generic.List`1.RemoveAt(Int32 index)
 at YoYoStudio.GUI.Gadgets.Grid.RemoveColumn(Int32 _index)
 at YoYoStudio.GUI.Gadgets.TextEditor2.DocumentWorkspace.<>c__DisplayClass8_1.<AddPanel>b__1()
 at WeakDelegate(Object , Object[] )
 at YoYoStudio.Core.Utils.WeakDelegate`1.Invoke(Object[] _args) in D:\a\YoYoStudio\YoYoStudio\YoYoStudio\IDE\Core\Utils\WeakDelegate.cs:line 184
[16:17:47:779(2a4c)] Fatal Error! 'IDE.OnWeakDelegateException - Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')'
[16:17:47:784(2a4c)] at System.Collections.Generic.List`1.RemoveAt(Int32 index)
 at YoYoStudio.GUI.Gadgets.Grid.RemoveColumn(Int32 _index)
 at YoYoStudio.GUI.Gadgets.TextEditor2.DocumentWorkspace.<>c__DisplayClass8_1.<AddPanel>b__1()
 at WeakDelegate(Object , Object[] )
 at YoYoStudio.Core.Utils.WeakDelegate`1.Invoke(Object[] _args) in D:\a\YoYoStudio\YoYoStudio\YoYoStudio\IDE\Core\Utils\WeakDelegate.cs:line 184
[16:17:47:790(2a4c)] ####################################
[16:17:47:796(2a4c)] Break in FatalErrorWarning (IDE:4486)
[16:17:47:802(2a4c)] ####################################
```

https://github.com/YoYoGames/YoYoStudio/assets/101252654/4aaebe5d-22dc-4ec4-a9c6-04522d5cd0e5

Linked to bug: https://github.com/YoYoGames/YoYoStudio/issues/9435

### Steps To Reproduce

1. Start GameMaker
2. Create a note
3. Expand the editor
4. Drag the preview slide back out as per the attached video
5. Drag the right editor in to the left editor
6. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

IDE v2024.400.0.526  Runtime v2024.400.0.547

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

No

### ui.log File

- [ ] I have attached my ui.log file

### Sample .yyz File

- [ ] I have attached a small sample project

**Comment by zreedy** [comment]
This has long been fixed.
