### ISSUE TITLE
GameMaker becomes unstable when unchecking texture group platform exports

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#5333]
### Description
The UI log message seems fairly straightforward. I don't think anything's actually wrong with the IDE in this case (there's no project corruption or anything in source control) so I probably won't  bother to actually save my changes and exit.

![image](https://github.com/YoYoGames/GameMaker-Bugs/assets/7087495/847a7ed0-c2c7-4c52-a21d-aba3cdca7201)

        [21:32:25:986(e0ee)] DoUndoableAction: 'Unset Ubuntu_YYC as target'
        [21:32:25:986(e0ee)] Fatal Error! 'UndoManager::DoUndoableAction - ConvertToJsonValue: Type not supported for property'
        [21:32:25:987(e0ee)]    at YoYoStudio.Resources.ResourceBase.ConvertToJsonValue[T](GMProject sourceGMProject, T value) in D:\a\YoYoStudio\YoYoStudio\YoYoStudio\IDE\Core\CoreResources\CoreResources\ResourceBase.cs:line 1306
           at YoYoStudio.Resources.GMBaseGroup.set_targets(eTargetPlatforms value) in D:\a\YoYoStudio\YoYoStudio\YoYoStudio\IDE\Core\CoreResources\CoreResources\Resources\GMBaseGroup.cs:line 20
           at YoYoStudio.Core.Utils.UndoManager.DoUndoableAction(String _description, Object _objectsToTrack, Action _actionDelegate, Object _contextOverride)
        [21:32:25:987(e0ee)] ####################################
        [21:32:25:987(e0ee)] Break in FatalErrorWarning (IDE:4482)
        [21:32:25:988(e0ee)] ####################################

This doesn't seem to be a problem in monthly.

### Steps To Reproduce
Open the texture groups window, check/uncheck some boxes

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.533 Runtime v2024.400.0.552

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[d755f593-59f3-4e69-9733-99305b69f599](https://api.gamemaker.io/api/github/downloads/d755f593-59f3-4e69-9733-99305b69f599)

**Comment by DragoniteSpam** [comment]
> I don't think anything's actually wrong with the IDE in this case (there's no project corruption or anything in source control)

though with that said it's not actually saving the changes (although i can set the targets mask to 0 manually ¯\_(ツ)_/¯)

**Comment by stuckie** [comment]
[BLANK GAME_1.zip](https://github.com/YoYoGames/GameMaker-Bugs/files/14904516/BLANK.GAME_1.zip)

Repro Steps:
Create a new project ( or open attached )
Create a new config and set it to active
Tools ->Texture Groups
Create a new texture group
Select the new texture group
Click off a platform and see the unstable message.


This is why we ask for a project and full reproduction steps, as we could not get this to reproduce originally, until we started looking into other ways it could trigger.

**Comment by Emc1923** [comment]
Verified fixed as of  IDE v2024.400.0.539  Runtime v2024.400.0.558.
