### ISSUE TITLE
Linux Igor: cannot execute Compiler Scripts

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GameMaker-Bugs#5355]
### Description
When building the sample project that uses a pre_build_step.sh at the project root, build would fail with the error:

```
bash -l -c "! [[ -x '/home/shi/gms2-compile/sandbox/gms-compile-demo/demo_yyp/pre_build_step.sh' ]] && chmod +x '/home/shi/gms2-compile/sandbox/gms-compile-demo/demo_yyp/pre_build_step.sh'; exit 0"


bash DONE (0)
bash -l -c "[[ $(file '/home/shi/gms2-compile/sandbox/gms-compile-demo/demo_yyp/pre_build_step.sh') == *CRLF* ]] && sed -i -e 's/\r$//' '/home/shi/gms2-compile/sandbox/gms-compile-demo/demo_yyp/pre_build_step.sh'; exit 0"


bash DONE (0)
/home/shi/gms2-compile/sandbox/gms-compile-demo/demo_yyp/pre_build_step.sh 
System.ComponentModel.Win32Exception (8): An error occurred trying to start process '/home/shi/gms2-compile/sandbox/gms-compile-demo/demo_yyp/pre_build_step.sh' with working directory '/home/shi/gms2-compile/sandbox/out'. Exec format error
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Igor.Command.ExecuteCommandSync(String _command, String _args, Boolean _fail_on_error, String _cwd, YYDictionary`2 _env, Boolean as_admin, String timingKey, Boolean _fQuiet)
   at Igor.Utils.ExecUserCmdStep(String fileName)
   at Igor.Utils.RunUserCmdStep(String _basename)
   at Igor.BaseTargetBuilder.PreBuildStep()
   at Igor.AndroidBuilder.Compile(Boolean _exe)
   at Igor.AndroidBuilder.Package()
Igor complete.
```

### Steps To Reproduce
1. Using the Linux Igor, compile the sample project for android export
2. Observe the build failure

### Which version of GameMaker are you reporting this issue for?
IDE v2024.400.0.526 Runtime v2024.400.0.547

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22000.0

[6a6ce82c-d380-4aa0-a5d6-bf1a1db1d1b2](https://api.gamemaker.io/api/github/downloads/6a6ce82c-d380-4aa0-a5d6-bf1a1db1d1b2)

**Comment by DiasFranciscoA** [comment]
@shichen85 thank you for the report on this, to be clean you are Linux IDE? Because the Operative system marked in the issue is "Windows 10.0.22000.0". I assume that was a typo?

**Comment by DiasFranciscoA** [comment]
So from what could be checked the included script is not a value bash script file and so it cannot be executed which is the error you are experiencing.

> [!TIP] 
> The most common cause of this error when executing shell scripts is the absence of a shebang (#!) at the beginning of the script. The shebang line tells the operating system which interpreter to use to execute the file. For a shell script, this line is typically `#!/bin/bash` (use in the official scripts) or `#!/bin/sh`.
>
> ### Solution
> 
> Ensure your script (ie.: `pre_build_step.sh`) starts with a shebang line pointing to the correct interpreter. For example:
>
>```sh
>#!/bin/bash
># your script commands follow
>```

**Comment by shichen85** [comment]
I see. Thank you for the solution. Adding the `#!/bin/bash` line resolves this issue.
