### ISSUE TITLE
Start Up: Crash to desktop when opening a source control project

### ISSUE THREAD

**Issue by Emc1923** [YoYoGames/GameMaker-Bugs#5795]
### Description

When opening a source control project after changing accounts, Beta IDE v2024.400.0.556 Beta Runtime v2024.400.0.571 crashed to desktop with the following error in the log:

```
[09:37:47:938(94ec)] IDE Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at A.c.b.A(String )
   at A.D.A(Object , Object )
   at YoYoStudio.FileAPI.FileRequest.ResultOperation() in D:\a\YoYoStudio\YoYoStudio\YoYoStudio\IDE\Core\Utils\FileAPI\FileRequest.cs:line 119
   at YoYoStudio.Core.Utils.FileAPI.ThreadedAsyncQueue.DispatchCompletedRequests(Int32 _amount) in D:\a\YoYoStudio\YoYoStudio\YoYoStudio\IDE\Core\Utils\FileAPI\ThreadedAsyncQueue.cs:line 186
   at YoYoStudio.FileAPI.FileSystem_Local_NonAsync.Tick(Boolean _applicationIsBackground) in D:\a\YoYoStudio\YoYoStudio\YoYoStudio\IDE\Core\Utils\FileAPI\FileSystem_Local_NonAsync.cs:line 59
   at YoYoStudio.IDE.Tick()
   at YoYoStudio.IDE.Run()
   at YoYoStudio.IDE.Execute(String[] _args, Int32 _initialWidth, Int32 _initialHeight)
[09:37:47:939(94ec)] --------------------------------------------------------------------------------
[09:37:47:939(94ec)] ####################################
[09:37:47:939(94ec)] Break in FatalErrorWarning (IDE:4482)
[09:37:47:940(94ec)] ####################################
```

### Steps To Reproduce

1. Start GameMaker
2. Modify a source control project with an account and save changes
3. Log out and log in with a different account (note, I changed from an user account to one with internal dev enabled)
4. Open the project
5. Potentially observe a crash
[ui.log](https://github.com/YoYoGames/GameMaker-Bugs/files/15246305/ui.log)

Project link: https://github.com/yoyo-qa/platformer

### How reliably can you recreate this issue using your steps above?

Rarely

### Which version of GameMaker are you reporting this issue for?

2024.400 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by stuckie** [comment]
This should now be fixed!

**Comment by Emc1923** [comment]
Closed as per comment, thanks
