### ISSUE TITLE
IDE log contains lot of errors caused by connecting to yandex.ru results in captcha challenge - `Unable to reach site https://www.yandex.ru`

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#5810]
### Description

To check if internet is alive, gamemaker opens in background google, yandex and baidu. However, when accessing `https://www.yandex.ru` requests may get redirected to `https://dzen.ru/showcaptcha` resulting in `302 (Moved temporarily)` HTTP status. This would cause IDE to report it as an error (in fact - even if it's redirect, that could be count in as "online" - as giving *any* HTTP status means server is alive).

```
[13:21:11:773(f4df)] InternalCheckForInternetConnection :: Unable to reach site https://www.yandex.ru
[13:21:11:774(f4df)] System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 302 (Moved temporarily).)
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 302 (Moved temporarily).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at YoYoStudio.Core.Utils.HttpUtil.<>c__DisplayClass52_0.<InternalCheckForInternetConnection>b__1(String s, ParallelLoopState _state) in D:\a\YoYoStudio\YoYoStudio\YoYoStudio\IDE\Core\Utils\HttpUtil.cs:line 928
[13:21:11:775(f4df)] Inner exception: 
[13:21:11:775(f4df)] Response status code does not indicate success: 302 (Moved temporarily).
```

### Steps To Reproduce

1. Open `ui.log` for GameMaker, and notice, that becase of captcha challenge on yandex.ru, there's lot of reports of `System.AggregateException` every 10-15 minutes.

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.4.0 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

None

**Comment by rwkay** [comment]
Fixed in 2024.6 - handles Http status codes (a protocol error is still good as the internet is working) - only an actual exception will classify the URL as down. (this should be limited to timeouts and hardware / transport errors)

**Comment by rwkay** [comment]
Closing as above

**Comment by gnysek** [comment]
Thanks, that's perfect solution.

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.600.0.557  Runtime v2024.600.0.572

**Comment by YYDan** [comment]
Note that https://github.com/YoYoGames/GameMaker-Bugs/issues/6499 shows that if someone is IN Russia, then they still get their 2024.6.0 ui.log filled with exceptions (as is mentioned above would still be the case if a transport error occurs).

```
[14:05:26:355(bcaa)] InternalCheckForInternetConnection :: Unable to reach site https://www.yandex.ru
[14:05:26:373(bcaa)] System.Net.Http.HttpRequestException: Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение. (www.yandex.ru:443)
 ---> System.Net.Sockets.SocketException (10061): Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение.
```

For some reason, copying that text out directly out of the original ui.log and pasting it into Google Translate changes it to Icelandic and gives
"Proceedings of the establishment, T.K. this is the case with the Russian Federation"

Whereas changing the encoding of the file and then setting Google Translate to be fixed on Russian gives the _very_ different, but also more expected:
"The connection has not been established because the destination computer rejected the connection request"

;)

**Comment by rwkay** [comment]
This would be expected as the fix for this bug was that the return code was a non-error and being handled as an exception.

This is an actual error and being reported as such...

**Comment by gnysek** [comment]
Yeah, issue here was that server returned answer, so no matter if it's 404, 302 or whatever it means network is up, and that doesn't need to throw an error.
