### ISSUE TITLE
Building Projects: Igor error "value cannot be null" when running the attached project in 2024.600 betas

### ISSUE THREAD

**Issue by DragoniteSpam** [YoYoGames/GameMaker-Bugs#5962]
### Description
Duck game runs fine on 2024.4, but fails to build on all of the 600 betas

There appears to be something wrong with the asset compiler, but the crash doesn't produce anything I can read:

```
collapsing enums.
Final Compile...System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'format')
   at System.ArgumentNullException.Throw(String paramName)
   at System.String.FormatHelper(IFormatProvider provider, String format, ReadOnlySpan`1 args)
   at System.String.Format(String format, Object[] args)
   at GMAssetCompiler.GMLCompile.OptimizeStringCall(GMLToken& _tok)
   at GMAssetCompiler.GMLCompile.OptimizeFunction(GMLToken& _tok)
   at GMAssetCompiler.GMLCompile.OptimizeTree(GMLToken _tok, Boolean fLHS, Boolean fPartOfDot)
   at GMAssetCompiler.GMLCompile.OptimizeTree(GMLToken _tok, Boolean fLHS, Boolean fPartOfDot)
   at GMAssetCompiler.GMLCompile.OptimizeTree(GMLToken _tok, Boolean fLHS, Boolean fPartOfDot)
   at GMAssetCompiler.GMLCompile.OptimizeTree(GMLToken _tok, Boolean fLHS, Boolean fPartOfDot)
   at GMAssetCompiler.GMLCompile.OptimizeTree(GMLToken _tok, Boolean fLHS, Boolean fPartOfDot)
   at GMAssetCompiler.GMLCompile.OptimizeTree(GMLToken _tok, Boolean fLHS, Boolean fPartOfDot)
   at GMAssetCompiler.GMLCompile.OptimizeTree(GMLToken _tok, Boolean fLHS, Boolean fPartOfDot)
   at GMAssetCompiler.GMLCompile.OptimizeTree(GMLToken _tok, Boolean fLHS, Boolean fPartOfDot)
   at GMAssetCompiler.GMLCompile.OptimizeTree(GMLToken _tok, Boolean fLHS, Boolean fPartOfDot)
   at GMAssetCompiler.GMLCompile.OptimizeTree(GMLToken _tok, Boolean fLHS, Boolean fPartOfDot)
   at GMAssetCompiler.GMLCompile.OptimizeTree(GMLToken _tok, Boolean fLHS, Boolean fPartOfDot)
   at GMAssetCompiler.GMLCompile.OptimizeTree(GMLToken _tok, Boolean fLHS, Boolean fPartOfDot)
   at GMAssetCompiler.WADSaver`1.CompileAllCode(GMAssets _assets)
   at GMAssetCompiler.IFFSaver.Save(GMAssets _assets, String _name)
   at GMAssetCompiler.Program.CompileProject(GMAssets _file)
   at GMAssetCompiler.Program.Reentry(String[] _args)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Igor.Program.ExecuteAssetCompiler(String _args)
   at Igor.WindowsBuilder.Compile(Boolean _exe)
   at Igor.WindowsBuilder.Deploy(Boolean _exe)
   at Igor.WindowsBuilder.Run()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
Igor complete.
```

### Steps To Reproduce
Run the game (any config)

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.560 Runtime v2024.600.0.577

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[19d47a79-93f1-4564-a6b7-bf21ea396708](https://api.gamemaker.io/api/github/downloads/19d47a79-93f1-4564-a6b7-bf21ea396708)

**Comment by Emc1923** [comment]
Verified fixed in  IDE v2024.600.0.563  Runtime v2024.600.0.582
