### ISSUE TITLE
Building Projects: [Ubuntu] Unable to build projects if using Ubuntu IDE on Ubuntu LTS 24.04

### ISSUE THREAD

**Issue by Emc1923** [YoYoGames/GameMaker-Bugs#6015]
### Description

When building for newest Ubuntu LTS 24.04 any project will fail to build with the following error:

```
/bin/bash DONE (0)
/bin/bash -c 'unshare -mUprf sh -c '\''mount -o bind "$1" "$2/tmp/" && PATH="$PATH:/usr/local/sbin:/usr/sbin:/sbin" NO_STRIP=1 chroot "$2" /bin/sh -c "export PATH=/usr/bin:/bin:/tmp/squashfs-root/usr/bin && cd /tmp/ && linuxdeploy --appdir=AppDir/"'\''  -- /home/emvm2/GameMakerStudio2/vm/BLANK_GAME /opt/steam-runtime'
unshare: write failed /proc/self/uid_map: Operation not permitted


System.Exception: command 'unshare -mUprf sh -c 'mount -o bind "$1" "$2/tmp/" && PATH="$PATH:/usr/local/sbin:/usr/sbin:/sbin" NO_STRIP=1 chroot "$2" /bin/sh -c "export PATH=/usr/bin:/bin:/tmp/squashfs-root/usr/bin && cd /tmp/ && linuxdeploy --appdir=AppDir/"'  -- /home/emvm2/GameMakerStudio2/vm/BLANK_GAME /opt/steam-runtime' failed with exit status 1
   at Igor.LinuxBuilder.plink_async(String command, Boolean fail_on_error)
   at Igor.LinuxBuilder.BuildAppImage(String work_dir, String exe_path, String assets_zip_path, String projectName, Boolean package)
   at Igor.LinuxBuilder.Run()
```

[Ubuntu24.04.txt](https://github.com/YoYoGames/GameMaker/files/15234518/Ubuntu24.04.txt)

### Steps To Reproduce

1. Start GameMaker on Ubuntu 24.04
2. Create open any project
3. Attempt to run for Ubuntu VM/YYC
4. See the issue
[Ubuntu_package.zip](https://github.com/YoYoGames/GameMaker/files/15234537/Ubuntu_package.zip)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Beta IDE v2024.400.0.556 Beta Runtime v2024.400.0.571

### Which platform(s) are you having trouble building this project for?

Ubuntu

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package/Logs Attached?

- [X] I have attached my evidence

### Sample Project Added?

- [X] I have included a small sample project

**Comment by gurpreetsinghmatharoo** [comment]
This is now documented on the Setting Up For Ubuntu guide: https://help.gamemaker.io/hc/en-us/articles/235186168-Setting-Up-For-Ubuntu

**Comment by Emc1923** [comment]
Closing as per comment above.

**Comment by BihartGames** [comment]
I have the same issue with compiling and running games on ubuntu using the latest version of Game Maker Studio 2 and the latest Beta version for ubuntu. I have also tried using the command with no luck:

sudo sysctl kernel.apparmor_restrict_unprivileged_userns=0

even after adding to the /etc/sysctl.conf file still with no luck:

kernel.apparmor_restrict_unprivileged_userns=0

I am currently running Ubuntu 24.10 if this helps anyone.

**Comment by jiimjaam** [comment]
> I have the same issue with compiling and running games on ubuntu using the latest version of Game Maker Studio 2 and the latest Beta version for ubuntu. I have also tried using the command with no luck:
> 
> sudo sysctl kernel.apparmor_restrict_unprivileged_userns=0
> 
> even after adding to the /etc/sysctl.conf file still with no luck:
> 
> kernel.apparmor_restrict_unprivileged_userns=0
> 
> I am currently running Ubuntu 24.10 if this helps anyone.

I'm also having this issue and it's driving me crazy. I made sure to disable the problematic AppArmor functionality and have verified that my Ubuntu installation has all the required dependencies countless times. Does anyone have any idea what I'm doing wrong? lol

**Comment by jiimjaam** [comment]
Following up on my last comment: It seems that when GameMaker compiles to Ubuntu it uses two terminal commands, "zip" and "unzip," that have to be manually install using apt. After doing this my game compiled just fine!

**Comment by stuckie** [comment]
They're not in a default install anymore?
Just to verify here, were you using the IDE on Ubuntu and building on the same machine, or were you building on a remote machine?
I ask because the Ubuntu .deb does have zip and unzip in it's dependencies list, so apt should have ensured they were there.

**Comment by omriiii** [comment]
Also running into this issue!

Build fails here 
```
/bin/bash DONE (0)
/bin/bash -c 'unshare -mUprf sh -c '\''mount -o bind "$1" "$2/tmp/" && PATH="$PATH:/usr/local/sbin:/usr/sbin:/sbin" NO_STRIP=1 chroot "$2" /bin/sh -c "export PATH=/usr/bin:/bin:/tmp/squashfs-root/usr/bin && cd /tmp/ && linuxdeploy --appdir=AppDir/"'\''  -- /home/omri/GameMakerStudio2/vm/Showdown /opt/steam-runtime'
unshare: write failed /proc/self/uid_map: Operation not permitted
```

Running Ubuntu 24.04 LTS,
IDE Version: Beta 2024.1400.0.826
Current Runtime: Beta 2024.1400.0.822
