### ISSUE TITLE
Sprite Editor: Nine-slice Preview Non-Functional / Crashing in 600.0.571

### ISSUE THREAD

**Issue by Hyomoto** [YoYoGames/GameMaker-Bugs#6220]
### Description
In the latest IDE update the nine-slice resize preview no longer allows dragging the shape edges to preview the results.

### Steps To Reproduce
Make a sprite, enable nine slice, try to drag edges of preview.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.600.0.571 Runtime v2024.600.0.597

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[710f0f98-f7ef-4851-8c89-ed399f1eceea](https://api.gamemaker.io/api/github/downloads/710f0f98-f7ef-4851-8c89-ed399f1eceea)

**Comment by scott-dunbar** [comment]
Its' actually crashing (though not showing the user the Unstable Dialog, it is showing it to me)

[10:29:44:420(1dba)] Exception in YoYoStudio.GUI.Gadgets.Sequences.Canvas.SequenceCanvas,Void Canvas_MouseMove(Single, Single, YoYoStudio.Core.Utils.eMouseButtons) :    System.NullReferenceException: Object reference not set to an instance of an object.
   at YoYoStudio.GUI.Gadgets.Sequences.Canvas.SequenceCanvas.ScaleItemsByBoundingBox(Single _childX, Single _childY, eMouseButtons _buttons)
   at YoYoStudio.GUI.Gadgets.Sequences.Canvas.SequenceCanvas.ExecuteMouseAction(Single _childX, Single _childY, eMouseButtons _buttons)
   at YoYoStudio.GUI.Gadgets.Sequences.Canvas.SequenceCanvas.Canvas_MouseMove(Single _mousex, Single _mousey, eMouseButtons _buttons)
   at WeakDelegate(Object, Object[])
   at YoYoStudio.Core.Utils.WeakDelegate`1.Invoke(Object[] _args)

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.600.0.577  Runtime v2024.600.0.603
