### ISSUE TITLE
IDE: Crash when bringing up search and replace with `Ctrl+Shift+F`

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#6584]
### Description
I had IDE opened for 3 days, and at some point, when doing (another) search using `Ctrl+Shift+F` while window just vanished.

There's not much more I can say about that (I probably had some text selected).

There's an exception in ui.log I found (what's fun - it was already in packed file - probably because this session was 2 days old):

```
[14:56:13:583(40a0)] IDE Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at YoYoStudio.Core.Utils.ListExtensions.ForEach[T](IEnumerable`1 ie, Action`1 action)
   at YoYoStudio.Plugins.MiscPlugins.SearchReplaceDialog.Dispose(Boolean disposing)
   at YoYoStudio.Plugins.MiscPlugins.SearchReplaceDialog.Dispose()
   at YoYoStudio.Plugins.ResourceEditorManager.DeactivateModule(Type _type, IProvideIDE _module)
   at YoYoStudio.Plugins.MiscPlugins.SearchReplaceDialog.Initialise(ModulePackage _ide)
   at YoYoStudio.Plugins.ResourceEditorManager.ActivateModule(Type _type, Object[] _parameters)
   at YoYoStudio.Plugins.Command.execute_object(String _command, Object _focus, Object[] paramaters)
   at YoYoStudio.Plugins.Command.execute_object(String _command, Object _focus, Object[] paramaters)
   at YoYoStudio.Plugins.MiscPlugins.MiscPlugin.<>c__DisplayClass4_0.<Initialise>b__4()
   at YoYoStudio.KeyboardShortcuts.KeyboardShortcutManager.ExecuteShortcut(GUIBase focusTarget, Key key, KeyModifiers modifiers)
   at YoYoStudio.GUI.KeyboardManager.HandleKeyEvent(KeyEventPacket _evnt, GUIBase _gadgetInFocus)
   at YoYoStudio.GUI.KeyboardManager.DispatchEvents(Desktop desktop, GUIBase gadgetInFocus, Boolean dragging, Boolean blocking)
   at YoYoStudio.IDE.Run()
   at YoYoStudio.IDE.Execute(String[] _args, Int32 _initialWidth, Int32 _initialHeight)


[14:56:13:584(40a0)] Break in FatalErrorWarning (IDE:4468)
```

### Which version of GameMaker are you reporting this issue for?
IDE v2024.800.0.586 Runtime v2024.800.0.611

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

Repro:

1. Open any project
2. Press Ctrl+Shift+F to open Search and Replace
3. While that window is open, press Ctrl+Shift+F again
4. Observe crash to desktop

[e9ba1150-f142-4168-a952-34965b062acf](https://api.gamemaker.io/api/github/downloads/e9ba1150-f142-4168-a952-34965b062acf)

**Comment by gnysek** [comment]
Sorry that I have no more info on this one.

**Comment by scott-dunbar** [comment]
Issue occurs when opening search and replace with Ctrl+Shift+F while the Search and Replace window is already opened. 

Added repro steps to description

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.800.0.593  Runtime v2024.800.0.617
