### ISSUE TITLE
Startup: [Mac IDE] GM crash during first start after installing a new IDE because the runtime install path cannot be found

### ISSUE THREAD

**Issue by SamTHodson** [YoYoGames/GameMaker-Bugs#6863]
### Description

In the latest GM Beta on Mac, after finishing installing, the IDE will crash when attempting to automatically open.

![image](https://github.com/user-attachments/assets/6816c17c-9e61-473d-9ae9-bdb461de3dac)

```
[10:07:27:559(9ffb)] --------------------------------------------------------------------------------
[10:07:27:559(9ffb)] Unhandled Exception: System.IO.DirectoryNotFoundException
[10:07:27:559(9ffb)] Exception message: Could not find a part of the path '/Users/Shared/GameMakerStudio2-Beta/Cache/runtimes/runtime-2024.800.0.620/download'.
[10:07:27:567(9ffb)] Exception stack:    at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at A.d.A(String, List`1)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
[10:07:27:567(9ffb)] --------------------------------------------------------------------------------

``` 

Tested using IDE v2024.800.0.596  Runtime v2024.800.0.620 on an M2 Mac Mini.

[Contact Us Package](https://drive.google.com/file/d/15MlMvZc_ZCS8PfjeVGpozINjOGtqbpuP/view?usp=sharing)

### Steps To Reproduce

1. Install GameMaker Beta on Mac
2. After the installtion has finished, wait for GM to automatically startup
3. Observe the crash report

Repro: 100%

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.800 (Betas)

### Which operating system(s) are you seeing the problem on?

macOS Sonoma

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by SmithTom6304** [comment]
This was crashing due to iterating over files in a folder that didn't exist when copying rss files to the runtime install location.
For now we just skip the copy operation if the folder doesn't exist.
It's possible that the folder _should_ exist though - I'll reach out to Russell once he's back from holiday as he recently implemented this rss file copy operation.

**Comment by Emc1923** [comment]
Verified that the crash does no longer happen when installing  IDE v2024.800.0.599  Runtime v2024.800.0.622
