### ISSUE TITLE
Building Projects: Build fails if an in-game only effect is used due to the error "it, or its linked prefab libraries, need upgrading"

### ISSUE THREAD

**Issue by SamTHodson** [YoYoGames/GameMaker-Bugs#6865]
### Description

In the latest GM betas, building a project which uses an in-game only effect (Gaussian Blur, Glow, etc.) will cause the build to fail due to the following error:

```
C:\ProgramData/GameMakerStudio2-Beta/Cache/runtimes\runtime-2024.800.0.620\bin\FiltersAndEffects\_effect_gaussian_blur\project\_effect_gaussian_blur.yyp: Cannot load this new project because it, or its linked prefab libraries, need upgrading.
Core Resources : Info - C:\ProgramData/GameMakerStudio2-Beta/Cache/runtimes\runtime-2024.800.0.620\bin\FiltersAndEffects\_effect_gaussian_blur\project\_effect_gaussian_blur.yyp: Cannot load this new project because it, or its linked prefab libraries, need upgrading.
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at GMAssetCompiler.Loader.<>c__DisplayClass6_0.<AddGMS2ProjToAssets>b__2(ResourceBase _project, Exception _serialiseException)
   at YoYoStudio.Resources.ProjectInfo.<>c__DisplayClass24_0.<InternalLoadProject>g__handleFailure|4(Exception exception)
   at YoYoStudio.Resources.ProjectInfo.InternalLoadProject(String _path, Boolean _setActive, OnLoadSaveSuccess _onSuccess, OnLoadSaveUpdate _onUpdate, OnLoadSaveFailed _onFailed, Func`2 _shouldShowErrorFunc, Boolean _allowReversioning)
   at YoYoStudio.Resources.ProjectInfo.LoadProject(String _path, Boolean _setActive, OnLoadSaveSuccess _onSuccess, OnLoadSaveUpdate _onUpdate, OnLoadSaveFailed _onFailed, Func`2 _shouldShowErrorFunc, Boolean _allowReversioning)
   at GMAssetCompiler.Loader.AddGMS2ProjToAssets(String _filename, GMAssets _assets, Boolean _isFilter)
   at GMAssetCompiler.Loader.MergeInFiltersAndEffects(GMAssets _assets)
   at GMAssetCompiler.Loader.Load(String _name)
   at GMAssetCompiler.Program.GetAssetsFile(List`1 _args)
   at GMAssetCompiler.Program.Main(String[] _args)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Igor.Program.ExecuteAssetCompiler(String _args)
   at Igor.Program.SetupBuildEnv(String _options, String _project, String _runtimeLocation, String _cache, String _temp, String _user, String _outputFilename, String _targetFilename, String _debuggerPort, Boolean _launchPackage)
   at Igor.Program.Main(String[] args)
``` 

Tested using IDE v2024.800.0.597  Runtime v2024.800.0.620

Contact Us Package

### Steps To Reproduce

1. Start GameMaker
2. Create a project
3. Open Room1
4. Add an Effects layer and change the Effect Type to be one that is "in-game only" (e.g. Glow)
5. Run the project
6. Observe the issue

Repro: 100%

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.800 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11, macOS Sonoma

### Which platform(s) are you having trouble building this project for?

Windows, macOS

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by SamTHodson** [comment]
Verified fixed in IDE v2024.800.0.604  Runtime v2024.800.0.627
