### ISSUE TITLE
IDE: picking GMRT build for gx.games target crashes on compile

### ISSUE THREAD

**Issue by thennothinghappened** [YoYoGames/GameMaker-Bugs#6982]
### Description

As the title suggests, compiling with the GMRT output on the gx target instantly crashes the IDE:

https://github.com/GMExternal/NewRuntimeBeta/assets/35243139/93c7c109-3803-4aa2-9960-0d9dc4ef88b8

Beta IDE v2024.200.0.505 Beta Runtime v2024.200.0.523

[ui.log](https://github.com/GMExternal/NewRuntimeBeta/files/14468102/ui.log)
...and relevant error line:
```
[15:49:11:6(c8a4)] IDE Exception: System.Collections.Generic.KeyNotFoundException: The given key 'cmake' was not present in the dictionary.
   at YoYoStudio.Plugins.MiscPlugins.Build.Common.<>c__DisplayClass68_0.<WriteToCronusBuildFile>b__0(Object _create_result, Object _create_userData) in D:\a\YoYoStudio\YoYoStudio\YoYoStudio\IDE\Plugins\MiscPlugins\Build\Common.cs:line 745
   at YoYoStudio.FileAPI.FileSystem_Local_NonAsync.<>c__DisplayClass30_0.<CreateDirectory>b__2() in D:\a\YoYoStudio\YoYoStudio\YoYoStudio\IDE\Core\Utils\FileAPI\FileSystem_Local_NonAsync.cs:line 774
   at YoYoStudio.FileAPI.FileRequest.ResultOperation() in D:\a\YoYoStudio\YoYoStudio\YoYoStudio\IDE\Core\Utils\FileAPI\FileRequest.cs:line 119
   at YoYoStudio.Core.Utils.FileAPI.ThreadedAsyncQueue.DispatchCompletedRequests(Int32 _amount) in D:\a\YoYoStudio\YoYoStudio\YoYoStudio\IDE\Core\Utils\FileAPI\ThreadedAsyncQueue.cs:line 186
   at YoYoStudio.FileAPI.FileSystem_Local_NonAsync.Tick(Boolean _applicationIsBackground) in D:\a\YoYoStudio\YoYoStudio\YoYoStudio\IDE\Core\Utils\FileAPI\FileSystem_Local_NonAsync.cs:line 59
   at YoYoStudio.IDE.Tick()
   at YoYoStudio.IDE.Run()
   at YoYoStudio.IDE.Execute(String[] _args, Int32 _initialWidth, Int32 _initialHeight)
```

### Steps To Reproduce

1. Start GameMaker
2. Switch to the `gx.games` target, and GMRT output
3. Press F5 to compile
4. IDE will crash immediately

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Other Release (Please put the exact version number in your Description)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### ui.log File

- [X] I have attached my ui.log file

### Sample .yyz File

- [ ] I have attached a small sample project

**Comment by scott-dunbar** [comment]
This no longer occurs but WASM as a target is still not quite functional
see
https://github.com/YoYoGames/GameMaker-Bugs/issues/11917
and
https://github.com/YoYoGames/GameMaker-Bugs/issues/11918 

However as this issue no longer occurs i will close it.   tested with 0.18.24 beta IDE 1400.882
