### ISSUE TITLE
Code Editor 2: IDE became unstable after deleting multiple lines of code

### ISSUE THREAD

**Issue by scott-dunbar** [YoYoGames/GameMaker-Bugs#7167]
### Description

After highlighting multiple lines and pressing Delete the IDE went unstable

Attempts to reproduce the issue have not yielded a reproduction

```
[13:50:08:999(d453)] Exception in YoYoStudio.GUI.Gadgets.TextEditor2.TextEditorPanel,Boolean TextEditorPanel_KeyDownEvent(Core.CoreOS.Input.Key, UInt32, Core.CoreOS.Input.KeyModifiers, Boolean) :    System.ArgumentOutOfRangeException: Index must be within the bounds of the List. (Parameter 'index')
   at System.Collections.Generic.List`1.Insert(Int32 index, T item)
   at YoYoStudio.TextEditor2.Text.TextBuffer.InsertLines(Int32 _line, IReadOnlyList`1 _lines)
   at YoYoStudio.TextEditor2.Text.TextBuffer.SplitLine(Int32 _line, Int32 _position)
   at YoYoStudio.GUI.Gadgets.TextEditor2.Components.DocumentManipulationComponent.<InsertLineBreak>b__25_0(CursorPosition position)
   at YoYoStudio.TextEditor2.Cursor.<ApplyEdit>g__DoOperation|39_0(CursorPosition position, <>c__DisplayClass39_0&)
   at YoYoStudio.TextEditor2.Cursor.ApplyEdit(Action`1 operation)
   at YoYoStudio.GUI.Gadgets.TextEditor2.Components.DocumentManipulationComponent.InsertLineBreak()
   at YoYoStudio.KeyboardShortcuts.Shortcut.Execute()
   at YoYoStudio.KeyboardShortcuts.OrderedShortcutCollection.TryExecute(Shortcut& executedShortcut)
   at YoYoStudio.GUI.Gadgets.TextEditor2.Components.DocumentManipulationComponent.OnKeyDown(Key key, UInt32 scanCode, KeyModifiers modifiers, Boolean repeat)
   at YoYoStudio.GUI.Gadgets.TextEditor2.TextEditorPanel.TextEditorPanel_KeyDownEvent(Key key, UInt32 scanCode, KeyModifiers modifiers, Boolean repeat)
   at WeakDelegate(Object, Object[])
   at YoYoStudio.Core.Utils.WeakDelegate`1.Invoke(Object[] _args)
[13:50:09:000(d453)] Fatal Error! 'IDE.OnWeakDelegateException - Index must be within the bounds of the List. (Parameter 'index')'
[13:50:09:000(d453)]    at System.Collections.Generic.List`1.Insert(Int32 index, T item)
   at YoYoStudio.TextEditor2.Text.TextBuffer.InsertLines(Int32 _line, IReadOnlyList`1 _lines)
   at YoYoStudio.TextEditor2.Text.TextBuffer.SplitLine(Int32 _line, Int32 _position)
   at YoYoStudio.GUI.Gadgets.TextEditor2.Components.DocumentManipulationComponent.<InsertLineBreak>b__25_0(CursorPosition position)
   at YoYoStudio.TextEditor2.Cursor.<ApplyEdit>g__DoOperation|39_0(CursorPosition position, <>c__DisplayClass39_0&)
   at YoYoStudio.TextEditor2.Cursor.ApplyEdit(Action`1 operation)
   at YoYoStudio.GUI.Gadgets.TextEditor2.Components.DocumentManipulationComponent.InsertLineBreak()
   at YoYoStudio.KeyboardShortcuts.Shortcut.Execute()
   at YoYoStudio.KeyboardShortcuts.OrderedShortcutCollection.TryExecute(Shortcut& executedShortcut)
   at YoYoStudio.GUI.Gadgets.TextEditor2.Components.DocumentManipulationComponent.OnKeyDown(Key key, UInt32 scanCode, KeyModifiers modifiers, Boolean repeat)
   at YoYoStudio.GUI.Gadgets.TextEditor2.TextEditorPanel.TextEditorPanel_KeyDownEvent(Key key, UInt32 scanCode, KeyModifiers modifiers, Boolean repeat)
   at WeakDelegate(Object, Object[])
   at YoYoStudio.Core.Utils.WeakDelegate`1.Invoke(Object[] _args)
[13:50:09:000(d453)] ####################################
[13:50:09:001(d453)] Break in FatalErrorWarning (IDE:4496)
[13:50:09:001(d453)] ####################################
```

### Steps To Reproduce

Unknown repro

1. Start GameMaker
2. Open a project
3. Open a code file
4. Select multiple lines of code
5. Press Delete on the keyboard
6. See the issue

### How reliably can you recreate this issue using your steps above?

Only Ever Happened Once

### Which version of GameMaker are you reporting this issue for?

2024.800 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

None

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by zreedy** [comment]
Unable to reproduce, but I added a safeguard to protect against indexing outside of the lines array in the crashing function.

**Comment by Emc1923** [comment]
Unable to repro as of  IDE v2024.1000.0.621  Runtime v2024.1000.0.647, closing.
