### ISSUE TITLE
Building Projects: Deleting Sprites used by Sequences via deleting its parent group in the AB causes builds to fail thereafter

### ISSUE THREAD

**Issue by ash0verride** [YoYoGames/GameMaker-Bugs#7169]
### Description
Deleting sprites from a project that were once used by a sequence will cause any build to fail, even when the sequence that required the sprites isn't being used actively but just exists in the files.

- May not actually be a bug but a huge inconvenience when working with a lot of different sequences that change.

Each individual sprite will be flagged as missing with its own exception:

```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\adouglas\Documents\GitHub\GM-25\GM-25\sprites\Hand_Holding\Hand_Holding.yy'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.ReadAllBytes(String path)
   at YoYoStudio.Resources.FileIO.<>c.<SetDefaultFileFunctions>b__58_6(String _path)

```
and then just the first one will be blamed again a second time when the build process fails:

```
Failed to load resource file 'C:/Users/adouglas/Documents/GitHub/GM-25/GM-25/sprites/Hand_Holding/Hand_Holding.yy'.
Core Resources : Info - Failed to load resource file 'C:/Users/adouglas/Documents/GitHub/GM-25/GM-25/sprites/Hand_Holding/Hand_Holding.yy'.
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at GMAssetCompiler.Loader.<>c__DisplayClass5_0.<LoadGMS2CreateAssets>b__2(ResourceBase _project, Exception _serialiseException)
   at YoYoStudio.Resources.ProjectInfo.<>c__DisplayClass24_0.<LoadProject>g__handleFailure|4(Exception exception)
   at YoYoStudio.Resources.ProjectInfo.LoadProject(String _path, Boolean _setActive, OnLoadSaveSuccess _onSuccess, OnLoadSaveUpdate _onUpdate, OnLoadSaveFailed _onFailed, Func`2 _shouldShowError)
   at GMAssetCompiler.Loader.LoadGMS2CreateAssets(String _filename)
   at GMAssetCompiler.Loader.Load(String _name)
   at GMAssetCompiler.Program.GetAssetsFile(List`1 _args)
   at GMAssetCompiler.Program.Main(String[] _args)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Igor.Program.ExecuteAssetCompiler(String _args)
   at Igor.Program.SetupBuildEnv(String _options, String _project, String _runtimeLocation, String _cache, String _temp, String _user, String _outputFilename, String _targetFilename, String _debuggerPort, Boolean _launchPackage)
   at Igor.Program.Main(String[] args)
Igor complete.
```

### Steps To Reproduce
1. Start GM and import this small sample (not the giant one originally sent with this report): [GM-252.zip](https://github.com/user-attachments/files/16550114/GM-252.zip)
2. (Optional) Run the game for Windows VM and observe the spinning GM logo and then just a black screen, close the game
3. Delete the sprites folder in the AB
4. Try to run the project and observe it fails

### Which version of GameMaker are you reporting this issue for?
IDE v2024.6.2.162 Runtime v2024.6.1.208

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Which platform(s) are you seeing the problem on?
Windows

[f8bd36e0-3c89-4ebb-9c2b-963296b8276f](https://api.gamemaker.io/api/github/downloads/f8bd36e0-3c89-4ebb-9c2b-963296b8276f)

**Comment by YYDan** [comment]
Note that simply importing the attached project will show the same errors in ProjectTool's output window:

```
Setting up CoreResources for VERSIONED
Loading...System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\dan\GameMakerProjects\GM-25\sprites\Hand\Hand.yy'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.ReadAllBytes(String path)
   at YoYoStudio.Resources.FileIO.<>c.<SetDefaultFileFunctions>b__58_6(String _path)
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\dan\GameMakerProjects\GM-25\sprites\Layer_6_copy\Layer_6_copy.yy'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.ReadAllBytes(String path)
   at YoYoStudio.Resources.FileIO.<>c.<SetDefaultFileFunctions>b__58_6(String _path)
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\dan\GameMakerProjects\GM-25\sprites\Hand_Holding\Hand_Holding.yy'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.ReadAllBytes(String path)
   at YoYoStudio.Resources.FileIO.<>c.<SetDefaultFileFunctions>b__58_6(String _path)
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\dan\GameMakerProjects\GM-25\sprites\Layer_537\Layer_537.yy'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.ReadAllBytes(String path)
   at YoYoStudio.Resources.FileIO.<>c.<SetDefaultFileFunctions>b__58_6(String _path)
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\dan\GameMakerProjects\GM-25\sprites\Hand_L\Hand_L.yy'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.ReadAllBytes(String path)
   at YoYoStudio.Resources.FileIO.<>c.<SetDefaultFileFunctions>b__58_6(String _path)
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\dan\GameMakerProjects\GM-25\sprites\Layer_6\Layer_6.yy'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.ReadAllBytes(String path)
   at YoYoStudio.Resources.FileIO.<>c.<SetDefaultFileFunctions>b__58_6(String _path)
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\dan\GameMakerProjects\GM-25\sprites\Body\Body.yy'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.ReadAllBytes(String path)
   at YoYoStudio.Resources.FileIO.<>c.<SetDefaultFileFunctions>b__58_6(String _path)
Failed to load resource file 'C:/Users/dan/GameMakerProjects/GM-25/sprites/Body/Body.yy'.
Core Resources : Info - Failed to load resource file 'C:/Users/dan.cleaton/GameMakerProjects/GM-25/sprites/Body/Body.yy'.
Failed: Failed to load resource file 'C:/Users/dan/GameMakerProjects/GM-25/sprites/Body/Body.yy'.
```

**Comment by YYDan** [comment]
This also seems to fix the problem for everyone else - I am able to build and play the game just fine, so assume ProjectTool fixed the problems during import.

**Comment by YYDan** [comment]
Okay, the key thing is seemingly that you have to delete the sprite(s) via deleting a group in the AB, rather than just an individual sprite. This makes it reliable for me and is what Ash originally did also, so I have updated the repro steps above now.

Ash says deleting a single sprite can still be enough to cause the problem in some cases, but I was not able to break the spinning GM logo sequence in my little sample that way.

**Comment by yyalansavage** [comment]
I did not repro by deleting the folder with the sprite. Issue actually seems to occur if you delete the sprite use by the sequence when the Sequence Editor is not open.

**Comment by YYDan** [comment]
All fine for me now in IDE v2024.800.0.611  Runtime v2024.800.0.635.
