### ISSUE TITLE
Cant get my Gamemaker to run any game

### ISSUE THREAD

**Issue by K4F4R** [YoYoGames/GameMaker-Bugs#7408]
### Description

I cannot run any of the projects I have and I  have tried re-installing Gamemaker studio already and it is not working. this is the message that always appears when I try to run any of my projects:

C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2024.2.0.163/bin/igor/windows/x64/Igor.exe"  -j=8  -options="C:\Users\Bart\AppData\Local\GameMakerStudio2\GMS2TEMP\build.bff" -v -- Windows Run

Loaded Macros from C:\Users\Bart\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE\BLANK_GAME_C3921DCA\macros.json
Options: C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2024.2.0.163\bin\platform_setting_defaults.json
Options: C:\Users\Bart\AppData\Roaming/GameMakerStudio2\unknownUser_unknownUserID\local_settings.json
Options: C:\Users\Bart\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE\BLANK_GAME_C3921DCA\targetoptions.json
Setting up the Asset compiler
C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2024.2.0.163/bin/assetcompiler/windows/x64/GMAssetCompiler.dll  /c /mv=1 /zpex /iv=0 /rv=0 /bv=0 /j=8  /gn="BLANK GAME" /td="C:\Users\Bart\AppData\Local\GameMakerStudio2\GMS2TEMP" /cd="C:\Users\Bart\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE\BLANK_GAME_C3921DCA" /rtp="C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2024.2.0.163" /zpuf="C:\Users\Bart\AppData\Roaming/GameMakerStudio2\unknownUser_unknownUserID"  /ffe="d3t+fjZrf25zeTdwgjZ5em98a3GCN4ODbTZzeH5vdnZzfW94fW82eH92dnN9cjZ2eXFzeGl9fXk2fm99fjZtf31+eXdpb3iANnBzdn41cII2cYJpd3luaYFrdnZ6a3pvfDZxgml3eW5pcWt3b31+fHN6NnZzgG9pgWt2dnprem98aX1/bH1tfHN6fnN5eA==" /m=windows /tgt=64 /nodnd /cfg="Default" /o="C:\Users\Bart\AppData\Local\GameMakerStudio2\GMS2TEMP\BLANK_GAME_4CFD3D75_VM" /sh=True /optionsini="C:\Users\Bart\AppData\Local\GameMakerStudio2\GMS2TEMP\BLANK_GAME_4CFD3D75_VM\options.ini"  /cvm /baseproject="C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2024.2.0.163\BaseProject\BaseProj
ect.yyp" "C:\Users\Bart\GameMakerProjects\BLANK GAME\BLANK GAME.yyp" /preprocess="C:\Users\Bart\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE\BLANK_GAME_C3921DCA"
Found Project Format 2
C:/Users/Bart/GameMakerProjects/BLANK GAME/options/main/options_main.yy(13,3): GMSC Error: option_sci_usesci expected.
Core Resources : IDE Message - ProjectLoad_ErrorTitle : ProjectLoad_ErrorMessage ( C:/Users/Bart/GameMakerProjects/BLANK GAME/options/main/options_main.yy(13,3): GMSC Error: option_sci_usesci expected. )
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at GMAssetCompiler.Loader.<>c__DisplayClass5_0.<LoadGMS2CreateAssets>b__2(ResourceBase _project)
   at YoYoStudio.Resources.ProjectInfo.<>c__DisplayClass23_0.<LoadProject>g__handleFailure|4(String message) in /home/runner/work/GameMaker/GameMaker/GameMaker/Runner/GMAssetCompiler/CoreResources/CoreResources/Management/ProjectInfo.cs:line 294
   at YoYoStudio.Resources.ProjectInfo.LoadProject(String _path, Boolean _setActive, OnLoadSaveSuccess _onSuccess, OnLoadSaveUpdate _onUpdate, OnLoadSaveFailed _onFailed, Boolean _triedProjectTool) in /home/runner/work/GameMaker/GameMaker/GameMaker/Runner/GMAssetCompiler/CoreResources/CoreResources/Management/ProjectInfo.cs:line 322
   at GMAssetCompiler.Loader.LoadGMS2CreateAssets(String _filename)
   at GMAssetCompiler.Loader.Load(String _name)
   at GMAssetCompiler.Program.GetAssetsFile(List`1 _args)
   at GMAssetCompiler.Program.Main(String[] _args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Igor.Program.ExecuteAssetCompiler(String _args)
   at Igor.Program.SetupBuildEnv(String _options, String _project, String _runtimeLocation, String _cache, String _temp, String _user, String _outputFilename, String _targetFilename, String _debuggerPort, Boolean _launchPackage)
   at Igor.Program.Main(String[] args)
[createdump] Writing minidump to file C:\ProgramData\GameMakerStudio2\Dumps\gmdump.19584.dmp
[createdump] Dump successfully written
Igor complete.
elapsed time 00:00:04.2665173s for command "C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2024.2.0.163/bin/igor/windows/x64/Igor.exe" -j=8  -options="C:\Users\Bart\AppData\Local\GameMakerStudio2\GMS2TEMP\build.bff" -v -- Windows Run started at 08/23/2024 21:44:54
FAILED: Run Program Complete
For the details of why this build failed, please review the whole log above and also see your Compile Errors window.

### Expected Change

for my gamemaker to not fail to run my games.

### Steps To Reproduce

1. Start GameMaker
2. Open new project
3. Run empty project
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.6.2 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Which platform(s) are you having trouble building this project for?

Windows

### Are you running GameMaker from inside your Steam library?

No

### Contact Us Package Attached?

- [X] I have attached my Contact Us Package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by L-Clouds** [comment]
Wrong runtime version for your IDE version. Update the runtime. See #6915

**Comment by stuckie** [comment]
Closing as above, thanks.
