### ISSUE TITLE
Local Packages: Some packages will fail to import into LTSr3

### ISSUE THREAD

**Issue by DiasFranciscoA** [YoYoGames/GameMaker-Bugs#7691]
### Description

As described in the title.
Here are the relevant ui.logs and a test yymps (AdMob 1.4.0)

```
[12:21:29:332(1444)] Starting job:ExtractPackage...
[12:21:29:333(1444)] Extracting package: E:\Source\GMEXT-AdMob\output\AdMob Ext (v1.4.0).yymps to: E:\GameMaker\Temp\GMS2TEMP\AdMob Ext (v1.4.0)_6cb5146b\extract
[12:21:29:506(1444)] Extract Complete:success=True
[12:21:29:507(1444)] Starting job:VerifyPackage...
[12:21:29:519(1444)] Starting job:EnumerateFiles...
[12:21:29:528(1444)] Starting job:VeryifyMD5...
[12:21:29:705(1444)] Starting job:LoadProject...
[12:21:29:947(1444)] Project Load Exception, Collection was modified; enumeration operation may not execute.   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at YoYoStudio.Resources.GMProject.PostDeserialise(GMProject _project)
   at YoYoStudio.Resources.GMProject.LoadUpdate(OnLoadSaveSuccess _onSuccess, OnLoadSaveUpdate _onUpdate, OnLoadSaveFailed _onFailed)
[12:21:29:962(1444)] FAILED job:LoadProject
[12:21:29:966(1444)] ResourceManager resources have been cleared
[12:21:29:969(1444)] Setting ProjectFullFilePathMacro to 'E:\GameMaker\Projects\EMPTY1\EMPTY1.yyp'
[12:21:29:969(1444)] Setting ProjectDirMacro to 'E:\GameMaker\Projects\EMPTY1'
[12:21:29:969(1444)] Setting ProjectNameMacro to 'EMPTY1'
[12:21:57:500(1444)] Analytics :: sending _uri=https://api.mixpanel.com/track with json={"event" : "open_browser","properties" : {"token" : "73f678be4bbca5175b05134e8a9675f7","distinct_id" : "18644","machine_id" : "65308F7F8605CDF1AB26D90CED1F9BAF","ide_version" : "2022.0.3.70","runtime_version" : "2022.0.3.83","time" : "1726658517.499693","url" : "C:\ProgramData\GameMakerStudio2-LTS"}}

```

[AdMob Ext (v1.4.0).zip](https://github.com/user-attachments/files/17043300/AdMob.Ext.v1.4.0.zip)

### Steps To Reproduce

1. Start GameMaker
2. Test importing local package
3. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2022.0.2 (LTS)

### Which operating system(s) are you seeing the problem on?

Windows 10

### Are you running GameMaker from inside your Steam library?

No

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by stuckie** [comment]
Technically nothing to do with ProjectTool, this was due to folder structures being loaded out of order. They were being generated on an ad-hoc basis, which modified the list they were reading from. This was fixed in later versions, but was not backported.

**Comment by YYDan** [comment]
Works correctly for me now - IDE v2022.0.3.71  Runtime v2022.0.3.83

![image](https://github.com/user-attachments/assets/728ff403-ca3b-4990-895b-7edd2135fffb)

[15:37:05:916(2778)] Import Completed successfully 'AdMob Ext (v1.4.0)'

Verifying.
