### ISSUE TITLE
Project Import: [Mac IDE] Unable to convert old-format projects in early 2024.1100 Beta IDEs

### ISSUE THREAD

**Issue by Emc1923** [YoYoGames/GameMaker-Bugs#7756]
### Description

Attempting to import any project (that uses a previous format) to the IDE will fail and hard lock the IDE (in some cases). 
<img width="1250" alt="Screenshot 2024-09-19 at 16 03 43" src="https://github.com/user-attachments/assets/4de20347-9c66-4695-aeff-1d3d3ba81fb5">

In others, the conversion will just fail, like the below example:

```
ProjectTool Version 1.5
-----------------------
Checking 'VERSIONED' can load/import '/tmp/GameMakerStudio2-Beta/GMS2TEMP/conv/yyp/GML-2_1E68EB10/GML-2.yyp' - False/True : 9999
Checking 'VERS0' can load/import '/tmp/GameMakerStudio2-Beta/GMS2TEMP/conv/yyp/GML-2_1E68EB10/GML-2.yyp' - False/False : 9999
Checking 'MVC' can load/import '/tmp/GameMakerStudio2-Beta/GMS2TEMP/conv/yyp/GML-2_1E68EB10/GML-2.yyp' - True/False : 9999
Checking 'GMX' can load/import '/tmp/GameMakerStudio2-Beta/GMS2TEMP/conv/yyp/GML-2_1E68EB10/GML-2.yyp' - False/False : 9999
Loading project '/tmp/GameMakerStudio2-Beta/GMS2TEMP/conv/yyp/GML-2_1E68EB10/GML-2.yyp'
Loading project '/tmp/GameMakerStudio2-Beta/GMS2TEMP/conv/yyp/GML-2_1E68EB10/GML-2.yyp'
Resource file is malformed 'options/windowsuap/options_windowsuap.yy' System.ArgumentNullException: Value cannot be null. (Parameter 'type')
   at YoYoStudio.MVC.ResourceManager.DeserialiseIntoResourceModel(String _jsonData, String _resourceType, Boolean _register) in /Users/runner/work/ProjectTool/ProjectTool/Source/Formats/2.2.5/MVC/ResourceManagement/ResourceManager.LoadSave.cs:line 141
   at YoYoStudio.MVC.ResourceManager.DeserialiseResource(String _jsonData, GMResourceInfo_Controller _resInfo, Boolean _addResource) in /Users/runner/work/ProjectTool/ProjectTool/Source/Formats/2.2.5/MVC/ResourceManagement/ResourceManager.LoadSave.cs:line 88
   at YoYoStudio.Plugins.MiscPlugins.ProjectLoadSave.ReadResource(String _resourceJson, GMResourceInfo_Controller _resInfo, String& _errMsg, Boolean _addResource) in /Users/runner/work/ProjectTool/ProjectTool/Source/Formats/2.2.5/ProjectLoadSave.cs:line 587
Resource file is malformed 'options/windowsuap/options_windowsuap.yy' Value cannot be null. (Parameter 'type')
Load project took 00:00:00.1714090
Setting up CoreResources for VERS0
####################################
Break in PrintException (YYDebug:45)
Reason: Exception - Project Conversion Exception
####################################
Project Conversion Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at YoYoStudio.Core.Utils.Language.HasString(String _ID) in /Users/runner/work/ProjectTool/ProjectTool/Source/Formats/2.2.5/Language.cs:line 587
   at YoYoStudio.ResourcesVERS0.ProjectConversion.ParentResource(Guid _child, ResourceBase _parent, GMProject _project, String _withTag) in /Users/runner/work/ProjectTool/ProjectTool/Source/Formats/2.3/VERS-0/ProjectConversion.cs:line 2187
   at YoYoStudio.ResourcesVERS0.ProjectConversion.Update(Boolean _openProject, ConversionCallback _cb) in /Users/runner/work/ProjectTool/ProjectTool/Source/Formats/2.3/VERS-0/ProjectConversion.cs:line 249 [Update, /Users/runner/work/ProjectTool/ProjectTool/Source/Formats/2.3/VERS-0/ProjectConversion.cs, 352]
Loading...System.IO.FileNotFoundException: Could not find file '/tmp/GameMakerStudio2-Beta/GMS2TEMP/ProjectTool/GML-2_MVC_conv_378918090/GML-2.yyp'.
File name: '/tmp/GameMakerStudio2-Beta/GMS2TEMP/ProjectTool/GML-2_MVC_conv_378918090/GML-2.yyp'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at YoYoStudio.ResourcesVERS0.FileIO.<>c.<SetDefaultFileFunctions>b__56_2(String _path) in /Users/runner/work/ProjectTool/ProjectTool/Source/Formats/2.3/VERS-0/FileIO/FileIO.cs:line 243
Setting up CoreResources for VERSIONED
Harvesting resource versions from: /var/folders/sv/dn2cjtfx5g5b5zvtbdp22vpw0000gn/T/tmp7I4b4S.tmp
Targetting resource versions from: /var/folders/sv/dn2cjtfx5g5b5zvtbdp22vpw0000gn/T/tmp7I4b4S.tmp
Changing the class revisions of a VERSIONED file
Class count: 131
Source: /tmp/GameMakerStudio2-Beta/GMS2TEMP/ProjectTool/GML-2_MVC_conv_378918090/GML-2.yyp
Destination: /tmp/GameMakerStudio2-Beta/GMS2TEMP/ProjectTool/GML-2_MVC_conv_378918090/GML-2.yyp
System.IO.FileNotFoundException: Could not find file '/tmp/GameMakerStudio2-Beta/GMS2TEMP/ProjectTool/GML-2_MVC_conv_378918090/GML-2.yyp'.
File name: '/tmp/GameMakerStudio2-Beta/GMS2TEMP/ProjectTool/GML-2_MVC_conv_378918090/GML-2.yyp'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Boolean failForSymlink, Boolean& wasSymlink, Func`4 createOpenException)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.ReadAllBytes(String path)
   at YoYoStudio.Resources.FileIO.<>c.<SetDefaultFileFunctions>b__58_6(String _path) in /Users/runner/work/ProjectTool/ProjectTool/Source/Formats/Versioned/CoreResources/FileIO/FileIO.cs:line 260
Cannot load file /tmp/GameMakerStudio2-Beta/GMS2TEMP/ProjectTool/GML-2_MVC_conv_378918090/GML-2.yyp
ResourceManager resources have been cleared
Cannot convert project
ProjectTool Failed
```

### Steps To Reproduce

1. Start GameMaker on a Mac
2. Attempt to create project from a Start Page Templates or importing an older version project
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

 IDE v2024.1100.0.623  Runtime v2024.1100.0.649

### Which operating system(s) are you seeing the problem on?

macOS Sonoma

### Are you running GameMaker from inside your Steam library?

None

### ui.log File

- [ ] I have attached my ui.log file

### Sample .yyz File

- [ ] I have attached a small sample project

**Comment by stuckie** [comment]
This should now be fixed.

**Comment by Emc1923** [comment]
Verified as of  IDE v2024.1100.0.629  Runtime v2024.1100.0.654
