### ISSUE TITLE
Room Editor: GM crashes if File Watcher is set to "auto-reload" and external app modifies a room .yy file

### ISSUE THREAD

**Issue by nullbunny** [YoYoGames/GameMaker-Bugs#7868]
### Description
I was working on my level and discarded the recent changes via git.

GM froze for a few seconds and then silently closed itself without any error messages.

The same has happened before when I was manually changing a position of an instance in VS Code.

I have GM set up to auto-reload when files change.

ui.log says:
```
[12:20:59:000(ceb0)] --------------------------------------------------------------------------------
[12:20:59:001(ceb0)] IDE Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at YoYoStudio.Plugins.RoomEditor.RoomEditor_SelectedItem.UpdateProperties(Boolean _layoutUpdate)
   at YoYoStudio.Plugins.RoomEditor.RoomEditor_Room.RefreshSelectedBounds()
   at YoYoStudio.Plugins.RoomEditor.RoomEditorModule.Tick()
   at YoYoStudio.Plugins.Command.execute_object(String _command, Object _focus, Object[] paramaters)
   at YoYoStudio.Plugins.Command.execute_object(String _command, Object _focus, Object[] paramaters)
   at YoYoStudio.IDE.Run()
   at YoYoStudio.IDE.Execute(String[] _args, Int32 _initialWidth, Int32 _initialHeight)
[12:20:59:001(ceb0)] --------------------------------------------------------------------------------
```

### Steps To Reproduce
Git:

1. Make changes to a room that involve instances or assets on an asset layer - adding, moving, etc.
2. Discard those changes with GIT

VS Code:
1. Open a room in GM
2. Open the room in VS Code
3. Modify the position value, for example, move X or Y by a small amount.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.8.0.169 Runtime v2024.8.0.216

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[315accbb-92c7-4698-ab7b-b35c57713239](https://api.gamemaker.io/api/github/downloads/315accbb-92c7-4698-ab7b-b35c57713239)

**Comment by YYDan** [comment]
Same thing as https://github.com/YoYoGames/GameMaker-Bugs/issues/7505 but with the added info about VS Code and a report on Windows also.

**Comment by stuckie** [comment]
This particular instance was due to the layer disappearing and should now be fixed

**Comment by Emc1923** [comment]
Verified in  IDE v2024.1100.0.687  Runtime v2024.1100.0.708
