### ISSUE TITLE
Stability: GM crash while loading plugins at startup in 2024.1100.0.643

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GameMaker-Bugs#7969]
### Description

![chrome_st4kRWfA1c](https://github.com/user-attachments/assets/7dc76591-57b5-4a0d-99c8-c2249c4e714f)

Getting this error when opening IDE 2024.1100.0.643. The `ui.log` file showed the following error:

```
IDE Exception: YoYoStudio.GUI.Styles.StyleManagerException: Error: Failed to clone style value object of type 'System.Collections.ArrayList' collection types must have a bespoke deep clone implemented
   at YoYoStudio.GUI.Styles.StyleManager.CloneStyleValue(Object _value)
   at YoYoStudio.GUI.Styles.StyleManager.ApplyStyleValue(Object _obj, PropertyInfo p, StyleValue _styleValue)
   at YoYoStudio.GUI.Styles.StyleManager.Set(Object _obj, List`1 _style, Boolean _fromLayout)
   at YoYoStudio.GUI.Styles.StyleManager.Set(Object _obj, String _stylename)
   at YoYoStudio.GUI.Styles.GUIStyle.Set(String _name)
   at YoYoStudio.GUI.Styles.GUIStyle.set_StyleName(String value)
   at YoYoStudio.GUI.Layout.LayoutManager.LoadStyleAttributes[T](T _gadget, XmlElement _xmlNode, Boolean _setStyles)
   at YoYoStudio.GUI.Layout.LayoutManager.BasicLoad[T](T _gadget, XmlElement _xmlNode)
   at YoYoStudio.GUI.Gadgets.Grid.Load(XmlElement _node)
   at YoYoStudio.GUI.Layout.LayoutManager.CreateGadget(XmlElement layoutXmlElement, LayoutInstanceID _ownerLayout)
   at YoYoStudio.GUI.Layout.LayoutManager.CreateGadgets(GUIBase _g, XmlElement _xmlNode, LayoutInstanceID _ownerLayout)
   at YoYoStudio.GUI.Layout.LayoutManager.CreateLayout(String _layoutID)
   at YoYoStudio.GUI.WindowInterface.CreateLayout(String _layout)
   at YoYoStudio.Plugins.StartScreen.StartScreenModule.CreateStartScreen()
   at YoYoStudio.Plugins.StartScreen.StartScreenModule.Initialise(ModulePackage _ide)
   at YoYoStudio.Plugins.ResourceEditorManager.ActivateModule(Type _type, Object[] _parameters)
   at YoYoStudio.Plugins.Command.execute_object(String _command, Object _focus, Object[] paramaters)
   at YoYoStudio.Plugins.Command.execute_object(String _command, Object _focus, Object[] paramaters)
   at YoYoStudio.SplashScreen.SplashTick()
   at YoYoStudio.Plugins.Command.execute_object(String _command, Object _focus, Object[] paramaters)
   at YoYoStudio.Plugins.Command.execute_object(String _command, Object _focus, Object[] paramaters)
   at YoYoStudio.IDE.Run()
   at YoYoStudio.IDE.Execute(String[] _args, Int32 _initialWidth, Int32 _initialHeight)
```

### Steps To Reproduce

1. Start GameMaker
4. See the issue

[ui.log](https://github.com/user-attachments/files/17335607/ui.log)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.1100 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

No

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by scott-dunbar** [comment]
We have currently not seen this yet in testing

Do you have any custom themes enabled?

**Comment by shichen85** [comment]
> We have currently not seen this yet in testing
> 
> Do you have any custom themes enabled?

I don't have custom themes, though I would love to try deleting whatever folder that supposedly contain those files to see if that solves the problem. Where should I look?

**Comment by scott-dunbar** [comment]
C:\ProgramData\GameMakerStudio2\Skins 

It would be interesting to know if that had any content present before you delete it.

**Comment by shichen85** [comment]
Nope. I have nothing in that folder. Deleted it and still getting the same error. IDE 2024.1100.0.624 still works. I am attaching the new ui.log where you can see 2024.1100.0.624 successfully launches, but `2024.1100.0.629` and `2024.1100.0.643` are crashing.
[ui.log](https://github.com/user-attachments/files/17344332/ui.log)

**Comment by shichen85** [comment]
Resolved as of 2024.1100.0.651

**Comment by stuckie** [comment]
Thanks for letting us know!
Closing as above.. though a little frustrating that we didn't get to the bottom of it...

**Comment by shichen85** [comment]
Got another one from my colleague. IDE 2024.1100.0.634 was fine for him, but 2024.1100.0.654 crashes with the same error that I had. Here is the [ui (1).log](https://github.com/user-attachments/files/17562147/ui.1.log)

**Comment by stuckie** [comment]
Bah, reopened.

On the plus side, there's a little bit more information in there... it's a grid column layout it's having issues with; though it didn't seem to tell me *what* gadget it was trying to load, which is annoying.

**Comment by stuckie** [comment]
I've added another lot of debug info into the next build.
This should tell us what gadget type it thinks it has, and what it's trying to put it into.
Or it might move elsewhere again because we're trying to shine a light on it.. we'll see!

**Comment by stuckie** [comment]
Just checking if you've had any time to see if the last set of fixes resolves, or gives more information here?

**Comment by shichen85** [comment]
> Just checking if you've had any time to see if the last set of fixes resolves, or gives more information here?

Hello @stuckie , we have not been experiencing IDE crashes lately with `2024.1100.0.686` or `2024.1100.0.687`. If anything shows up, I will report back.

**Comment by stuckie** [comment]
Going to tempt fate and close this again!
If anything pops up, let us know.

Thanks!
