### ISSUE TITLE
running

### ISSUE THREAD

**Issue by CrazyKieran19** [YoYoGames/GameMaker-Bugs#8050]
### Description

It will not let me run my build and just says "error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory" https://api.gamemaker.io/api/github/downloads/3e623c84-a617-473e-9be4-6cbbf5e60244

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.1100 (Betas)

### Which operating system(s) are you seeing the problem on?

ChromeOS

### Which platform(s) are you having trouble building this project for?

Ubuntu

### Are you running GameMaker from inside your Steam library?

No

### Sample Package Attached?

- [X] I have attached my bug package

### Sample Project Added?

- [X] I have included a small sample project

**Comment by YYDan** [comment]
Unfortunately, you must have restarted GM before sending us this bug report, so there is no compiler log included and we cannot comment on the actual error you're reporting.

We'll see if we can reproduce, but in the meantime I would of course suggest that you check the Ubuntu setup guide on our Helpdesk and ensure you have actually installed all the required packages, as this may be something you can fix immediately in your current install.


However, there are several errors in your ui.log which further lead me to believe this might actually be a permissions issue on your own machine.

The post-install script for installing the runtmes failed to run properly:
```
[14:44:29:095(ab70)] running linux post install script...
[14:44:29:102(ab70)] starting /bin/sh -c ". /home/kfoxmeyer/.local/share/GameMakerStudio2-Beta/Cache/runtimes/runtime-2024.1100.0.658/bin/linux-post-install.sh"
[14:44:29:205(ab70)] elapsed time 00:00:00.0979000s for command "/bin/sh" -c ". /home/kfoxmeyer/.local/share/GameMakerStudio2-Beta/Cache/runtimes/runtime-2024.1100.0.658/bin/linux-post-install.sh" started at 10/18/2024 14:44:29
[14:44:29:207(ab70)] linux post install script output : /bin/sh: 46: /home/kfoxmeyer/.local/share/GameMakerStudio2-Beta/Cache/runtimes/runtime-2024.1100.0.658/bin/linux-post-install.sh: pushd: not found
[14:44:29:207(ab70)] linux post install script result : 127
```

You appear to have a number of instances where opening the OS file browser did not work properly and you were blocked when trying to load a few different projects - as one example:
```
[14:56:56:263(ab70)] File exception 'Could not find file '/home/kfoxmeyer/GameMakerProjects/MY FIRST GAME in gamemaker/MY FIRST GAME in gamemaker.yyp'.'
[14:57:35:958(ab70)] OpenBrowserToImportFromYY: ShowDialog Error: 
```
or, similarly, files were blocked from being read:
```
[15:59:49:890(ab70)] Failed to open document for edit: /home/kfoxmeyer/GameMakerProjects/BLANK GAME/objects/Object1/Create_0.gml - File Error FileNotFound
[16:00:18:468(ab70)] DoUndoableAction: 'create event'
[16:00:18:535(ab70)] Failed to open document for edit: /home/kfoxmeyer/GameMakerProjects/BLANK GAME/objects/Object1/Step_0.gml - File Error FileNotFound
```

And in recent starts of GM you have issues running ProjectTool (which could lead to a variety of other problems):
```
[15:56:06:061(ab70)] Unable to launch "./ProjectTool/ProjectTool": System.ComponentModel.Win32Exception (8): An error occurred trying to start process '/opt/GameMaker-Beta/aarch64/./ProjectTool/ProjectTool' with working directory '/opt/GameMaker-Beta/aarch64'. Exec format error
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at YoYoStudio.Core.Utils.CmdProcess.StartProcess(String _working_directory, OutputDelegate _output, OutputDelegate _error) [StartProcess, /home/runner/work/YoYoStudio/YoYoStudio/YoYoStudio/IDE/Core/Utils/CmdProcess.cs, 267]
[15:56:06:064(ab70)] FAILED job:ProjectTool
```

As well as ensuring you have followed the Ubuntu (IDE and platform setup guides (both of them), I would recommend you review our [Permissions FAQ](https://help.gamemaker.io/hc/en-us/articles/360022953052) and follow the steps there. Note that we always link to this guide on the release notes page, as many users need to review their protection settings every time they install a new version of GameMaker, so this may be something you need to do also in future.
