### ISSUE TITLE
Layouts Menu: GM unstable when selecting Show/Close All Windows in 2024.1100 Betas

### ISSUE THREAD

**Issue by sihammill** [YoYoGames/GameMaker-Bugs#8101]
### Description

When selecting either **_Show / Close all windows_** from the Layouts menu results in the IDE becoming unstable and the following entry added to the ui.log. However, if you right click in the empty Workspace tab and select Windows -> Show all / Close all, then the issue doesn't arise and returning to the layouts menu and selecting Show / Close all windows now doesn't raise the issue.

Beta Build Version: IDE v2024.1100.0.653  Runtime v2024.1100.0.679

Close all windows
```
[13:47:27:131(0f77)] Exception in YoYoStudio.GUI.Gadgets.MenuEntry,Void ReleaseButton(Single, Single, YoYoStudio.Core.Utils.eMouseButtons) : System.NullReferenceException: Object reference not set to an instance of an object.
 at YoYoStudio.Plugins.ProjectLayout.ProjectLayoutModule.HideAllWindows()
 at YoYoStudio.Plugins.Command.execute_object(String _command, Object _focus, Object[] paramaters)
 at YoYoStudio.GUI.Gadgets.Button.ButtonClicked(Boolean _bRightClicked)
 at YoYoStudio.GUI.Gadgets.Button.ReleaseButton(Single _mousex, Single _mousey, eMouseButtons _buttons)
 at WeakDelegate(Object, Object[])
 at YoYoStudio.Core.Utils.WeakDelegate`1.Invoke(Object[] _args)
[13:47:27:136(0f77)] Fatal Error! 'IDE.OnWeakDelegateException - Object reference not set to an instance of an object.'
[13:47:27:139(0f77)] at YoYoStudio.Plugins.ProjectLayout.ProjectLayoutModule.HideAllWindows()
 at YoYoStudio.Plugins.Command.execute_object(String _command, Object _focus, Object[] paramaters)
 at YoYoStudio.GUI.Gadgets.Button.ButtonClicked(Boolean _bRightClicked)
 at YoYoStudio.GUI.Gadgets.Button.ReleaseButton(Single _mousex, Single _mousey, eMouseButtons _buttons)
 at WeakDelegate(Object, Object[])
 at YoYoStudio.Core.Utils.WeakDelegate`1.Invoke(Object[] _args)
[13:47:27:143(0f77)] ####################################
[13:47:27:146(0f77)] Break in FatalErrorWarning (IDE:4760)
[13:47:27:149(0f77)] ####################################
```

Show all Windows
```
[13:47:29:700(0f77)] Exception in YoYoStudio.GUI.Gadgets.MenuEntry,Void ReleaseButton(Single, Single, YoYoStudio.Core.Utils.eMouseButtons) : System.NullReferenceException: Object reference not set to an instance of an object.
 at YoYoStudio.Plugins.ProjectLayout.ProjectLayoutModule.ShowAllWindows()
 at YoYoStudio.Plugins.Command.execute_object(String _command, Object _focus, Object[] paramaters)
 at YoYoStudio.GUI.Gadgets.Button.ButtonClicked(Boolean _bRightClicked)
 at YoYoStudio.GUI.Gadgets.Button.ReleaseButton(Single _mousex, Single _mousey, eMouseButtons _buttons)
 at WeakDelegate(Object, Object[])
 at YoYoStudio.Core.Utils.WeakDelegate`1.Invoke(Object[] _args)
[13:47:29:706(0f77)] Fatal Error! 'IDE.OnWeakDelegateException - Object reference not set to an instance of an object.'
[13:47:29:709(0f77)] at YoYoStudio.Plugins.ProjectLayout.ProjectLayoutModule.ShowAllWindows()
 at YoYoStudio.Plugins.Command.execute_object(String _command, Object _focus, Object[] paramaters)
 at YoYoStudio.GUI.Gadgets.Button.ButtonClicked(Boolean _bRightClicked)
 at YoYoStudio.GUI.Gadgets.Button.ReleaseButton(Single _mousex, Single _mousey, eMouseButtons _buttons)
 at WeakDelegate(Object, Object[])
 at YoYoStudio.Core.Utils.WeakDelegate`1.Invoke(Object[] _args)
[13:47:29:713(0f77)] ####################################
[13:47:29:716(0f77)] Break in FatalErrorWarning (IDE:4760)
[13:47:29:719(0f77)] ####################################
```

### Steps To Reproduce

1. Start GameMaker
2. Open a project, any
3. Go to the top Layouts menu and select Show / Close all windows
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.1100 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

None

### Sample Package Attached?

- [ ] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by mgeddesGM** [comment]
verified as of  IDE v2024.1100.0.659  Runtime v2024.1100.0.685
