### ISSUE TITLE
Project Build: [Windows] Unhandled exception when adding a unicode codepoint "'\ud83d\ude42'" within a string

### ISSUE THREAD

**Issue by sihammill** [YoYoGames/GameMaker-Bugs#8117]
### Description

Trying to output this struct key, value pair results in the below unhandled exception
`show_debug_message("string_length( string const ), Sshould return length of 1 for string literal '\ud83d\ude42'");`

```
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentOutOfRangeException: A valid UTF32 value is between 0x000000 and 0x10ffff, inclusive, and should not include surrogate codepoint values (0x00d800 ~ 0x00dfff). (Parameter 'utf32')
   at System.Char.ConvertFromUtf32(Int32 utf32)
   at GMAssetCompiler.GMLCompile.NextZeusString(String _script, Int32& _index, List`1 _variables)
   at GMAssetCompiler.GMLCompile.NextToken(String _script, Int32& _index, Int32& _line)
   at GMAssetCompiler.GMLCompile.PreParse(String _script, String _filename, String _fullFilename)
   at GMAssetCompiler.GMObject.SubTypeAndEventFromEvent(GMAssets _a, GMEvent _ev)
   at GMAssetCompiler.GMObject.SetFromResource(GMAssets _a, ResourceBase _id)
   at GMAssetCompiler.GMObject..ctor(GMAssets _a, ResourceBase _id)
   at GMAssetCompiler.GMAssets.AddAssets(GMProject _project, String _baseDir, Boolean _hasPrefabs)
   at GMAssetCompiler.Loader.LoadGMS2CreateAssets(String _filename)
   at GMAssetCompiler.Loader.Load(String _name)
   at GMAssetCompiler.Program.GetAssetsFile(List`1 _args)
   at GMAssetCompiler.Program.Main(String[] _args)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Igor.Program.ExecuteAssetCompiler(String _args)
   at Igor.Program.SetupBuildEnv(String _options, String _project, String _runtimeLocation, String _cache, String _temp, String _user, String _outputFilename, String _targetFilename, String _debuggerPort, Boolean _launchPackage)
   at Igor.Program.Main(String[] args)
```

### Steps To Reproduce

1. Start GameMaker
2. Add the following unicode codepoint to a string
3. `show_debug_message("string_length( string const ), Sshould return length of 1 for string literal '\ud83d\ude42'");`
4. Run project
5. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.1100 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Which platform(s) are you having trouble building this project for?

Windows

### Are you running GameMaker from inside your Steam library?

None

### Sample Package Attached?

- [ ] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by rwkay** [comment]
Fixed in 2024.11
