### ISSUE TITLE
Start page: Carousel tiles are not displaying and remote server error entry in ui.log

### ISSUE THREAD

**Issue by sihammill** [YoYoGames/GameMaker-Bugs#8192]
### Description

After loading the latest beta IDE v2024.1100.0.661  Runtime v2024.1100.0.687 it is noted that the Carousel tiles are no longer displaying:

![Image](https://github.com/user-attachments/assets/56c2da5d-68f3-4675-8f30-096bca640b17)

The following error is then added in the ui.log:
```
[10:01:52:238(cd28)] Start page carousel failed, server not responding: System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
 at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
 at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
 at System.Net.WebClient.GetWebResponseTaskAsync(WebRequest request)
 at System.Net.WebClient.DownloadBitsAsync(WebRequest request, Stream writeStream, AsyncOperation asyncOp, Action`3 completionDelegate)
```

### Steps To Reproduce

1. Start GameMaker
2. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.1100 (Betas)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

None

### Sample Package Attached?

- [x] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by iampremo** [comment]
website issue not ide

**Comment by code-bunny** [comment]
Looking into it, but I need something more to go on to track it down. We know something is returning a 503, but I don't have the URL.

**Comment by YYDan** [comment]
Finally closing - was obviously fixed way back at the time.
