### ISSUE TITLE
Code Editor 2: Language server fails again in CE2 2024.1100.0.655 IDE

### ISSUE THREAD

**Issue by gnysek** [YoYoGames/GameMaker-Bugs#8271]
### Description
Language server fails again in CE2 2024.1100.0.655 IDE - what's worse, there's even no message about it in top-right corner, like it was before.

Similar to #6701, #5251, #7161

### Steps To Reproduce
1. Create new project in 2024.1100.0.655 (while CE2 is already enabled)
2. See that there's no syntax higligting at all.
3. From now on, reloading project or loading existing one would still not use LS anymore, only restart helps
4. It would work for existing projects, but would crash again for same IDE session when creating new project

What I found in logs:
```
[09:45:58:359(5e25)] File exception 'Could not find file 'C:\Users\gnysek\Documents\GameMakerStudio2\beta_svg_jiggly\beta_svg_jiggly.yyp'.'
[09:45:58:417(4ae5)] Exception in GameMakerLanguageServer.Handlers.CompletionHandler+<>c,Void <.ctor>b__7_1() :    System.NullReferenceException: Object reference not set to an instance of an object.
   at GameMakerLanguageServer.Handlers.CompletionHandler.<>c.<.ctor>b__7_1()
   at WeakDelegate(Object, Object[])
   at YoYoStudio.Core.Utils.WeakDelegate`1.Invoke(Object[] _args)
[09:45:58:418(4ae5)] Exception in GameMakerLanguageServer.Handlers.CompletionHandler+<>c,Void <.ctor>b__7_1() :    System.NullReferenceException: Object reference not set to an instance of an object.
   at GameMakerLanguageServer.Handlers.CompletionHandler.<>c.<.ctor>b__7_1()
   at WeakDelegate(Object, Object[])
   at YoYoStudio.Core.Utils.WeakDelegate`1.Invoke(Object[] _args)
```

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.665 Runtime v2024.1100.0.691

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[9a421f10-cc98-4b8b-8cdf-93ac0334b9b5](https://api.gamemaker.io/api/github/downloads/9a421f10-cc98-4b8b-8cdf-93ac0334b9b5)

**Comment by zreedy** [comment]
This bug has a 100% repro rate in official Beta and Red builds, and a 0% repro rate in my branch dev builds.
Without a reliable repro I can not verify that this bug is fixed in branch and will need to await confirmation from QA against a Red/Beta build.

The issue appears to be that a race condition between the Client and Server exists where the Client issues a workspace open, close, open due to a project being upgraded. The Server finishes the first open right as it receives the close command. OmniSharp parallelizes the commands so that the close command `null`s out the `ProjectInfo.Current` field before the `GMProjectService.OnProjectLoaded` event fires. The callbacks on this event throw the above exception because it _should be impossible_ for `ProjectInfo.Current` to be null by the time this event is fired (as it is _not_ fired if the project did not load). _Normally_ the first load would fail but it appears that the Client actually serializes the upgraded project to disk before the first open command can even read the offending resource (Room v0). The exception then causes the 2nd open command to abort as the command processor is in a parallel configuration and recycles the same TPL thread for the `WorkspaceChangeHandler`.

I suspect that this does not happen in dev builds because the code is not compiled with full optimizations (even in Release, without Debugger).

Current fix is to add a mutex to the entry point for `WorkspaceChangeHandler`, additionally the fix for private ticket 10869 should prevent the open, close, open dispatch in the first place as the blank project no longer requires an upgrade.

**Comment by sihammill** [comment]
After running through the repo steps above, I have tried multiple times and I'm not getting a notification that the Language Server had failed. All syntax colouring appears to be correct and as expected.

Tested using IDE v2024.1100.0.681  Runtime v2024.1100.0.703
