### ISSUE TITLE
Sprite Editor: GM unstable when dropping a SVG image into the frames bar of an existing SVG sprite

### ISSUE THREAD

**Issue by alicemoretti** [YoYoGames/GameMaker-Bugs#8479]
### Description
On IDE v2024.1100.0.693  Runtime v2024.1100.0.712, when dragging and dropping a SVG image into the frames preview section of a sprite that is another SVG, the IDE becomes unstable. 

The ui.log shows the following error: 
```
[15:12:14:473(3242)] File exception 'Could not find a part of the path 'C:\Users\amoretti\GameMakerProjects\svginsprite\sprites\duck\253b83e6-5df0-44e7-a1cb-8796f28e1bd9.png'.'
[15:12:14:477(3242)] File exception 'Could not find a part of the path 'C:\Users\amoretti\GameMakerProjects\svginsprite\sprites\duck\253b83e6-5df0-44e7-a1cb-8796f28e1bd9.svg'.'
[15:12:14:481(3242)] File exception 'Could not find a part of the path 'C:\Users\amoretti\GameMakerProjects\svginsprite\sprites\duck\253b83e6-5df0-44e7-a1cb-8796f28e1bd9.dat'.'
[15:12:14:571(3242)] File exception 'Could not find a part of the path 'C:\Users\amoretti\GameMakerProjects\svginsprite\sprites\duck\400e3234-c0f6-42d9-9e9f-ba9c69143478.dat'.'
[15:12:14:576(3242)] ####################################
[15:12:14:579(3242)] Break in WriteBinary (FileSystem_Local_NonAsync:619)
[15:12:14:582(3242)] Reason: Could not find a part of the path 'C:\Users\amoretti\GameMakerProjects\svginsprite\sprites\duck\400e3234-c0f6-42d9-9e9f-ba9c69143478.dat.new'. ( C:\Users\amoretti\GameMakerProjects\svginsprite\sprites\duck\400e3234-c0f6-42d9-9e9f-ba9c69143478.dat )
[15:12:14:586(3242)] ####################################
[15:12:14:589(3242)] File exception 'Could not find a part of the path 'C:\Users\amoretti\GameMakerProjects\svginsprite\sprites\duck\400e3234-c0f6-42d9-9e9f-ba9c69143478.dat.new'.'
[15:12:15:236(3242)] WeakRefHandleManager for GPU API:  Scan #1178:  1 x object's handles garbage-collected.  128 objects remain allocated.
[15:12:15:943(3242)] WeakRefHandleManager for GPU API:  Scan #1185:  22 x object's handles garbage-collected.  136 objects remain allocated.
[15:12:20:247(3242)] Exception in YoYoStudio.Plugins.SpriteEditor.SpriteEditorModule,Void DopeSheet_OnOsDndEvent(Core.CoreOS.System.eOSDndEventType, Single, Single, System.Collections.Generic.IReadOnlyList`1[System.String]) :    System.InvalidCastException: Unable to cast object of type 'YoYoStudio.Resources.GMSpriteVector' to type 'YoYoStudio.Resources.GMSpriteBitmap'.
   at YoYoStudio.Plugins.SpriteEditor.Resize.SpriteResizeHelper.ResizeSpriteBitmap(GMSpriteImage _image, Int32 _width, Int32 _height, ipoint _offset, irect _srcRect, Boolean& _unload)
   at YoYoStudio.Plugins.SpriteEditor.Resize.SpriteResizeHelper.PreviewResizeCanvas(Int32 _newWidth, Int32 _newHeight, eAnchor _anchor, GMSprite _sprite)
   at YoYoStudio.Plugins.SpriteEditor.Resize.SpriteResizeDialog.<>c__DisplayClass33_0.<OpenResizeDialog>b__4(Boolean _scale)
   at YoYoStudio.Plugins.SpriteEditor.Resize.SpriteResizeDialog.OpenResizeDialog(Int32 _desktopId, Boolean _allowCancel, Boolean allowChangeSize, Action _preResize)
   at YoYoStudio.Plugins.SpriteEditor.SpriteEditorModule.OpenResizeDialog(Boolean _allowCancel, Boolean allowChangeSize, Boolean _allowOpenInImageEditor)
   at YoYoStudio.Plugins.SpriteEditor.SpriteEditorModule.<>c__DisplayClass133_0.<AddImagesWithResizeDialog>b__0()
   at YoYoStudio.Plugins.SpriteEditor.Resize.SpriteResizeHelper.AddImagesWithResizeDialog(GMSprite _sprite, SpriteResizeDialog _dialog, IReadOnlyList`1 _filenames, Boolean _import, Func`1 _showDialog, Action _onComplete, Dictionary`2& _yyImages)
   at YoYoStudio.Plugins.SpriteEditor.SpriteEditorModule.AddImagesWithResizeDialog(IReadOnlyList`1 _filenames, Boolean _import, Dictionary`2& _yyImages)
   at YoYoStudio.Plugins.SpriteEditor.SpriteEditorModule.AddImageFiles(IReadOnlyList`1 _filenames)
   at YoYoStudio.Plugins.SpriteEditor.SpriteEditorModule.DopeSheet_OnOsDndEvent(eOSDndEventType _type, Single _mousex, Single _mousey, IReadOnlyList`1 _filenames)
   at WeakDelegate(Object, Object[])
   at YoYoStudio.Core.Utils.WeakDelegate`1.Invoke(Object[] _args)
[15:12:20:253(3242)] Fatal Error! 'IDE.OnWeakDelegateException - Unable to cast object of type 'YoYoStudio.Resources.GMSpriteVector' to type 'YoYoStudio.Resources.GMSpriteBitmap'.'
[15:12:20:257(3242)]    at YoYoStudio.Plugins.SpriteEditor.Resize.SpriteResizeHelper.ResizeSpriteBitmap(GMSpriteImage _image, Int32 _width, Int32 _height, ipoint _offset, irect _srcRect, Boolean& _unload)
   at YoYoStudio.Plugins.SpriteEditor.Resize.SpriteResizeHelper.PreviewResizeCanvas(Int32 _newWidth, Int32 _newHeight, eAnchor _anchor, GMSprite _sprite)
   at YoYoStudio.Plugins.SpriteEditor.Resize.SpriteResizeDialog.<>c__DisplayClass33_0.<OpenResizeDialog>b__4(Boolean _scale)
   at YoYoStudio.Plugins.SpriteEditor.Resize.SpriteResizeDialog.OpenResizeDialog(Int32 _desktopId, Boolean _allowCancel, Boolean allowChangeSize, Action _preResize)
   at YoYoStudio.Plugins.SpriteEditor.SpriteEditorModule.OpenResizeDialog(Boolean _allowCancel, Boolean allowChangeSize, Boolean _allowOpenInImageEditor)
   at YoYoStudio.Plugins.SpriteEditor.SpriteEditorModule.<>c__DisplayClass133_0.<AddImagesWithResizeDialog>b__0()
   at YoYoStudio.Plugins.SpriteEditor.Resize.SpriteResizeHelper.AddImagesWithResizeDialog(GMSprite _sprite, SpriteResizeDialog _dialog, IReadOnlyList`1 _filenames, Boolean _import, Func`1 _showDialog, Action _onComplete, Dictionary`2& _yyImages)
   at YoYoStudio.Plugins.SpriteEditor.SpriteEditorModule.AddImagesWithResizeDialog(IReadOnlyList`1 _filenames, Boolean _import, Dictionary`2& _yyImages)
   at YoYoStudio.Plugins.SpriteEditor.SpriteEditorModule.AddImageFiles(IReadOnlyList`1 _filenames)
   at YoYoStudio.Plugins.SpriteEditor.SpriteEditorModule.DopeSheet_OnOsDndEvent(eOSDndEventType _type, Single _mousex, Single _mousey, IReadOnlyList`1 _filenames)
   at WeakDelegate(Object, Object[])
   at YoYoStudio.Core.Utils.WeakDelegate`1.Invoke(Object[] _args)
[15:12:20:260(3242)] ####################################
[15:12:20:263(3242)] Break in FatalErrorWarning (IDE:4796)
[15:12:20:267(3242)] ####################################
```

### Steps To Reproduce
1. Import one SVG image into the IDE
2. Drag and drop the second SVG images into the frames preview section of the first image
3. See the issue

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.693 Runtime v2024.1100.0.712

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

### Attached Files
* halloween.svg
* duck.svg

[8f347219-2593-4f99-9a70-aaa7bfcfaa8b](https://api.gamemaker.io/api/github/downloads/8f347219-2593-4f99-9a70-aaa7bfcfaa8b)

**Comment by yymrennie** [comment]
Fixed in 2024.13

**Comment by alicemoretti** [comment]
Verified fixed on IDE v2024.1300.0.722  Runtime v2024.1300.0.733. 
The IDE now triggers a popup saying that it's not possible to add additional frames to the SVG sprite (and it doesn't add the frame). 
Thank you.
