### ISSUE TITLE
YYC Fails to Build Variables used before Initialization

### ISSUE THREAD

**Issue by sanbox-irl** [YoYoGames/GameMaker-Bugs#8493]
The YYC crashes when it tries to build a program with only the following:

```
show_debug_message("Initial value is `" + string(self[$ "hello"]) + "`");

self.hello = "hello";

show_debug_message("Final Value is `" + string(self.hello) + "`");

```

Note: the VM compiles and runs the above code fine, and outputs the expected `undefined` and then `"hello"`.

--------

Additionally, this bug came up on Fields of Mistria where we had the following:

```
self.seasonal = self[$ "seasonal"] == undefined;
```
In that case, the compiler *did not* crash on compilation, and instead we got very bad code, where the RVal `self[$ "seasonal"]` evaluated to `0` (incorrectly -- should have been `undefined`) and thus the LVal `self.seasonal` was given `false` incorrectly.

**Comment by rwkay** [comment]
Unable to replicate - in the future please attach a project that illustrates the problem (the smaller the better) - I have tried in both a script and in an event and I cannot get YYC to crash - see my attached project

[Bug-8493a.zip](https://github.com/user-attachments/files/17903065/Bug-8493a.zip)

**Comment by sanbox-irl** [comment]
@rwkay I'm back post the Thanksgiving holiday here in America -- your included project *also* fails to compile on the YYC for me (windows, IDE v2024.8.1.171, Runtime v2024.8.1.218).

Here is the full output:

```
"C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2024.8.1.218/bin/igor/windows/x64/Igor.exe"  -j=8  -options="C:\Users\jjspi\AppData\Local\GameMakerStudio2\GMS2TEMP\build.bff" -v -- Windows Run

Loaded Macros from C:\Users\jjspi\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE\Bug-8493a_D4EFE1B7\macros.json
Options: C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2024.8.1.218\bin\platform_setting_defaults.json
Options: C:\Users\jjspi\AppData\Roaming/GameMakerStudio2\jjspira_1226692\local_settings.json
Options: C:\Users\jjspi\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE\Bug-8493a_D4EFE1B7\targetoptions.json
Setting up the Asset compiler
C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2024.8.1.218/bin/assetcompiler/windows/x64/GMAssetCompiler.dll  /c /mv=1 /zpex /iv=0 /rv=0 /bv=0 /j=8  /gn="Bug-8493a" /td="C:\Users\jjspi\AppData\Local\GameMakerStudio2\GMS2TEMP" /cd="C:\Users\jjspi\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE\Bug-8493a_D4EFE1B7" /rtp="C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2024.8.1.218" /zpuf="C:\Users\jjspi\AppData\Roaming/GameMakerStudio2\jjspira_1226692" /prefabs="C:\ProgramData/GameMakerStudio2/Prefabs"   /ffe="d3t+fjZrf25zeTdwgjZ5em98a3GCN4ODbTZzeH5vdnZzfW94fW82eH92dnN9cjZ2eXFzeGl9fXk2fm99fjZtf31+eXdpb3iANnBzdn41cII2cYJpd3luaYFrdnZ6a3pvfDZxgml3eW5pcWt3b31+fHN6NnZzgG9pgWt2dnprem98aX1/bH1tfHN6fnN5eA==" /m=llvm-win /tgt=64 /llvmSource="C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2024.8.1.218/yyc/"  /nodnd /cfg="Default" /o="C:\Users\jjspi\AppData\Local\GameMakerStudio2\GMS2TEMP\Bug-8493a_2D20C9A5_YYC" /sh=True /optionsini="C:\Users\jjspi\AppData\Local\GameMakerStudio2\GMS2TEMP\Bug-8493a_
2D20C9A5_YYC\options.ini" /baseproject="C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2024.8.1.218\BaseProject\BaseProject.yyp" "C:\Users\jjspi\GameMakerProjects\Bug-8493a\Bug-8493a.yyp" /preprocess="C:\Users\jjspi\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE\Bug-8493a_D4EFE1B7"
Found Project Format 2
+++ GMSC serialisation:  SUCCESSFUL LOAD AND LINK TIME: 252.5556ms
Loaded Project: Bug-8493a
finished.
Found Project Format 2
+++ GMSC serialisation:  SUCCESSFUL LOAD AND LINK TIME: 17.2564ms
Loaded Project: __yy_sdf_shader
finished.
Found Project Format 2
+++ GMSC serialisation:  SUCCESSFUL LOAD AND LINK TIME: 12.3066ms
Loaded Project: __yy_sdf_effect_shader
finished.
Found Project Format 2
+++ GMSC serialisation:  SUCCESSFUL LOAD AND LINK TIME: 15.8253ms
Loaded Project: __yy_sdf_blur_shader
finished.
Found Project Format 2
+++ GMSC serialisation:  SUCCESSFUL LOAD AND LINK TIME: 38.1111ms
Loaded Project: GMPresetParticles
finished.
Release build
Options: C:\Users\jjspi\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE\Bug-8493a_D4EFE1B7\ExtensionOptions.json
OptionsIni
Options: C:\Users\jjspi\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE\Bug-8493a_D4EFE1B7\PlatformOptions.json
[Compile] Run asset compiler (YYC)
C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2024.8.1.218/bin/assetcompiler/windows/x64/GMAssetCompiler.dll  /c /mv=1 /zpex /iv=0 /rv=0 /bv=0 /j=8  /gn="Bug-8493a" /td="C:\Users\jjspi\AppData\Local\GameMakerStudio2\GMS2TEMP" /cd="C:\Users\jjspi\AppData\Roaming\GameMakerStudio2\Cache\GMS2CACHE\Bug-8493a_D4EFE1B7" /rtp="C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2024.8.1.218" /zpuf="C:\Users\jjspi\AppData\Roaming/GameMakerStudio2\jjspira_1226692" /prefabs="C:\ProgramData/GameMakerStudio2/Prefabs"   /ffe="d3t+fjZrf25zeTdwgjZ5em98a3GCN4ODbTZzeH5vdnZzfW94fW82eH92dnN9cjZ2eXFzeGl9fXk2fm99fjZtf31+eXdpb3iANnBzdn41cII2cYJpd3luaYFrdnZ6a3pvfDZxgml3eW5pcWt3b31+fHN6NnZzgG9pgWt2dnprem98aX1/bH1tfHN6fnN5eA==" /m=llvm-win /tgt=64 /llvmSource="C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2024.8.1.218/yyc/"  /nodnd /cfg="Default" /o="C:\Users\jjspi\AppData\Local\GameMakerStudio2\GMS2TEMP\Bug-8493a_2D20C9A5_YYC" /sh=True /optionsini="C:\Users\jjspi\AppData\Local\GameMakerStudio2\GMS2TEMP\Bug-8493a_
2D20C9A5_YYC\options.ini" /baseproject="C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2024.8.1.218\BaseProject\BaseProject.yyp" "C:\Users\jjspi\GameMakerProjects\Bug-8493a\Bug-8493a.yyp" /debug /bt=run /rt=yyc /yyc64bit=true
Looking for built-in fallback image in C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2024.8.1.218\bin\BuiltinImages
Compiling Shader Shader___yy_sdf_shader... compiled with vs_4_0_level_9_1 (optimised)
Compiling Shader Shader___yy_sdf_shader... compiled with ps_4_0_level_9_3 (optimised)
Compiling Shader Shader___yy_sdf_effect_shader... compiled with vs_4_0_level_9_1 (optimised)
Compiling Shader Shader___yy_sdf_effect_shader... compiled with ps_4_0_level_9_3 (optimised)
Compiling Shader Shader___yy_sdf_blur_shader... compiled with vs_4_0_level_9_1 (optimised)
Compiling Shader Shader___yy_sdf_blur_shader... compiled with ps_4_0_level_9_1 (optimised)
Compile Constants...finished.
Remove DnD...finished.
Compile Scripts...finished.
Compile Rooms...finished..... 0 CC empty
Compile Objects...finished.... 0 empty events
Compile Timelines...finished.
Compile Triggers...finished.
Compile Extensions...finished.
Global scripts...finished.
finished.
collapsing enums.
Error : gml_GlobalScript_Script1(0) : Fatal Error while compiling gml_GlobalScript_Script1 - bailing details below
Final Compile...System.InvalidOperationException: Stack empty.
   at System.Collections.Generic.Stack`1.ThrowForEmptyStack()
   at System.Collections.Generic.Stack`1.Peek()
   at GMAssetCompiler.TypeDecorator.BinaryTypeCoercion(GMLToken _tok, Int32 _parmNum)
   at GMAssetCompiler.TypeDecorator.CompileBinary(GMLToken _tok)
   at GMAssetCompiler.TypeDecorator.CompileExpression(GMLToken _tok)
   at GMAssetCompiler.TypeDecorator.CompileFunction(GMLToken _tok)
   at GMAssetCompiler.TypeDecorator.CompileStatement(GMLToken _tok)
   at GMAssetCompiler.TypeDecorator.CompileBlock(GMLToken _tok)
   at GMAssetCompiler.TypeDecorator.DoIt(GMLToken _tok)
   at GMAssetCompiler.GML2CPP.Compile(GMAssets _assets, GMLCode _code)
System.InvalidOperationException: Stack empty.
   at System.Collections.Generic.Stack`1.ThrowForEmptyStack()
   at System.Collections.Generic.Stack`1.Peek()
   at GMAssetCompiler.TypeDecorator.BinaryTypeCoercion(GMLToken _tok, Int32 _parmNum)
   at GMAssetCompiler.TypeDecorator.CompileBinary(GMLToken _tok)
   at GMAssetCompiler.TypeDecorator.CompileExpression(GMLToken _tok)
   at GMAssetCompiler.TypeDecorator.CompileFunction(GMLToken _tok)
   at GMAssetCompiler.TypeDecorator.CompileStatement(GMLToken _tok)
   at GMAssetCompiler.TypeDecorator.CompileBlock(GMLToken _tok)
   at GMAssetCompiler.TypeDecorator.DoIt(GMLToken _tok)
   at GMAssetCompiler.GML2CPP.Compile(GMAssets _assets, GMLCode _code)
Error : gml_Object_Object1_Create_0(0) : Fatal Error while compiling gml_Object_Object1_Create_0 - bailing details below
finished.
Stats : GMA : Elapsed=421.8471
Stats : GMA : sp=0,au=0,bk=0,pt=0,sc=1,sh=3,fo=0,tl=0,ob=1,ro=1,da=0,ex=0,ma=0,fm=0x840040000
C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2024.8.1.218/bin/assetcompiler/windows/x64/GMAssetCompiler.dll exited with non-zero status (1)
elapsed time 00:00:01.3137380s for command "C:\ProgramData/GameMakerStudio2/Cache/runtimes\runtime-2024.8.1.218/bin/igor/windows/x64/Igor.exe" -j=8  -options="C:\Users\jjspi\AppData\Local\GameMakerStudio2\GMS2TEMP\build.bff" -v -- Windows Run started at 12/03/2024 13:15:29
FAILED: Run Program Complete
For the details of why this build failed, please review the whole log above and also see your Compile Errors window.
```

**Comment by rwkay** [comment]
This is fixed on the Beta
