### ISSUE TITLE
Code Editor 2: GM crash when showing a tooltip

### ISSUE THREAD

**Issue by Lukanibal** [YoYoGames/GameMaker-Bugs#8591]
### Description
I was editing a lot of code in the new editor, I probably had 10 or 12 tabs open of object editors in CE2. I was copying/pasting more than usual, but otherwise I have no idea what caused the crash.

### Steps To Reproduce
I honestly have no idea, I hope the logs help find the issue, I'm really sorry I don't have more info.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.700 Runtime v2024.1100.0.718

### Which operating system(s) are you seeing the problem on?
Windows 10.0.26100.0

[13f2ef64-7ef8-4a14-90bb-b88f2881b15e](https://api.gamemaker.io/api/github/downloads/13f2ef64-7ef8-4a14-90bb-b88f2881b15e)

**Comment by stuckie** [comment]
So this looks like it's crashed specifically trying to make a tooltip

> Exception stack:    at YoYoStudio.GUI.Gadgets.TextEditor2.TextEditorPanel.XyToLineColumn(Single x, Single y, Int32& line, Int32& column, Boolean clampColumn)
>    at YoYoStudio.GUI.Gadgets.TextEditor2.Components.TooltipComponent.OnMouseOver(Single _mousex, Single _mousey, eMouseButtons _buttons)
>    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
>    at System.Threading.QueueUserWorkItemCallbackDefaultContext`1.Execute()
>    at System.Threading.ThreadPoolWorkQueue.Dispatch()
>    at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
> [10:59:14:905(627d)] --------------------------------------------------------------------------------

**Comment by thennothinghappened** [comment]
#8784 and #8861 are likely duplicates of this issue.

**Comment by stuckie** [comment]
This should be fixed as of 2024.1300.0.732

**Comment by sihammill** [comment]
This appears to be fixed in IDE v2024.1300.0.769  Runtime v2024.1300.0.776
