### ISSUE TITLE
Building Projects: [Android] Attempting to run the base extension demo fails with a duplicate key error in November Betas

### ISSUE THREAD

**Issue by Emc1923** [YoYoGames/GameMaker-Bugs#8633]
Attempting to build the base extension demo project currently fails as of  IDE v2024.1100.0.703  Runtime v2024.1100.0.719 with the following exception:

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: An item with the same key has already been added. Key: YYAndroidManifestApplicationAttributes
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at GMAssetCompiler.WADSaver`1.<>c__DisplayClass146_1.<HandleAndroidExtensions>b__0(XElement elem)
   at GMAssetCompiler.CodeInjectionUtils.HandleCodeInjectionTags(String codeInjection, Dictionary`2 env, String tagPrefix, Action`1 codeInjectionHandler, Dictionary`2 xmlNamespaces)
   at GMAssetCompiler.WADSaver`1.HandleAndroidExtensions(Dictionary`2 _env, String _target, String _domain, String _company, String _product, String _destAndroidDir, String _runtimeDir)
   at GMAssetCompiler.Program.HandleAndroidExtensions(Dictionary`2 _env, String _target, String _domain, String _company, String _product, String _destAndroidDir, String _runtimeDir)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Igor.Program.HandleAndroidExtensions(YYDictionary`2 _env, String _target, String _domain, String _company, String _product, String _destAndroidDir, String _runtimeDir)
   at Igor.AndroidUtils.HandleExtensions(YYDictionary`2 _env, String _target, String _domain, String _company, String _product)
   at Igor.AndroidUtils.CreateAPK(YYDictionary`2 _env, String _apk, Boolean _exe, String _target, AndroidBuilder builder)
   at Igor.AndroidBuilder.Deploy(Boolean _exe)
   at Igor.AndroidBuilder.Run()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

[bugPackage.zip](https://github.com/user-attachments/files/18023644/bugPackage.zip)

### Steps To Reproduce

1. Start Gamemaker
2. Get the most recent extension release from this repo https://github.com/YoYoGames/GMEXT-MobileUtils
3. Create a new project by importing the local package
4. Run for Android VM/YYC
5. See the issue

**Comment by Emc1923** [comment]
Verified fixed in  IDE v2024.1100.0.710  Runtime v2024.1100.0.726.
