### ISSUE TITLE
Debugger: GM unstable when stepping into instance creation code if CE2 is enabled

### ISSUE THREAD

**Issue by iampremo** [YoYoGames/GameMaker-Bugs#8686]
### Description
Added new breakpoint to instance creation code, every time I hit that breakpoint the ide goes unstable until the debugger is closed.

### Steps To Reproduce
Enable CE2
Add break point
Debug
Hit breakpoint

### Which version of GameMaker are you reporting this issue for?
IDE v2024.1100.0.711 Runtime v2024.1100.0.726

### Which operating system(s) are you seeing the problem on?
Windows 10.0.22631.0

[866b5403-8eee-4570-adb2-49f3a7073f02](https://api.gamemaker.io/api/github/downloads/866b5403-8eee-4570-adb2-49f3a7073f02)

**Comment by YYDan** [comment]
Esther gets

```
[08:52:26:908(7f27)] ####################################
[08:52:26:909(7f27)] Break in BreakpointToScriptLocation (BreakpointManager:492)
[08:52:26:910(7f27)] ####################################
[08:52:26:911(7f27)] Failed to determine breakpoint type
```

Scott gets

```
[08:57:18:508(e1ce)] Exception in YoYoStudio.GUI.Gadgets.TextEditor2.DocumentWindow_FoldingPanel+HeaderGadget,Void DocumentFoldingGadget_Render(System.TimeSpan, YoYoStudio.Core.Utils.rect) :    System.NullReferenceException: Object reference not set to an instance of an object.
   at YoYoStudio.GUI.Gadgets.TextEditor2.DocumentWindow_FoldingPanel.HeaderGadget.DocumentFoldingGadget_Render(TimeSpan deltaTime, rect contentArea)
   at WeakDelegate(Object, Object[])
   at YoYoStudio.Core.Utils.WeakDelegate`1.Invoke(Object[] _args)
```


Note that although the exception is logged each time, not all users get shown the unstable dialog for this issue when it happens - depends on your licence type.

**Comment by scott-dunbar** [comment]
Verified fixed in 
 IDE v2024.11.0.179  Runtime v2024.11.0.226
