### ISSUE TITLE
"Report a bug" pop-up can't be opened again after closing it

### ISSUE THREAD

**Issue by Notlea** [YoYoGames/GameMaker-Bugs#8779]
### Description

As title

### Steps To Reproduce

1. Help -> Report a Gamemaker bug
2. Put that pop-up inside Asset browser panel (it wasn't intentional in the first place)
3. Right click on the top of the newly placed pop-up in the asset browser -> Click "Close"
4. Pop-up closes and can't be opened again through Help -> Report GM bug until Gamemaker restart

Reproduce is even simplier:  You can't open that pop-up second time until GM restart

Bonus points: all buttons, except "Close" in the top right corner, aren't working in the pop-up.

[ui-2024-12-19-04-18-54.gz](https://github.com/user-attachments/files/18200253/ui-2024-12-19-04-18-54.gz)

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

2024.11.0 (Monthly)

### Which operating system(s) are you seeing the problem on?

Windows 11

### Are you running GameMaker from inside your Steam library?

None

### Sample Package Attached?

- [x] I have attached my bug package

### Sample Project Added?

- [ ] I have included a small sample project

**Comment by Notlea** [comment]
This bug doesn't reproduce on the new beta that dropped today. I also successfully reported one bug through it.

**Comment by stuckie** [comment]
ui.log has a few of the following to look into at least

> [15:55:55:853(f0eb)] Exception in YoYoStudio.GUI.Gadgets.MenuEntry,Void ReleaseButton(Single, Single, YoYoStudio.Core.Utils.eMouseButtons) :    System.NullReferenceException: Object reference not set to an instance of an object.
>    at YoYoStudio.Plugins.BugReporter.CreateBugReportModule.ShowBugReportDialog()
>    at YoYoStudio.Plugins.BugReporter.CreateBugReportModule.CheckRuntimeVersion()
>    at YoYoStudio.Plugins.BugReporter.CreateBugReportModule.Initialise(ModulePackage _ide)
>    at YoYoStudio.Plugins.ResourceEditorManager.ActivateModule(Type _type, Object[] _parameters)
>    at YoYoStudio.Plugins.Command.execute_object(String _command, Object _focus, Object[] paramaters)
>    at YoYoStudio.GUI.Gadgets.Button.ButtonClicked(Boolean _bRightClicked)
>    at YoYoStudio.GUI.Gadgets.Button.ReleaseButton(Single _mousex, Single _mousey, eMouseButtons _buttons)
>    at WeakDelegate(Object, Object[])
>    at YoYoStudio.Core.Utils.WeakDelegate`1.Invoke(Object[] _args)

**Comment by stuckie** [comment]
Yep as above this appears to have already been fixed.

**Comment by scott-dunbar** [comment]
Verified fixed in  IDE v2024.1300.0.770  Runtime v2024.1300.0.777
