### ISSUE TITLE
Code Editor 2: Freeze and silent crash on clicking text at EOL(?)

### ISSUE THREAD

**Issue by thennothinghappened** [YoYoGames/GameMaker-Bugs#8861]
### Description
Fatal crash whilst using CE2 - see reproduction information below.

### Steps To Reproduce
Unfortunately I don't have much for this one, it just kinda happened.

What I had been doing at the time the crash occurred however, was writing out a method in an object, and clicked the mouse at the end of the line whilst writing it. Upon doing so, the IDE froze, my fans spun up - did not have time to check if a core was being pinned, but likely so - and shortly thereafter silently crashed. The method in question I'd just started writing a JSDoc header for, moments earlier. This may be relevant, given the second line of the stacktrace is `TooltipComponent.OnMouseOver`.

Doubly unfortunately, I'm not 100% sure if my account of my actions that lead to the crash are accurate. I am *pretty sure*, since I've also noted occasional (non-fatal) freezes in seemingly random circumstances on moving the text cursor with the mouse.

### Which version of GameMaker are you reporting this issue for?
IDE v2024.11.0.179 Runtime v2024.11.0.227

### Which operating system(s) are you seeing the problem on?
Windows 10.0.19045.0

[02e292bb-e8ed-485f-9483-c3831517cfcb](https://api.gamemaker.io/api/github/downloads/02e292bb-e8ed-485f-9483-c3831517cfcb)

**Comment by stuckie** [comment]
Same Exception as others:

> Exception stack: at YoYoStudio.GUI.Gadgets.TextEditor2.TextEditorPanel.XyToLineColumn(Single x, Single y, Int32& line, Int32& column, Boolean clampColumn)
> at YoYoStudio.GUI.Gadgets.TextEditor2.Components.TooltipComponent.OnMouseOver(Single _mousex, Single _mousey, eMouseButtons _buttons)
> at System.Threading.Tasks.Task.<>c.b__128_0(Object state)
> at System.Threading.QueueUserWorkItemCallbackDefaultContext`1.Execute()
> at System.Threading.ThreadPoolWorkQueue.Dispatch()
> at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
> [10:59:14:905(627d)] --------------------------------------------------------------------------------
